// Code generated by ent, DO NOT EDIT.

package graphedge

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the graphedge type in the database.
	Label = "graph_edge"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantKey holds the string denoting the tenant_key field in the database.
	FieldTenantKey = "tenant_key"
	// FieldFromID holds the string denoting the from_id field in the database.
	FieldFromID = "from_id"
	// FieldToID holds the string denoting the to_id field in the database.
	FieldToID = "to_id"
	// FieldRelationship holds the string denoting the relationship field in the database.
	FieldRelationship = "relationship"
	// FieldRationale holds the string denoting the rationale field in the database.
	FieldRationale = "rationale"
	// FieldReviewState holds the string denoting the review_state field in the database.
	FieldReviewState = "review_state"
	// FieldTombstonedAt holds the string denoting the tombstoned_at field in the database.
	FieldTombstonedAt = "tombstoned_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the graphedge in the database.
	Table = "graph_edges"
)

// Columns holds all SQL columns for graphedge fields.
var Columns = []string{
	FieldID,
	FieldTenantKey,
	FieldFromID,
	FieldToID,
	FieldRelationship,
	FieldRationale,
	FieldReviewState,
	FieldTombstonedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTenantKey holds the default value on creation for the "tenant_key" field.
	DefaultTenantKey string
	// TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	TenantKeyValidator func(string) error
	// RelationshipValidator is a validator for the "relationship" field. It is called by the builders before save.
	RelationshipValidator func(string) error
	// DefaultReviewState holds the default value on creation for the "review_state" field.
	DefaultReviewState string
	// ReviewStateValidator is a validator for the "review_state" field. It is called by the builders before save.
	ReviewStateValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the GraphEdge queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantKey orders the results by the tenant_key field.
func ByTenantKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantKey, opts...).ToFunc()
}

// ByFromID orders the results by the from_id field.
func ByFromID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromID, opts...).ToFunc()
}

// ByToID orders the results by the to_id field.
func ByToID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToID, opts...).ToFunc()
}

// ByRelationship orders the results by the relationship field.
func ByRelationship(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelationship, opts...).ToFunc()
}

// ByRationale orders the results by the rationale field.
func ByRationale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRationale, opts...).ToFunc()
}

// ByReviewState orders the results by the review_state field.
func ByReviewState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewState, opts...).ToFunc()
}

// ByTombstonedAt orders the results by the tombstoned_at field.
func ByTombstonedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTombstonedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
