// Code generated by ent, DO NOT EDIT.

package graphedge

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLTE(FieldID, id))
}

// TenantKey applies equality check predicate on the "tenant_key" field. It's identical to TenantKeyEQ.
func TenantKey(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldTenantKey, v))
}

// FromID applies equality check predicate on the "from_id" field. It's identical to FromIDEQ.
func FromID(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldFromID, v))
}

// ToID applies equality check predicate on the "to_id" field. It's identical to ToIDEQ.
func ToID(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldToID, v))
}

// Relationship applies equality check predicate on the "relationship" field. It's identical to RelationshipEQ.
func Relationship(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldRelationship, v))
}

// Rationale applies equality check predicate on the "rationale" field. It's identical to RationaleEQ.
func Rationale(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldRationale, v))
}

// ReviewState applies equality check predicate on the "review_state" field. It's identical to ReviewStateEQ.
func ReviewState(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldReviewState, v))
}

// TombstonedAt applies equality check predicate on the "tombstoned_at" field. It's identical to TombstonedAtEQ.
func TombstonedAt(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldTombstonedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantKeyEQ applies the EQ predicate on the "tenant_key" field.
func TenantKeyEQ(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldTenantKey, v))
}

// TenantKeyNEQ applies the NEQ predicate on the "tenant_key" field.
func TenantKeyNEQ(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNEQ(FieldTenantKey, v))
}

// TenantKeyIn applies the In predicate on the "tenant_key" field.
func TenantKeyIn(vs ...string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIn(FieldTenantKey, vs...))
}

// TenantKeyNotIn applies the NotIn predicate on the "tenant_key" field.
func TenantKeyNotIn(vs ...string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotIn(FieldTenantKey, vs...))
}

// TenantKeyGT applies the GT predicate on the "tenant_key" field.
func TenantKeyGT(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGT(FieldTenantKey, v))
}

// TenantKeyGTE applies the GTE predicate on the "tenant_key" field.
func TenantKeyGTE(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGTE(FieldTenantKey, v))
}

// TenantKeyLT applies the LT predicate on the "tenant_key" field.
func TenantKeyLT(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLT(FieldTenantKey, v))
}

// TenantKeyLTE applies the LTE predicate on the "tenant_key" field.
func TenantKeyLTE(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLTE(FieldTenantKey, v))
}

// TenantKeyContains applies the Contains predicate on the "tenant_key" field.
func TenantKeyContains(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldContains(FieldTenantKey, v))
}

// TenantKeyHasPrefix applies the HasPrefix predicate on the "tenant_key" field.
func TenantKeyHasPrefix(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldHasPrefix(FieldTenantKey, v))
}

// TenantKeyHasSuffix applies the HasSuffix predicate on the "tenant_key" field.
func TenantKeyHasSuffix(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldHasSuffix(FieldTenantKey, v))
}

// TenantKeyEqualFold applies the EqualFold predicate on the "tenant_key" field.
func TenantKeyEqualFold(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEqualFold(FieldTenantKey, v))
}

// TenantKeyContainsFold applies the ContainsFold predicate on the "tenant_key" field.
func TenantKeyContainsFold(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldContainsFold(FieldTenantKey, v))
}

// FromIDEQ applies the EQ predicate on the "from_id" field.
func FromIDEQ(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldFromID, v))
}

// FromIDNEQ applies the NEQ predicate on the "from_id" field.
func FromIDNEQ(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNEQ(FieldFromID, v))
}

// FromIDIn applies the In predicate on the "from_id" field.
func FromIDIn(vs ...uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIn(FieldFromID, vs...))
}

// FromIDNotIn applies the NotIn predicate on the "from_id" field.
func FromIDNotIn(vs ...uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotIn(FieldFromID, vs...))
}

// FromIDGT applies the GT predicate on the "from_id" field.
func FromIDGT(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGT(FieldFromID, v))
}

// FromIDGTE applies the GTE predicate on the "from_id" field.
func FromIDGTE(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGTE(FieldFromID, v))
}

// FromIDLT applies the LT predicate on the "from_id" field.
func FromIDLT(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLT(FieldFromID, v))
}

// FromIDLTE applies the LTE predicate on the "from_id" field.
func FromIDLTE(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLTE(FieldFromID, v))
}

// ToIDEQ applies the EQ predicate on the "to_id" field.
func ToIDEQ(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldToID, v))
}

// ToIDNEQ applies the NEQ predicate on the "to_id" field.
func ToIDNEQ(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNEQ(FieldToID, v))
}

// ToIDIn applies the In predicate on the "to_id" field.
func ToIDIn(vs ...uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIn(FieldToID, vs...))
}

// ToIDNotIn applies the NotIn predicate on the "to_id" field.
func ToIDNotIn(vs ...uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotIn(FieldToID, vs...))
}

// ToIDGT applies the GT predicate on the "to_id" field.
func ToIDGT(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGT(FieldToID, v))
}

// ToIDGTE applies the GTE predicate on the "to_id" field.
func ToIDGTE(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGTE(FieldToID, v))
}

// ToIDLT applies the LT predicate on the "to_id" field.
func ToIDLT(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLT(FieldToID, v))
}

// ToIDLTE applies the LTE predicate on the "to_id" field.
func ToIDLTE(v uuid.UUID) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLTE(FieldToID, v))
}

// RelationshipEQ applies the EQ predicate on the "relationship" field.
func RelationshipEQ(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldRelationship, v))
}

// RelationshipNEQ applies the NEQ predicate on the "relationship" field.
func RelationshipNEQ(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNEQ(FieldRelationship, v))
}

// RelationshipIn applies the In predicate on the "relationship" field.
func RelationshipIn(vs ...string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIn(FieldRelationship, vs...))
}

// RelationshipNotIn applies the NotIn predicate on the "relationship" field.
func RelationshipNotIn(vs ...string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotIn(FieldRelationship, vs...))
}

// RelationshipGT applies the GT predicate on the "relationship" field.
func RelationshipGT(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGT(FieldRelationship, v))
}

// RelationshipGTE applies the GTE predicate on the "relationship" field.
func RelationshipGTE(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGTE(FieldRelationship, v))
}

// RelationshipLT applies the LT predicate on the "relationship" field.
func RelationshipLT(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLT(FieldRelationship, v))
}

// RelationshipLTE applies the LTE predicate on the "relationship" field.
func RelationshipLTE(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLTE(FieldRelationship, v))
}

// RelationshipContains applies the Contains predicate on the "relationship" field.
func RelationshipContains(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldContains(FieldRelationship, v))
}

// RelationshipHasPrefix applies the HasPrefix predicate on the "relationship" field.
func RelationshipHasPrefix(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldHasPrefix(FieldRelationship, v))
}

// RelationshipHasSuffix applies the HasSuffix predicate on the "relationship" field.
func RelationshipHasSuffix(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldHasSuffix(FieldRelationship, v))
}

// RelationshipEqualFold applies the EqualFold predicate on the "relationship" field.
func RelationshipEqualFold(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEqualFold(FieldRelationship, v))
}

// RelationshipContainsFold applies the ContainsFold predicate on the "relationship" field.
func RelationshipContainsFold(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldContainsFold(FieldRelationship, v))
}

// RationaleEQ applies the EQ predicate on the "rationale" field.
func RationaleEQ(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldRationale, v))
}

// RationaleNEQ applies the NEQ predicate on the "rationale" field.
func RationaleNEQ(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNEQ(FieldRationale, v))
}

// RationaleIn applies the In predicate on the "rationale" field.
func RationaleIn(vs ...string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIn(FieldRationale, vs...))
}

// RationaleNotIn applies the NotIn predicate on the "rationale" field.
func RationaleNotIn(vs ...string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotIn(FieldRationale, vs...))
}

// RationaleGT applies the GT predicate on the "rationale" field.
func RationaleGT(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGT(FieldRationale, v))
}

// RationaleGTE applies the GTE predicate on the "rationale" field.
func RationaleGTE(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGTE(FieldRationale, v))
}

// RationaleLT applies the LT predicate on the "rationale" field.
func RationaleLT(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLT(FieldRationale, v))
}

// RationaleLTE applies the LTE predicate on the "rationale" field.
func RationaleLTE(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLTE(FieldRationale, v))
}

// RationaleContains applies the Contains predicate on the "rationale" field.
func RationaleContains(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldContains(FieldRationale, v))
}

// RationaleHasPrefix applies the HasPrefix predicate on the "rationale" field.
func RationaleHasPrefix(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldHasPrefix(FieldRationale, v))
}

// RationaleHasSuffix applies the HasSuffix predicate on the "rationale" field.
func RationaleHasSuffix(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldHasSuffix(FieldRationale, v))
}

// RationaleIsNil applies the IsNil predicate on the "rationale" field.
func RationaleIsNil() predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIsNull(FieldRationale))
}

// RationaleNotNil applies the NotNil predicate on the "rationale" field.
func RationaleNotNil() predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotNull(FieldRationale))
}

// RationaleEqualFold applies the EqualFold predicate on the "rationale" field.
func RationaleEqualFold(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEqualFold(FieldRationale, v))
}

// RationaleContainsFold applies the ContainsFold predicate on the "rationale" field.
func RationaleContainsFold(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldContainsFold(FieldRationale, v))
}

// ReviewStateEQ applies the EQ predicate on the "review_state" field.
func ReviewStateEQ(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldReviewState, v))
}

// ReviewStateNEQ applies the NEQ predicate on the "review_state" field.
func ReviewStateNEQ(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNEQ(FieldReviewState, v))
}

// ReviewStateIn applies the In predicate on the "review_state" field.
func ReviewStateIn(vs ...string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIn(FieldReviewState, vs...))
}

// ReviewStateNotIn applies the NotIn predicate on the "review_state" field.
func ReviewStateNotIn(vs ...string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotIn(FieldReviewState, vs...))
}

// ReviewStateGT applies the GT predicate on the "review_state" field.
func ReviewStateGT(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGT(FieldReviewState, v))
}

// ReviewStateGTE applies the GTE predicate on the "review_state" field.
func ReviewStateGTE(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGTE(FieldReviewState, v))
}

// ReviewStateLT applies the LT predicate on the "review_state" field.
func ReviewStateLT(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLT(FieldReviewState, v))
}

// ReviewStateLTE applies the LTE predicate on the "review_state" field.
func ReviewStateLTE(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLTE(FieldReviewState, v))
}

// ReviewStateContains applies the Contains predicate on the "review_state" field.
func ReviewStateContains(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldContains(FieldReviewState, v))
}

// ReviewStateHasPrefix applies the HasPrefix predicate on the "review_state" field.
func ReviewStateHasPrefix(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldHasPrefix(FieldReviewState, v))
}

// ReviewStateHasSuffix applies the HasSuffix predicate on the "review_state" field.
func ReviewStateHasSuffix(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldHasSuffix(FieldReviewState, v))
}

// ReviewStateEqualFold applies the EqualFold predicate on the "review_state" field.
func ReviewStateEqualFold(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEqualFold(FieldReviewState, v))
}

// ReviewStateContainsFold applies the ContainsFold predicate on the "review_state" field.
func ReviewStateContainsFold(v string) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldContainsFold(FieldReviewState, v))
}

// TombstonedAtEQ applies the EQ predicate on the "tombstoned_at" field.
func TombstonedAtEQ(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldTombstonedAt, v))
}

// TombstonedAtNEQ applies the NEQ predicate on the "tombstoned_at" field.
func TombstonedAtNEQ(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNEQ(FieldTombstonedAt, v))
}

// TombstonedAtIn applies the In predicate on the "tombstoned_at" field.
func TombstonedAtIn(vs ...time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIn(FieldTombstonedAt, vs...))
}

// TombstonedAtNotIn applies the NotIn predicate on the "tombstoned_at" field.
func TombstonedAtNotIn(vs ...time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotIn(FieldTombstonedAt, vs...))
}

// TombstonedAtGT applies the GT predicate on the "tombstoned_at" field.
func TombstonedAtGT(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGT(FieldTombstonedAt, v))
}

// TombstonedAtGTE applies the GTE predicate on the "tombstoned_at" field.
func TombstonedAtGTE(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGTE(FieldTombstonedAt, v))
}

// TombstonedAtLT applies the LT predicate on the "tombstoned_at" field.
func TombstonedAtLT(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLT(FieldTombstonedAt, v))
}

// TombstonedAtLTE applies the LTE predicate on the "tombstoned_at" field.
func TombstonedAtLTE(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLTE(FieldTombstonedAt, v))
}

// TombstonedAtIsNil applies the IsNil predicate on the "tombstoned_at" field.
func TombstonedAtIsNil() predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIsNull(FieldTombstonedAt))
}

// TombstonedAtNotNil applies the NotNil predicate on the "tombstoned_at" field.
func TombstonedAtNotNil() predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotNull(FieldTombstonedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GraphEdge {
	return predicate.GraphEdge(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GraphEdge) predicate.GraphEdge {
	return predicate.GraphEdge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GraphEdge) predicate.GraphEdge {
	return predicate.GraphEdge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GraphEdge) predicate.GraphEdge {
	return predicate.GraphEdge(sql.NotPredicates(p))
}
