// Code generated by ent, DO NOT EDIT.

package vote

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldID, id))
}

// TenantKey applies equality check predicate on the "tenant_key" field. It's identical to TenantKeyEQ.
func TenantKey(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldTenantKey, v))
}

// InsightID applies equality check predicate on the "insight_id" field. It's identical to InsightIDEQ.
func InsightID(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldInsightID, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldActorID, v))
}

// ProblemFingerprintID applies equality check predicate on the "problem_fingerprint_id" field. It's identical to ProblemFingerprintIDEQ.
func ProblemFingerprintID(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldProblemFingerprintID, v))
}

// Outcome applies equality check predicate on the "outcome" field. It's identical to OutcomeEQ.
func Outcome(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldOutcome, v))
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v float64) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldConfidence, v))
}

// Rationale applies equality check predicate on the "rationale" field. It's identical to RationaleEQ.
func Rationale(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldRationale, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldIdempotencyKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantKeyEQ applies the EQ predicate on the "tenant_key" field.
func TenantKeyEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldTenantKey, v))
}

// TenantKeyNEQ applies the NEQ predicate on the "tenant_key" field.
func TenantKeyNEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldTenantKey, v))
}

// TenantKeyIn applies the In predicate on the "tenant_key" field.
func TenantKeyIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldTenantKey, vs...))
}

// TenantKeyNotIn applies the NotIn predicate on the "tenant_key" field.
func TenantKeyNotIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldTenantKey, vs...))
}

// TenantKeyGT applies the GT predicate on the "tenant_key" field.
func TenantKeyGT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldTenantKey, v))
}

// TenantKeyGTE applies the GTE predicate on the "tenant_key" field.
func TenantKeyGTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldTenantKey, v))
}

// TenantKeyLT applies the LT predicate on the "tenant_key" field.
func TenantKeyLT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldTenantKey, v))
}

// TenantKeyLTE applies the LTE predicate on the "tenant_key" field.
func TenantKeyLTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldTenantKey, v))
}

// TenantKeyContains applies the Contains predicate on the "tenant_key" field.
func TenantKeyContains(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContains(FieldTenantKey, v))
}

// TenantKeyHasPrefix applies the HasPrefix predicate on the "tenant_key" field.
func TenantKeyHasPrefix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasPrefix(FieldTenantKey, v))
}

// TenantKeyHasSuffix applies the HasSuffix predicate on the "tenant_key" field.
func TenantKeyHasSuffix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasSuffix(FieldTenantKey, v))
}

// TenantKeyEqualFold applies the EqualFold predicate on the "tenant_key" field.
func TenantKeyEqualFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEqualFold(FieldTenantKey, v))
}

// TenantKeyContainsFold applies the ContainsFold predicate on the "tenant_key" field.
func TenantKeyContainsFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContainsFold(FieldTenantKey, v))
}

// InsightIDEQ applies the EQ predicate on the "insight_id" field.
func InsightIDEQ(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldInsightID, v))
}

// InsightIDNEQ applies the NEQ predicate on the "insight_id" field.
func InsightIDNEQ(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldInsightID, v))
}

// InsightIDIn applies the In predicate on the "insight_id" field.
func InsightIDIn(vs ...uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldInsightID, vs...))
}

// InsightIDNotIn applies the NotIn predicate on the "insight_id" field.
func InsightIDNotIn(vs ...uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldInsightID, vs...))
}

// InsightIDGT applies the GT predicate on the "insight_id" field.
func InsightIDGT(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldInsightID, v))
}

// InsightIDGTE applies the GTE predicate on the "insight_id" field.
func InsightIDGTE(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldInsightID, v))
}

// InsightIDLT applies the LT predicate on the "insight_id" field.
func InsightIDLT(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldInsightID, v))
}

// InsightIDLTE applies the LTE predicate on the "insight_id" field.
func InsightIDLTE(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldInsightID, v))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldActorID, v))
}

// ActorIDIsNil applies the IsNil predicate on the "actor_id" field.
func ActorIDIsNil() predicate.Vote {
	return predicate.Vote(sql.FieldIsNull(FieldActorID))
}

// ActorIDNotNil applies the NotNil predicate on the "actor_id" field.
func ActorIDNotNil() predicate.Vote {
	return predicate.Vote(sql.FieldNotNull(FieldActorID))
}

// ProblemFingerprintIDEQ applies the EQ predicate on the "problem_fingerprint_id" field.
func ProblemFingerprintIDEQ(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldProblemFingerprintID, v))
}

// ProblemFingerprintIDNEQ applies the NEQ predicate on the "problem_fingerprint_id" field.
func ProblemFingerprintIDNEQ(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldProblemFingerprintID, v))
}

// ProblemFingerprintIDIn applies the In predicate on the "problem_fingerprint_id" field.
func ProblemFingerprintIDIn(vs ...uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldProblemFingerprintID, vs...))
}

// ProblemFingerprintIDNotIn applies the NotIn predicate on the "problem_fingerprint_id" field.
func ProblemFingerprintIDNotIn(vs ...uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldProblemFingerprintID, vs...))
}

// ProblemFingerprintIDGT applies the GT predicate on the "problem_fingerprint_id" field.
func ProblemFingerprintIDGT(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldProblemFingerprintID, v))
}

// ProblemFingerprintIDGTE applies the GTE predicate on the "problem_fingerprint_id" field.
func ProblemFingerprintIDGTE(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldProblemFingerprintID, v))
}

// ProblemFingerprintIDLT applies the LT predicate on the "problem_fingerprint_id" field.
func ProblemFingerprintIDLT(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldProblemFingerprintID, v))
}

// ProblemFingerprintIDLTE applies the LTE predicate on the "problem_fingerprint_id" field.
func ProblemFingerprintIDLTE(v uuid.UUID) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldProblemFingerprintID, v))
}

// ProblemFingerprintIDIsNil applies the IsNil predicate on the "problem_fingerprint_id" field.
func ProblemFingerprintIDIsNil() predicate.Vote {
	return predicate.Vote(sql.FieldIsNull(FieldProblemFingerprintID))
}

// ProblemFingerprintIDNotNil applies the NotNil predicate on the "problem_fingerprint_id" field.
func ProblemFingerprintIDNotNil() predicate.Vote {
	return predicate.Vote(sql.FieldNotNull(FieldProblemFingerprintID))
}

// OutcomeEQ applies the EQ predicate on the "outcome" field.
func OutcomeEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldOutcome, v))
}

// OutcomeNEQ applies the NEQ predicate on the "outcome" field.
func OutcomeNEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldOutcome, v))
}

// OutcomeIn applies the In predicate on the "outcome" field.
func OutcomeIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldOutcome, vs...))
}

// OutcomeNotIn applies the NotIn predicate on the "outcome" field.
func OutcomeNotIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldOutcome, vs...))
}

// OutcomeGT applies the GT predicate on the "outcome" field.
func OutcomeGT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldOutcome, v))
}

// OutcomeGTE applies the GTE predicate on the "outcome" field.
func OutcomeGTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldOutcome, v))
}

// OutcomeLT applies the LT predicate on the "outcome" field.
func OutcomeLT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldOutcome, v))
}

// OutcomeLTE applies the LTE predicate on the "outcome" field.
func OutcomeLTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldOutcome, v))
}

// OutcomeContains applies the Contains predicate on the "outcome" field.
func OutcomeContains(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContains(FieldOutcome, v))
}

// OutcomeHasPrefix applies the HasPrefix predicate on the "outcome" field.
func OutcomeHasPrefix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasPrefix(FieldOutcome, v))
}

// OutcomeHasSuffix applies the HasSuffix predicate on the "outcome" field.
func OutcomeHasSuffix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasSuffix(FieldOutcome, v))
}

// OutcomeEqualFold applies the EqualFold predicate on the "outcome" field.
func OutcomeEqualFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEqualFold(FieldOutcome, v))
}

// OutcomeContainsFold applies the ContainsFold predicate on the "outcome" field.
func OutcomeContainsFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContainsFold(FieldOutcome, v))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v float64) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v float64) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...float64) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...float64) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldConfidence, vs...))
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v float64) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldConfidence, v))
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v float64) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldConfidence, v))
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v float64) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldConfidence, v))
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v float64) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldConfidence, v))
}

// RationaleEQ applies the EQ predicate on the "rationale" field.
func RationaleEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldRationale, v))
}

// RationaleNEQ applies the NEQ predicate on the "rationale" field.
func RationaleNEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldRationale, v))
}

// RationaleIn applies the In predicate on the "rationale" field.
func RationaleIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldRationale, vs...))
}

// RationaleNotIn applies the NotIn predicate on the "rationale" field.
func RationaleNotIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldRationale, vs...))
}

// RationaleGT applies the GT predicate on the "rationale" field.
func RationaleGT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldRationale, v))
}

// RationaleGTE applies the GTE predicate on the "rationale" field.
func RationaleGTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldRationale, v))
}

// RationaleLT applies the LT predicate on the "rationale" field.
func RationaleLT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldRationale, v))
}

// RationaleLTE applies the LTE predicate on the "rationale" field.
func RationaleLTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldRationale, v))
}

// RationaleContains applies the Contains predicate on the "rationale" field.
func RationaleContains(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContains(FieldRationale, v))
}

// RationaleHasPrefix applies the HasPrefix predicate on the "rationale" field.
func RationaleHasPrefix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasPrefix(FieldRationale, v))
}

// RationaleHasSuffix applies the HasSuffix predicate on the "rationale" field.
func RationaleHasSuffix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasSuffix(FieldRationale, v))
}

// RationaleIsNil applies the IsNil predicate on the "rationale" field.
func RationaleIsNil() predicate.Vote {
	return predicate.Vote(sql.FieldIsNull(FieldRationale))
}

// RationaleNotNil applies the NotNil predicate on the "rationale" field.
func RationaleNotNil() predicate.Vote {
	return predicate.Vote(sql.FieldNotNull(FieldRationale))
}

// RationaleEqualFold applies the EqualFold predicate on the "rationale" field.
func RationaleEqualFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEqualFold(FieldRationale, v))
}

// RationaleContainsFold applies the ContainsFold predicate on the "rationale" field.
func RationaleContainsFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContainsFold(FieldRationale, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.Vote {
	return predicate.Vote(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.Vote {
	return predicate.Vote(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Vote) predicate.Vote {
	return predicate.Vote(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Vote) predicate.Vote {
	return predicate.Vote(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Vote) predicate.Vote {
	return predicate.Vote(sql.NotPredicates(p))
}
