// Code generated by ent, DO NOT EDIT.

package auditevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldID, id))
}

// TenantKey applies equality check predicate on the "tenant_key" field. It's identical to TenantKeyEQ.
func TenantKey(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldTenantKey, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldActorID, v))
}

// AuthMode applies equality check predicate on the "auth_mode" field. It's identical to AuthModeEQ.
func AuthMode(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldAuthMode, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldAction, v))
}

// TargetKind applies equality check predicate on the "target_kind" field. It's identical to TargetKindEQ.
func TargetKind(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldTargetKind, v))
}

// TargetID applies equality check predicate on the "target_id" field. It's identical to TargetIDEQ.
func TargetID(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldTargetID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantKeyEQ applies the EQ predicate on the "tenant_key" field.
func TenantKeyEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldTenantKey, v))
}

// TenantKeyNEQ applies the NEQ predicate on the "tenant_key" field.
func TenantKeyNEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldTenantKey, v))
}

// TenantKeyIn applies the In predicate on the "tenant_key" field.
func TenantKeyIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldTenantKey, vs...))
}

// TenantKeyNotIn applies the NotIn predicate on the "tenant_key" field.
func TenantKeyNotIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldTenantKey, vs...))
}

// TenantKeyGT applies the GT predicate on the "tenant_key" field.
func TenantKeyGT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldTenantKey, v))
}

// TenantKeyGTE applies the GTE predicate on the "tenant_key" field.
func TenantKeyGTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldTenantKey, v))
}

// TenantKeyLT applies the LT predicate on the "tenant_key" field.
func TenantKeyLT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldTenantKey, v))
}

// TenantKeyLTE applies the LTE predicate on the "tenant_key" field.
func TenantKeyLTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldTenantKey, v))
}

// TenantKeyContains applies the Contains predicate on the "tenant_key" field.
func TenantKeyContains(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContains(FieldTenantKey, v))
}

// TenantKeyHasPrefix applies the HasPrefix predicate on the "tenant_key" field.
func TenantKeyHasPrefix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasPrefix(FieldTenantKey, v))
}

// TenantKeyHasSuffix applies the HasSuffix predicate on the "tenant_key" field.
func TenantKeyHasSuffix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasSuffix(FieldTenantKey, v))
}

// TenantKeyEqualFold applies the EqualFold predicate on the "tenant_key" field.
func TenantKeyEqualFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEqualFold(FieldTenantKey, v))
}

// TenantKeyContainsFold applies the ContainsFold predicate on the "tenant_key" field.
func TenantKeyContainsFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContainsFold(FieldTenantKey, v))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v uuid.UUID) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldActorID, v))
}

// ActorIDIsNil applies the IsNil predicate on the "actor_id" field.
func ActorIDIsNil() predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIsNull(FieldActorID))
}

// ActorIDNotNil applies the NotNil predicate on the "actor_id" field.
func ActorIDNotNil() predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotNull(FieldActorID))
}

// AuthModeEQ applies the EQ predicate on the "auth_mode" field.
func AuthModeEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldAuthMode, v))
}

// AuthModeNEQ applies the NEQ predicate on the "auth_mode" field.
func AuthModeNEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldAuthMode, v))
}

// AuthModeIn applies the In predicate on the "auth_mode" field.
func AuthModeIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldAuthMode, vs...))
}

// AuthModeNotIn applies the NotIn predicate on the "auth_mode" field.
func AuthModeNotIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldAuthMode, vs...))
}

// AuthModeGT applies the GT predicate on the "auth_mode" field.
func AuthModeGT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldAuthMode, v))
}

// AuthModeGTE applies the GTE predicate on the "auth_mode" field.
func AuthModeGTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldAuthMode, v))
}

// AuthModeLT applies the LT predicate on the "auth_mode" field.
func AuthModeLT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldAuthMode, v))
}

// AuthModeLTE applies the LTE predicate on the "auth_mode" field.
func AuthModeLTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldAuthMode, v))
}

// AuthModeContains applies the Contains predicate on the "auth_mode" field.
func AuthModeContains(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContains(FieldAuthMode, v))
}

// AuthModeHasPrefix applies the HasPrefix predicate on the "auth_mode" field.
func AuthModeHasPrefix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasPrefix(FieldAuthMode, v))
}

// AuthModeHasSuffix applies the HasSuffix predicate on the "auth_mode" field.
func AuthModeHasSuffix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasSuffix(FieldAuthMode, v))
}

// AuthModeEqualFold applies the EqualFold predicate on the "auth_mode" field.
func AuthModeEqualFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEqualFold(FieldAuthMode, v))
}

// AuthModeContainsFold applies the ContainsFold predicate on the "auth_mode" field.
func AuthModeContainsFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContainsFold(FieldAuthMode, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContainsFold(FieldAction, v))
}

// TargetKindEQ applies the EQ predicate on the "target_kind" field.
func TargetKindEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldTargetKind, v))
}

// TargetKindNEQ applies the NEQ predicate on the "target_kind" field.
func TargetKindNEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldTargetKind, v))
}

// TargetKindIn applies the In predicate on the "target_kind" field.
func TargetKindIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldTargetKind, vs...))
}

// TargetKindNotIn applies the NotIn predicate on the "target_kind" field.
func TargetKindNotIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldTargetKind, vs...))
}

// TargetKindGT applies the GT predicate on the "target_kind" field.
func TargetKindGT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldTargetKind, v))
}

// TargetKindGTE applies the GTE predicate on the "target_kind" field.
func TargetKindGTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldTargetKind, v))
}

// TargetKindLT applies the LT predicate on the "target_kind" field.
func TargetKindLT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldTargetKind, v))
}

// TargetKindLTE applies the LTE predicate on the "target_kind" field.
func TargetKindLTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldTargetKind, v))
}

// TargetKindContains applies the Contains predicate on the "target_kind" field.
func TargetKindContains(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContains(FieldTargetKind, v))
}

// TargetKindHasPrefix applies the HasPrefix predicate on the "target_kind" field.
func TargetKindHasPrefix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasPrefix(FieldTargetKind, v))
}

// TargetKindHasSuffix applies the HasSuffix predicate on the "target_kind" field.
func TargetKindHasSuffix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasSuffix(FieldTargetKind, v))
}

// TargetKindIsNil applies the IsNil predicate on the "target_kind" field.
func TargetKindIsNil() predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIsNull(FieldTargetKind))
}

// TargetKindNotNil applies the NotNil predicate on the "target_kind" field.
func TargetKindNotNil() predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotNull(FieldTargetKind))
}

// TargetKindEqualFold applies the EqualFold predicate on the "target_kind" field.
func TargetKindEqualFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEqualFold(FieldTargetKind, v))
}

// TargetKindContainsFold applies the ContainsFold predicate on the "target_kind" field.
func TargetKindContainsFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContainsFold(FieldTargetKind, v))
}

// TargetIDEQ applies the EQ predicate on the "target_id" field.
func TargetIDEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldTargetID, v))
}

// TargetIDNEQ applies the NEQ predicate on the "target_id" field.
func TargetIDNEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldTargetID, v))
}

// TargetIDIn applies the In predicate on the "target_id" field.
func TargetIDIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldTargetID, vs...))
}

// TargetIDNotIn applies the NotIn predicate on the "target_id" field.
func TargetIDNotIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldTargetID, vs...))
}

// TargetIDGT applies the GT predicate on the "target_id" field.
func TargetIDGT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldTargetID, v))
}

// TargetIDGTE applies the GTE predicate on the "target_id" field.
func TargetIDGTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldTargetID, v))
}

// TargetIDLT applies the LT predicate on the "target_id" field.
func TargetIDLT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldTargetID, v))
}

// TargetIDLTE applies the LTE predicate on the "target_id" field.
func TargetIDLTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldTargetID, v))
}

// TargetIDContains applies the Contains predicate on the "target_id" field.
func TargetIDContains(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContains(FieldTargetID, v))
}

// TargetIDHasPrefix applies the HasPrefix predicate on the "target_id" field.
func TargetIDHasPrefix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasPrefix(FieldTargetID, v))
}

// TargetIDHasSuffix applies the HasSuffix predicate on the "target_id" field.
func TargetIDHasSuffix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasSuffix(FieldTargetID, v))
}

// TargetIDIsNil applies the IsNil predicate on the "target_id" field.
func TargetIDIsNil() predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIsNull(FieldTargetID))
}

// TargetIDNotNil applies the NotNil predicate on the "target_id" field.
func TargetIDNotNil() predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotNull(FieldTargetID))
}

// TargetIDEqualFold applies the EqualFold predicate on the "target_id" field.
func TargetIDEqualFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEqualFold(FieldTargetID, v))
}

// TargetIDContainsFold applies the ContainsFold predicate on the "target_id" field.
func TargetIDContainsFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContainsFold(FieldTargetID, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditEvent) predicate.AuditEvent {
	return predicate.AuditEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditEvent) predicate.AuditEvent {
	return predicate.AuditEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditEvent) predicate.AuditEvent {
	return predicate.AuditEvent(sql.NotPredicates(p))
}
