// Code generated by ent, DO NOT EDIT.

package actor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldID, id))
}

// TenantKey applies equality check predicate on the "tenant_key" field. It's identical to TenantKeyEQ.
func TenantKey(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldTenantKey, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldKind, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldName, v))
}

// ExternalID applies equality check predicate on the "external_id" field. It's identical to ExternalIDEQ.
func ExternalID(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldExternalID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantKeyEQ applies the EQ predicate on the "tenant_key" field.
func TenantKeyEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldTenantKey, v))
}

// TenantKeyNEQ applies the NEQ predicate on the "tenant_key" field.
func TenantKeyNEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldTenantKey, v))
}

// TenantKeyIn applies the In predicate on the "tenant_key" field.
func TenantKeyIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldTenantKey, vs...))
}

// TenantKeyNotIn applies the NotIn predicate on the "tenant_key" field.
func TenantKeyNotIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldTenantKey, vs...))
}

// TenantKeyGT applies the GT predicate on the "tenant_key" field.
func TenantKeyGT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldTenantKey, v))
}

// TenantKeyGTE applies the GTE predicate on the "tenant_key" field.
func TenantKeyGTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldTenantKey, v))
}

// TenantKeyLT applies the LT predicate on the "tenant_key" field.
func TenantKeyLT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldTenantKey, v))
}

// TenantKeyLTE applies the LTE predicate on the "tenant_key" field.
func TenantKeyLTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldTenantKey, v))
}

// TenantKeyContains applies the Contains predicate on the "tenant_key" field.
func TenantKeyContains(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContains(FieldTenantKey, v))
}

// TenantKeyHasPrefix applies the HasPrefix predicate on the "tenant_key" field.
func TenantKeyHasPrefix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasPrefix(FieldTenantKey, v))
}

// TenantKeyHasSuffix applies the HasSuffix predicate on the "tenant_key" field.
func TenantKeyHasSuffix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasSuffix(FieldTenantKey, v))
}

// TenantKeyEqualFold applies the EqualFold predicate on the "tenant_key" field.
func TenantKeyEqualFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEqualFold(FieldTenantKey, v))
}

// TenantKeyContainsFold applies the ContainsFold predicate on the "tenant_key" field.
func TenantKeyContainsFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContainsFold(FieldTenantKey, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContainsFold(FieldKind, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContainsFold(FieldName, v))
}

// ExternalIDEQ applies the EQ predicate on the "external_id" field.
func ExternalIDEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldExternalID, v))
}

// ExternalIDNEQ applies the NEQ predicate on the "external_id" field.
func ExternalIDNEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldExternalID, v))
}

// ExternalIDIn applies the In predicate on the "external_id" field.
func ExternalIDIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldExternalID, vs...))
}

// ExternalIDNotIn applies the NotIn predicate on the "external_id" field.
func ExternalIDNotIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldExternalID, vs...))
}

// ExternalIDGT applies the GT predicate on the "external_id" field.
func ExternalIDGT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldExternalID, v))
}

// ExternalIDGTE applies the GTE predicate on the "external_id" field.
func ExternalIDGTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldExternalID, v))
}

// ExternalIDLT applies the LT predicate on the "external_id" field.
func ExternalIDLT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldExternalID, v))
}

// ExternalIDLTE applies the LTE predicate on the "external_id" field.
func ExternalIDLTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldExternalID, v))
}

// ExternalIDContains applies the Contains predicate on the "external_id" field.
func ExternalIDContains(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContains(FieldExternalID, v))
}

// ExternalIDHasPrefix applies the HasPrefix predicate on the "external_id" field.
func ExternalIDHasPrefix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasPrefix(FieldExternalID, v))
}

// ExternalIDHasSuffix applies the HasSuffix predicate on the "external_id" field.
func ExternalIDHasSuffix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasSuffix(FieldExternalID, v))
}

// ExternalIDIsNil applies the IsNil predicate on the "external_id" field.
func ExternalIDIsNil() predicate.Actor {
	return predicate.Actor(sql.FieldIsNull(FieldExternalID))
}

// ExternalIDNotNil applies the NotNil predicate on the "external_id" field.
func ExternalIDNotNil() predicate.Actor {
	return predicate.Actor(sql.FieldNotNull(FieldExternalID))
}

// ExternalIDEqualFold applies the EqualFold predicate on the "external_id" field.
func ExternalIDEqualFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEqualFold(FieldExternalID, v))
}

// ExternalIDContainsFold applies the ContainsFold predicate on the "external_id" field.
func ExternalIDContainsFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContainsFold(FieldExternalID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Actor) predicate.Actor {
	return predicate.Actor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Actor) predicate.Actor {
	return predicate.Actor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Actor) predicate.Actor {
	return predicate.Actor(sql.NotPredicates(p))
}
