// Code generated by ent, DO NOT EDIT.

package insight

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldID, id))
}

// TenantKey applies equality check predicate on the "tenant_key" field. It's identical to TenantKeyEQ.
func TenantKey(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldTenantKey, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldTitle, v))
}

// Problem applies equality check predicate on the "problem" field. It's identical to ProblemEQ.
func Problem(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldProblem, v))
}

// Answer applies equality check predicate on the "answer" field. It's identical to AnswerEQ.
func Answer(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldAnswer, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldDetail, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldAction, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldKind, v))
}

// CreatedByActorID applies equality check predicate on the "created_by_actor_id" field. It's identical to CreatedByActorIDEQ.
func CreatedByActorID(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldCreatedByActorID, v))
}

// SourceRunID applies equality check predicate on the "source_run_id" field. It's identical to SourceRunIDEQ.
func SourceRunID(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldSourceRunID, v))
}

// ReviewState applies equality check predicate on the "review_state" field. It's identical to ReviewStateEQ.
func ReviewState(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldReviewState, v))
}

// LifecycleState applies equality check predicate on the "lifecycle_state" field. It's identical to LifecycleStateEQ.
func LifecycleState(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldLifecycleState, v))
}

// SupersededByID applies equality check predicate on the "superseded_by_id" field. It's identical to SupersededByIDEQ.
func SupersededByID(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldSupersededByID, v))
}

// LastConfirmedAt applies equality check predicate on the "last_confirmed_at" field. It's identical to LastConfirmedAtEQ.
func LastConfirmedAt(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldLastConfirmedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantKeyEQ applies the EQ predicate on the "tenant_key" field.
func TenantKeyEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldTenantKey, v))
}

// TenantKeyNEQ applies the NEQ predicate on the "tenant_key" field.
func TenantKeyNEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldTenantKey, v))
}

// TenantKeyIn applies the In predicate on the "tenant_key" field.
func TenantKeyIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldTenantKey, vs...))
}

// TenantKeyNotIn applies the NotIn predicate on the "tenant_key" field.
func TenantKeyNotIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldTenantKey, vs...))
}

// TenantKeyGT applies the GT predicate on the "tenant_key" field.
func TenantKeyGT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldTenantKey, v))
}

// TenantKeyGTE applies the GTE predicate on the "tenant_key" field.
func TenantKeyGTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldTenantKey, v))
}

// TenantKeyLT applies the LT predicate on the "tenant_key" field.
func TenantKeyLT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldTenantKey, v))
}

// TenantKeyLTE applies the LTE predicate on the "tenant_key" field.
func TenantKeyLTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldTenantKey, v))
}

// TenantKeyContains applies the Contains predicate on the "tenant_key" field.
func TenantKeyContains(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContains(FieldTenantKey, v))
}

// TenantKeyHasPrefix applies the HasPrefix predicate on the "tenant_key" field.
func TenantKeyHasPrefix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasPrefix(FieldTenantKey, v))
}

// TenantKeyHasSuffix applies the HasSuffix predicate on the "tenant_key" field.
func TenantKeyHasSuffix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasSuffix(FieldTenantKey, v))
}

// TenantKeyEqualFold applies the EqualFold predicate on the "tenant_key" field.
func TenantKeyEqualFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEqualFold(FieldTenantKey, v))
}

// TenantKeyContainsFold applies the ContainsFold predicate on the "tenant_key" field.
func TenantKeyContainsFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContainsFold(FieldTenantKey, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContainsFold(FieldTitle, v))
}

// ProblemEQ applies the EQ predicate on the "problem" field.
func ProblemEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldProblem, v))
}

// ProblemNEQ applies the NEQ predicate on the "problem" field.
func ProblemNEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldProblem, v))
}

// ProblemIn applies the In predicate on the "problem" field.
func ProblemIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldProblem, vs...))
}

// ProblemNotIn applies the NotIn predicate on the "problem" field.
func ProblemNotIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldProblem, vs...))
}

// ProblemGT applies the GT predicate on the "problem" field.
func ProblemGT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldProblem, v))
}

// ProblemGTE applies the GTE predicate on the "problem" field.
func ProblemGTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldProblem, v))
}

// ProblemLT applies the LT predicate on the "problem" field.
func ProblemLT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldProblem, v))
}

// ProblemLTE applies the LTE predicate on the "problem" field.
func ProblemLTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldProblem, v))
}

// ProblemContains applies the Contains predicate on the "problem" field.
func ProblemContains(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContains(FieldProblem, v))
}

// ProblemHasPrefix applies the HasPrefix predicate on the "problem" field.
func ProblemHasPrefix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasPrefix(FieldProblem, v))
}

// ProblemHasSuffix applies the HasSuffix predicate on the "problem" field.
func ProblemHasSuffix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasSuffix(FieldProblem, v))
}

// ProblemIsNil applies the IsNil predicate on the "problem" field.
func ProblemIsNil() predicate.Insight {
	return predicate.Insight(sql.FieldIsNull(FieldProblem))
}

// ProblemNotNil applies the NotNil predicate on the "problem" field.
func ProblemNotNil() predicate.Insight {
	return predicate.Insight(sql.FieldNotNull(FieldProblem))
}

// ProblemEqualFold applies the EqualFold predicate on the "problem" field.
func ProblemEqualFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEqualFold(FieldProblem, v))
}

// ProblemContainsFold applies the ContainsFold predicate on the "problem" field.
func ProblemContainsFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContainsFold(FieldProblem, v))
}

// AnswerEQ applies the EQ predicate on the "answer" field.
func AnswerEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldAnswer, v))
}

// AnswerNEQ applies the NEQ predicate on the "answer" field.
func AnswerNEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldAnswer, v))
}

// AnswerIn applies the In predicate on the "answer" field.
func AnswerIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldAnswer, vs...))
}

// AnswerNotIn applies the NotIn predicate on the "answer" field.
func AnswerNotIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldAnswer, vs...))
}

// AnswerGT applies the GT predicate on the "answer" field.
func AnswerGT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldAnswer, v))
}

// AnswerGTE applies the GTE predicate on the "answer" field.
func AnswerGTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldAnswer, v))
}

// AnswerLT applies the LT predicate on the "answer" field.
func AnswerLT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldAnswer, v))
}

// AnswerLTE applies the LTE predicate on the "answer" field.
func AnswerLTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldAnswer, v))
}

// AnswerContains applies the Contains predicate on the "answer" field.
func AnswerContains(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContains(FieldAnswer, v))
}

// AnswerHasPrefix applies the HasPrefix predicate on the "answer" field.
func AnswerHasPrefix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasPrefix(FieldAnswer, v))
}

// AnswerHasSuffix applies the HasSuffix predicate on the "answer" field.
func AnswerHasSuffix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasSuffix(FieldAnswer, v))
}

// AnswerEqualFold applies the EqualFold predicate on the "answer" field.
func AnswerEqualFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEqualFold(FieldAnswer, v))
}

// AnswerContainsFold applies the ContainsFold predicate on the "answer" field.
func AnswerContainsFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContainsFold(FieldAnswer, v))
}

// ExampleIsNil applies the IsNil predicate on the "example" field.
func ExampleIsNil() predicate.Insight {
	return predicate.Insight(sql.FieldIsNull(FieldExample))
}

// ExampleNotNil applies the NotNil predicate on the "example" field.
func ExampleNotNil() predicate.Insight {
	return predicate.Insight(sql.FieldNotNull(FieldExample))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailIsNil applies the IsNil predicate on the "detail" field.
func DetailIsNil() predicate.Insight {
	return predicate.Insight(sql.FieldIsNull(FieldDetail))
}

// DetailNotNil applies the NotNil predicate on the "detail" field.
func DetailNotNil() predicate.Insight {
	return predicate.Insight(sql.FieldNotNull(FieldDetail))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContainsFold(FieldDetail, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasSuffix(FieldAction, v))
}

// ActionIsNil applies the IsNil predicate on the "action" field.
func ActionIsNil() predicate.Insight {
	return predicate.Insight(sql.FieldIsNull(FieldAction))
}

// ActionNotNil applies the NotNil predicate on the "action" field.
func ActionNotNil() predicate.Insight {
	return predicate.Insight(sql.FieldNotNull(FieldAction))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContainsFold(FieldAction, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContainsFold(FieldKind, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Insight {
	return predicate.Insight(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Insight {
	return predicate.Insight(sql.FieldNotNull(FieldTags))
}

// ContextIsNil applies the IsNil predicate on the "context" field.
func ContextIsNil() predicate.Insight {
	return predicate.Insight(sql.FieldIsNull(FieldContext))
}

// ContextNotNil applies the NotNil predicate on the "context" field.
func ContextNotNil() predicate.Insight {
	return predicate.Insight(sql.FieldNotNull(FieldContext))
}

// LinksIsNil applies the IsNil predicate on the "links" field.
func LinksIsNil() predicate.Insight {
	return predicate.Insight(sql.FieldIsNull(FieldLinks))
}

// LinksNotNil applies the NotNil predicate on the "links" field.
func LinksNotNil() predicate.Insight {
	return predicate.Insight(sql.FieldNotNull(FieldLinks))
}

// CreatedByActorIDEQ applies the EQ predicate on the "created_by_actor_id" field.
func CreatedByActorIDEQ(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldCreatedByActorID, v))
}

// CreatedByActorIDNEQ applies the NEQ predicate on the "created_by_actor_id" field.
func CreatedByActorIDNEQ(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldCreatedByActorID, v))
}

// CreatedByActorIDIn applies the In predicate on the "created_by_actor_id" field.
func CreatedByActorIDIn(vs ...uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldCreatedByActorID, vs...))
}

// CreatedByActorIDNotIn applies the NotIn predicate on the "created_by_actor_id" field.
func CreatedByActorIDNotIn(vs ...uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldCreatedByActorID, vs...))
}

// CreatedByActorIDGT applies the GT predicate on the "created_by_actor_id" field.
func CreatedByActorIDGT(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldCreatedByActorID, v))
}

// CreatedByActorIDGTE applies the GTE predicate on the "created_by_actor_id" field.
func CreatedByActorIDGTE(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldCreatedByActorID, v))
}

// CreatedByActorIDLT applies the LT predicate on the "created_by_actor_id" field.
func CreatedByActorIDLT(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldCreatedByActorID, v))
}

// CreatedByActorIDLTE applies the LTE predicate on the "created_by_actor_id" field.
func CreatedByActorIDLTE(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldCreatedByActorID, v))
}

// CreatedByActorIDIsNil applies the IsNil predicate on the "created_by_actor_id" field.
func CreatedByActorIDIsNil() predicate.Insight {
	return predicate.Insight(sql.FieldIsNull(FieldCreatedByActorID))
}

// CreatedByActorIDNotNil applies the NotNil predicate on the "created_by_actor_id" field.
func CreatedByActorIDNotNil() predicate.Insight {
	return predicate.Insight(sql.FieldNotNull(FieldCreatedByActorID))
}

// SourceRunIDEQ applies the EQ predicate on the "source_run_id" field.
func SourceRunIDEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldSourceRunID, v))
}

// SourceRunIDNEQ applies the NEQ predicate on the "source_run_id" field.
func SourceRunIDNEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldSourceRunID, v))
}

// SourceRunIDIn applies the In predicate on the "source_run_id" field.
func SourceRunIDIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldSourceRunID, vs...))
}

// SourceRunIDNotIn applies the NotIn predicate on the "source_run_id" field.
func SourceRunIDNotIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldSourceRunID, vs...))
}

// SourceRunIDGT applies the GT predicate on the "source_run_id" field.
func SourceRunIDGT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldSourceRunID, v))
}

// SourceRunIDGTE applies the GTE predicate on the "source_run_id" field.
func SourceRunIDGTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldSourceRunID, v))
}

// SourceRunIDLT applies the LT predicate on the "source_run_id" field.
func SourceRunIDLT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldSourceRunID, v))
}

// SourceRunIDLTE applies the LTE predicate on the "source_run_id" field.
func SourceRunIDLTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldSourceRunID, v))
}

// SourceRunIDContains applies the Contains predicate on the "source_run_id" field.
func SourceRunIDContains(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContains(FieldSourceRunID, v))
}

// SourceRunIDHasPrefix applies the HasPrefix predicate on the "source_run_id" field.
func SourceRunIDHasPrefix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasPrefix(FieldSourceRunID, v))
}

// SourceRunIDHasSuffix applies the HasSuffix predicate on the "source_run_id" field.
func SourceRunIDHasSuffix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasSuffix(FieldSourceRunID, v))
}

// SourceRunIDIsNil applies the IsNil predicate on the "source_run_id" field.
func SourceRunIDIsNil() predicate.Insight {
	return predicate.Insight(sql.FieldIsNull(FieldSourceRunID))
}

// SourceRunIDNotNil applies the NotNil predicate on the "source_run_id" field.
func SourceRunIDNotNil() predicate.Insight {
	return predicate.Insight(sql.FieldNotNull(FieldSourceRunID))
}

// SourceRunIDEqualFold applies the EqualFold predicate on the "source_run_id" field.
func SourceRunIDEqualFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEqualFold(FieldSourceRunID, v))
}

// SourceRunIDContainsFold applies the ContainsFold predicate on the "source_run_id" field.
func SourceRunIDContainsFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContainsFold(FieldSourceRunID, v))
}

// ReviewStateEQ applies the EQ predicate on the "review_state" field.
func ReviewStateEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldReviewState, v))
}

// ReviewStateNEQ applies the NEQ predicate on the "review_state" field.
func ReviewStateNEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldReviewState, v))
}

// ReviewStateIn applies the In predicate on the "review_state" field.
func ReviewStateIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldReviewState, vs...))
}

// ReviewStateNotIn applies the NotIn predicate on the "review_state" field.
func ReviewStateNotIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldReviewState, vs...))
}

// ReviewStateGT applies the GT predicate on the "review_state" field.
func ReviewStateGT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldReviewState, v))
}

// ReviewStateGTE applies the GTE predicate on the "review_state" field.
func ReviewStateGTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldReviewState, v))
}

// ReviewStateLT applies the LT predicate on the "review_state" field.
func ReviewStateLT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldReviewState, v))
}

// ReviewStateLTE applies the LTE predicate on the "review_state" field.
func ReviewStateLTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldReviewState, v))
}

// ReviewStateContains applies the Contains predicate on the "review_state" field.
func ReviewStateContains(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContains(FieldReviewState, v))
}

// ReviewStateHasPrefix applies the HasPrefix predicate on the "review_state" field.
func ReviewStateHasPrefix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasPrefix(FieldReviewState, v))
}

// ReviewStateHasSuffix applies the HasSuffix predicate on the "review_state" field.
func ReviewStateHasSuffix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasSuffix(FieldReviewState, v))
}

// ReviewStateEqualFold applies the EqualFold predicate on the "review_state" field.
func ReviewStateEqualFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEqualFold(FieldReviewState, v))
}

// ReviewStateContainsFold applies the ContainsFold predicate on the "review_state" field.
func ReviewStateContainsFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContainsFold(FieldReviewState, v))
}

// LifecycleStateEQ applies the EQ predicate on the "lifecycle_state" field.
func LifecycleStateEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldLifecycleState, v))
}

// LifecycleStateNEQ applies the NEQ predicate on the "lifecycle_state" field.
func LifecycleStateNEQ(v string) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldLifecycleState, v))
}

// LifecycleStateIn applies the In predicate on the "lifecycle_state" field.
func LifecycleStateIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldLifecycleState, vs...))
}

// LifecycleStateNotIn applies the NotIn predicate on the "lifecycle_state" field.
func LifecycleStateNotIn(vs ...string) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldLifecycleState, vs...))
}

// LifecycleStateGT applies the GT predicate on the "lifecycle_state" field.
func LifecycleStateGT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldLifecycleState, v))
}

// LifecycleStateGTE applies the GTE predicate on the "lifecycle_state" field.
func LifecycleStateGTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldLifecycleState, v))
}

// LifecycleStateLT applies the LT predicate on the "lifecycle_state" field.
func LifecycleStateLT(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldLifecycleState, v))
}

// LifecycleStateLTE applies the LTE predicate on the "lifecycle_state" field.
func LifecycleStateLTE(v string) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldLifecycleState, v))
}

// LifecycleStateContains applies the Contains predicate on the "lifecycle_state" field.
func LifecycleStateContains(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContains(FieldLifecycleState, v))
}

// LifecycleStateHasPrefix applies the HasPrefix predicate on the "lifecycle_state" field.
func LifecycleStateHasPrefix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasPrefix(FieldLifecycleState, v))
}

// LifecycleStateHasSuffix applies the HasSuffix predicate on the "lifecycle_state" field.
func LifecycleStateHasSuffix(v string) predicate.Insight {
	return predicate.Insight(sql.FieldHasSuffix(FieldLifecycleState, v))
}

// LifecycleStateEqualFold applies the EqualFold predicate on the "lifecycle_state" field.
func LifecycleStateEqualFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldEqualFold(FieldLifecycleState, v))
}

// LifecycleStateContainsFold applies the ContainsFold predicate on the "lifecycle_state" field.
func LifecycleStateContainsFold(v string) predicate.Insight {
	return predicate.Insight(sql.FieldContainsFold(FieldLifecycleState, v))
}

// SupersededByIDEQ applies the EQ predicate on the "superseded_by_id" field.
func SupersededByIDEQ(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldSupersededByID, v))
}

// SupersededByIDNEQ applies the NEQ predicate on the "superseded_by_id" field.
func SupersededByIDNEQ(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldSupersededByID, v))
}

// SupersededByIDIn applies the In predicate on the "superseded_by_id" field.
func SupersededByIDIn(vs ...uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldSupersededByID, vs...))
}

// SupersededByIDNotIn applies the NotIn predicate on the "superseded_by_id" field.
func SupersededByIDNotIn(vs ...uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldSupersededByID, vs...))
}

// SupersededByIDGT applies the GT predicate on the "superseded_by_id" field.
func SupersededByIDGT(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldSupersededByID, v))
}

// SupersededByIDGTE applies the GTE predicate on the "superseded_by_id" field.
func SupersededByIDGTE(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldSupersededByID, v))
}

// SupersededByIDLT applies the LT predicate on the "superseded_by_id" field.
func SupersededByIDLT(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldSupersededByID, v))
}

// SupersededByIDLTE applies the LTE predicate on the "superseded_by_id" field.
func SupersededByIDLTE(v uuid.UUID) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldSupersededByID, v))
}

// SupersededByIDIsNil applies the IsNil predicate on the "superseded_by_id" field.
func SupersededByIDIsNil() predicate.Insight {
	return predicate.Insight(sql.FieldIsNull(FieldSupersededByID))
}

// SupersededByIDNotNil applies the NotNil predicate on the "superseded_by_id" field.
func SupersededByIDNotNil() predicate.Insight {
	return predicate.Insight(sql.FieldNotNull(FieldSupersededByID))
}

// LastConfirmedAtEQ applies the EQ predicate on the "last_confirmed_at" field.
func LastConfirmedAtEQ(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldLastConfirmedAt, v))
}

// LastConfirmedAtNEQ applies the NEQ predicate on the "last_confirmed_at" field.
func LastConfirmedAtNEQ(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldLastConfirmedAt, v))
}

// LastConfirmedAtIn applies the In predicate on the "last_confirmed_at" field.
func LastConfirmedAtIn(vs ...time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldLastConfirmedAt, vs...))
}

// LastConfirmedAtNotIn applies the NotIn predicate on the "last_confirmed_at" field.
func LastConfirmedAtNotIn(vs ...time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldLastConfirmedAt, vs...))
}

// LastConfirmedAtGT applies the GT predicate on the "last_confirmed_at" field.
func LastConfirmedAtGT(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldLastConfirmedAt, v))
}

// LastConfirmedAtGTE applies the GTE predicate on the "last_confirmed_at" field.
func LastConfirmedAtGTE(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldLastConfirmedAt, v))
}

// LastConfirmedAtLT applies the LT predicate on the "last_confirmed_at" field.
func LastConfirmedAtLT(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldLastConfirmedAt, v))
}

// LastConfirmedAtLTE applies the LTE predicate on the "last_confirmed_at" field.
func LastConfirmedAtLTE(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldLastConfirmedAt, v))
}

// LastConfirmedAtIsNil applies the IsNil predicate on the "last_confirmed_at" field.
func LastConfirmedAtIsNil() predicate.Insight {
	return predicate.Insight(sql.FieldIsNull(FieldLastConfirmedAt))
}

// LastConfirmedAtNotNil applies the NotNil predicate on the "last_confirmed_at" field.
func LastConfirmedAtNotNil() predicate.Insight {
	return predicate.Insight(sql.FieldNotNull(FieldLastConfirmedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Insight {
	return predicate.Insight(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Insight) predicate.Insight {
	return predicate.Insight(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Insight) predicate.Insight {
	return predicate.Insight(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Insight) predicate.Insight {
	return predicate.Insight(sql.NotPredicates(p))
}
