// Code generated by ent, DO NOT EDIT.

package problemfingerprint

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the problemfingerprint type in the database.
	Label = "problem_fingerprint"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantKey holds the string denoting the tenant_key field in the database.
	FieldTenantKey = "tenant_key"
	// FieldKnowledgeUnitID holds the string denoting the knowledge_unit_id field in the database.
	FieldKnowledgeUnitID = "knowledge_unit_id"
	// FieldErrorHash holds the string denoting the error_hash field in the database.
	FieldErrorHash = "error_hash"
	// FieldCommand holds the string denoting the command field in the database.
	FieldCommand = "command"
	// FieldToolchain holds the string denoting the toolchain field in the database.
	FieldToolchain = "toolchain"
	// FieldService holds the string denoting the service field in the database.
	FieldService = "service"
	// FieldRepoPathPattern holds the string denoting the repo_path_pattern field in the database.
	FieldRepoPathPattern = "repo_path_pattern"
	// FieldEnvironment holds the string denoting the environment field in the database.
	FieldEnvironment = "environment"
	// FieldDependencyVersions holds the string denoting the dependency_versions field in the database.
	FieldDependencyVersions = "dependency_versions"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the problemfingerprint in the database.
	Table = "problem_fingerprints"
)

// Columns holds all SQL columns for problemfingerprint fields.
var Columns = []string{
	FieldID,
	FieldTenantKey,
	FieldKnowledgeUnitID,
	FieldErrorHash,
	FieldCommand,
	FieldToolchain,
	FieldService,
	FieldRepoPathPattern,
	FieldEnvironment,
	FieldDependencyVersions,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTenantKey holds the default value on creation for the "tenant_key" field.
	DefaultTenantKey string
	// TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	TenantKeyValidator func(string) error
	// ErrorHashValidator is a validator for the "error_hash" field. It is called by the builders before save.
	ErrorHashValidator func(string) error
	// CommandValidator is a validator for the "command" field. It is called by the builders before save.
	CommandValidator func(string) error
	// ToolchainValidator is a validator for the "toolchain" field. It is called by the builders before save.
	ToolchainValidator func(string) error
	// ServiceValidator is a validator for the "service" field. It is called by the builders before save.
	ServiceValidator func(string) error
	// RepoPathPatternValidator is a validator for the "repo_path_pattern" field. It is called by the builders before save.
	RepoPathPatternValidator func(string) error
	// EnvironmentValidator is a validator for the "environment" field. It is called by the builders before save.
	EnvironmentValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ProblemFingerprint queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantKey orders the results by the tenant_key field.
func ByTenantKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantKey, opts...).ToFunc()
}

// ByKnowledgeUnitID orders the results by the knowledge_unit_id field.
func ByKnowledgeUnitID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKnowledgeUnitID, opts...).ToFunc()
}

// ByErrorHash orders the results by the error_hash field.
func ByErrorHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorHash, opts...).ToFunc()
}

// ByCommand orders the results by the command field.
func ByCommand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommand, opts...).ToFunc()
}

// ByToolchain orders the results by the toolchain field.
func ByToolchain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolchain, opts...).ToFunc()
}

// ByService orders the results by the service field.
func ByService(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldService, opts...).ToFunc()
}

// ByRepoPathPattern orders the results by the repo_path_pattern field.
func ByRepoPathPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoPathPattern, opts...).ToFunc()
}

// ByEnvironment orders the results by the environment field.
func ByEnvironment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironment, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
