// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActorsColumns holds the columns for the "actors" table.
	ActorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_key", Type: field.TypeString, Size: 255, Default: "default"},
		{Name: "kind", Type: field.TypeString, Size: 100, Default: "agent"},
		{Name: "name", Type: field.TypeString, Size: 255, Default: "anonymous"},
		{Name: "external_id", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ActorsTable holds the schema information for the "actors" table.
	ActorsTable = &schema.Table{
		Name:       "actors",
		Columns:    ActorsColumns,
		PrimaryKey: []*schema.Column{ActorsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "actor_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{ActorsColumns[1]},
			},
			{
				Name:    "actor_tenant_key_external_id",
				Unique:  false,
				Columns: []*schema.Column{ActorsColumns[1], ActorsColumns[4]},
			},
		},
	}
	// AuditEventsColumns holds the columns for the "audit_events" table.
	AuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_key", Type: field.TypeString, Size: 255, Default: "default"},
		{Name: "actor_id", Type: field.TypeUUID, Nullable: true},
		{Name: "auth_mode", Type: field.TypeString, Size: 100, Default: "none"},
		{Name: "action", Type: field.TypeString, Size: 255},
		{Name: "target_kind", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "target_id", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditEventsTable holds the schema information for the "audit_events" table.
	AuditEventsTable = &schema.Table{
		Name:       "audit_events",
		Columns:    AuditEventsColumns,
		PrimaryKey: []*schema.Column{AuditEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditevent_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[1]},
			},
			{
				Name:    "auditevent_tenant_key_action",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[1], AuditEventsColumns[4]},
			},
			{
				Name:    "auditevent_tenant_key_target_kind_target_id",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[1], AuditEventsColumns[5], AuditEventsColumns[6]},
			},
		},
	}
	// GraphEdgesColumns holds the columns for the "graph_edges" table.
	GraphEdgesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_key", Type: field.TypeString, Size: 255, Default: "default"},
		{Name: "from_id", Type: field.TypeUUID},
		{Name: "to_id", Type: field.TypeUUID},
		{Name: "relationship", Type: field.TypeString, Size: 100},
		{Name: "rationale", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "review_state", Type: field.TypeString, Size: 100, Default: "approved"},
		{Name: "tombstoned_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GraphEdgesTable holds the schema information for the "graph_edges" table.
	GraphEdgesTable = &schema.Table{
		Name:       "graph_edges",
		Columns:    GraphEdgesColumns,
		PrimaryKey: []*schema.Column{GraphEdgesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "graphedge_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{GraphEdgesColumns[1]},
			},
			{
				Name:    "graphedge_tenant_key_from_id",
				Unique:  false,
				Columns: []*schema.Column{GraphEdgesColumns[1], GraphEdgesColumns[2]},
			},
			{
				Name:    "graphedge_tenant_key_to_id",
				Unique:  false,
				Columns: []*schema.Column{GraphEdgesColumns[1], GraphEdgesColumns[3]},
			},
			{
				Name:    "graphedge_tenant_key_from_id_to_id_relationship",
				Unique:  false,
				Columns: []*schema.Column{GraphEdgesColumns[1], GraphEdgesColumns[2], GraphEdgesColumns[3], GraphEdgesColumns[4]},
			},
		},
	}
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_key", Type: field.TypeString, Size: 255, Default: "default"},
		{Name: "kind", Type: field.TypeString, Size: 100},
		{Name: "status", Type: field.TypeString, Size: 100, Default: "pending"},
		{Name: "payload", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "last_error", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "run_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:       "jobs",
		Columns:    JobsColumns,
		PrimaryKey: []*schema.Column{JobsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "job_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{JobsColumns[1]},
			},
			{
				Name:    "job_tenant_key_status",
				Unique:  false,
				Columns: []*schema.Column{JobsColumns[1], JobsColumns[3]},
			},
			{
				Name:    "job_tenant_key_kind_status",
				Unique:  false,
				Columns: []*schema.Column{JobsColumns[1], JobsColumns[2], JobsColumns[3]},
			},
		},
	}
	// KnowledgeUnitsColumns holds the columns for the "knowledge_units" table.
	KnowledgeUnitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_key", Type: field.TypeString, Size: 255, Default: "default"},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "summary", Type: field.TypeString, Size: 1000},
		{Name: "detail", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "action", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "kind", Type: field.TypeString, Size: 100, Default: "finding"},
		{Name: "labels", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "context", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "evidence_refs", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "created_by_actor_id", Type: field.TypeUUID, Nullable: true},
		{Name: "source_run_id", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "review_state", Type: field.TypeString, Size: 100, Default: "approved"},
		{Name: "lifecycle_state", Type: field.TypeString, Size: 100, Default: "active"},
		{Name: "superseded_by_id", Type: field.TypeUUID, Nullable: true},
		{Name: "last_confirmed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// KnowledgeUnitsTable holds the schema information for the "knowledge_units" table.
	KnowledgeUnitsTable = &schema.Table{
		Name:       "knowledge_units",
		Columns:    KnowledgeUnitsColumns,
		PrimaryKey: []*schema.Column{KnowledgeUnitsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "knowledgeunit_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{KnowledgeUnitsColumns[1]},
			},
			{
				Name:    "knowledgeunit_tenant_key_review_state",
				Unique:  false,
				Columns: []*schema.Column{KnowledgeUnitsColumns[1], KnowledgeUnitsColumns[12]},
			},
			{
				Name:    "knowledgeunit_tenant_key_lifecycle_state",
				Unique:  false,
				Columns: []*schema.Column{KnowledgeUnitsColumns[1], KnowledgeUnitsColumns[13]},
			},
		},
	}
	// ProblemFingerprintsColumns holds the columns for the "problem_fingerprints" table.
	ProblemFingerprintsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_key", Type: field.TypeString, Size: 255, Default: "default"},
		{Name: "knowledge_unit_id", Type: field.TypeUUID},
		{Name: "error_hash", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "command", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "toolchain", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "service", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "repo_path_pattern", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "dependency_versions", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ProblemFingerprintsTable holds the schema information for the "problem_fingerprints" table.
	ProblemFingerprintsTable = &schema.Table{
		Name:       "problem_fingerprints",
		Columns:    ProblemFingerprintsColumns,
		PrimaryKey: []*schema.Column{ProblemFingerprintsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "problemfingerprint_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{ProblemFingerprintsColumns[1]},
			},
			{
				Name:    "problemfingerprint_tenant_key_knowledge_unit_id",
				Unique:  false,
				Columns: []*schema.Column{ProblemFingerprintsColumns[1], ProblemFingerprintsColumns[2]},
			},
			{
				Name:    "problemfingerprint_tenant_key_error_hash",
				Unique:  false,
				Columns: []*schema.Column{ProblemFingerprintsColumns[1], ProblemFingerprintsColumns[3]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_key", Type: field.TypeString, Size: 255, Default: "default"},
		{Name: "key", Type: field.TypeString, Size: 255},
		{Name: "value", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "setting_tenant_key_key",
				Unique:  true,
				Columns: []*schema.Column{SettingsColumns[1], SettingsColumns[2]},
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "key", Type: field.TypeString, Size: 255, Default: "default"},
		{Name: "name", Type: field.TypeString, Size: 255, Default: "Default"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tenant_key",
				Unique:  true,
				Columns: []*schema.Column{TenantsColumns[1]},
			},
		},
	}
	// VotesColumns holds the columns for the "votes" table.
	VotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_key", Type: field.TypeString, Size: 255, Default: "default"},
		{Name: "knowledge_unit_id", Type: field.TypeUUID},
		{Name: "actor_id", Type: field.TypeUUID, Nullable: true},
		{Name: "problem_fingerprint_id", Type: field.TypeUUID, Nullable: true},
		{Name: "outcome", Type: field.TypeString, Size: 100},
		{Name: "confidence", Type: field.TypeFloat64, Default: 0},
		{Name: "rationale", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "idempotency_key", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "created_at", Type: field.TypeTime},
	}
	// VotesTable holds the schema information for the "votes" table.
	VotesTable = &schema.Table{
		Name:       "votes",
		Columns:    VotesColumns,
		PrimaryKey: []*schema.Column{VotesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "vote_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{VotesColumns[1]},
			},
			{
				Name:    "vote_tenant_key_knowledge_unit_id",
				Unique:  false,
				Columns: []*schema.Column{VotesColumns[1], VotesColumns[2]},
			},
			{
				Name:    "vote_tenant_key_outcome",
				Unique:  false,
				Columns: []*schema.Column{VotesColumns[1], VotesColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActorsTable,
		AuditEventsTable,
		GraphEdgesTable,
		JobsTable,
		KnowledgeUnitsTable,
		ProblemFingerprintsTable,
		SettingsTable,
		TenantsTable,
		VotesTable,
	}
)

func init() {
}
