// Code generated by ent, DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loewenthal-corp/consensus/internal/postgres/actor"
	"github.com/loewenthal-corp/consensus/internal/postgres/predicate"
)

// ActorUpdate is the builder for updating Actor entities.
type ActorUpdate struct {
	config
	hooks    []Hook
	mutation *ActorMutation
}

// Where appends a list predicates to the ActorUpdate builder.
func (_u *ActorUpdate) Where(ps ...predicate.Actor) *ActorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantKey sets the "tenant_key" field.
func (_u *ActorUpdate) SetTenantKey(v string) *ActorUpdate {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *ActorUpdate) SetNillableTenantKey(v *string) *ActorUpdate {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ActorUpdate) SetKind(v string) *ActorUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ActorUpdate) SetNillableKind(v *string) *ActorUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ActorUpdate) SetName(v string) *ActorUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActorUpdate) SetNillableName(v *string) *ActorUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *ActorUpdate) SetExternalID(v string) *ActorUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *ActorUpdate) SetNillableExternalID(v *string) *ActorUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *ActorUpdate) ClearExternalID() *ActorUpdate {
	_u.mutation.ClearExternalID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ActorUpdate) SetUpdatedAt(v time.Time) *ActorUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ActorMutation object of the builder.
func (_u *ActorUpdate) Mutation() *ActorMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActorUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := actor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActorUpdate) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := actor.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "Actor.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := actor.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`postgres: validator failed for field "Actor.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := actor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`postgres: validator failed for field "Actor.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := actor.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`postgres: validator failed for field "Actor.external_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ActorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(actor.Table, actor.Columns, sqlgraph.NewFieldSpec(actor.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(actor.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(actor.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(actor.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(actor.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(actor.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(actor.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActorUpdateOne is the builder for updating a single Actor entity.
type ActorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActorMutation
}

// SetTenantKey sets the "tenant_key" field.
func (_u *ActorUpdateOne) SetTenantKey(v string) *ActorUpdateOne {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *ActorUpdateOne) SetNillableTenantKey(v *string) *ActorUpdateOne {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ActorUpdateOne) SetKind(v string) *ActorUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ActorUpdateOne) SetNillableKind(v *string) *ActorUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ActorUpdateOne) SetName(v string) *ActorUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActorUpdateOne) SetNillableName(v *string) *ActorUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *ActorUpdateOne) SetExternalID(v string) *ActorUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *ActorUpdateOne) SetNillableExternalID(v *string) *ActorUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *ActorUpdateOne) ClearExternalID() *ActorUpdateOne {
	_u.mutation.ClearExternalID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ActorUpdateOne) SetUpdatedAt(v time.Time) *ActorUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ActorMutation object of the builder.
func (_u *ActorUpdateOne) Mutation() *ActorMutation {
	return _u.mutation
}

// Where appends a list predicates to the ActorUpdate builder.
func (_u *ActorUpdateOne) Where(ps ...predicate.Actor) *ActorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActorUpdateOne) Select(field string, fields ...string) *ActorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Actor entity.
func (_u *ActorUpdateOne) Save(ctx context.Context) (*Actor, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActorUpdateOne) SaveX(ctx context.Context) *Actor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := actor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActorUpdateOne) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := actor.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "Actor.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := actor.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`postgres: validator failed for field "Actor.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := actor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`postgres: validator failed for field "Actor.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := actor.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`postgres: validator failed for field "Actor.external_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ActorUpdateOne) sqlSave(ctx context.Context) (_node *Actor, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(actor.Table, actor.Columns, sqlgraph.NewFieldSpec(actor.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`postgres: missing "Actor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, actor.FieldID)
		for _, f := range fields {
			if !actor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("postgres: invalid field %q for query", f)}
			}
			if f != actor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(actor.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(actor.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(actor.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(actor.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(actor.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(actor.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Actor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
