// Code generated by ent, DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/auditevent"
	"github.com/loewenthal-corp/consensus/internal/postgres/predicate"
)

// AuditEventUpdate is the builder for updating AuditEvent entities.
type AuditEventUpdate struct {
	config
	hooks    []Hook
	mutation *AuditEventMutation
}

// Where appends a list predicates to the AuditEventUpdate builder.
func (_u *AuditEventUpdate) Where(ps ...predicate.AuditEvent) *AuditEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantKey sets the "tenant_key" field.
func (_u *AuditEventUpdate) SetTenantKey(v string) *AuditEventUpdate {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableTenantKey(v *string) *AuditEventUpdate {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *AuditEventUpdate) SetActorID(v uuid.UUID) *AuditEventUpdate {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableActorID(v *uuid.UUID) *AuditEventUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// ClearActorID clears the value of the "actor_id" field.
func (_u *AuditEventUpdate) ClearActorID() *AuditEventUpdate {
	_u.mutation.ClearActorID()
	return _u
}

// SetAuthMode sets the "auth_mode" field.
func (_u *AuditEventUpdate) SetAuthMode(v string) *AuditEventUpdate {
	_u.mutation.SetAuthMode(v)
	return _u
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableAuthMode(v *string) *AuditEventUpdate {
	if v != nil {
		_u.SetAuthMode(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditEventUpdate) SetAction(v string) *AuditEventUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableAction(v *string) *AuditEventUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetKind sets the "target_kind" field.
func (_u *AuditEventUpdate) SetTargetKind(v string) *AuditEventUpdate {
	_u.mutation.SetTargetKind(v)
	return _u
}

// SetNillableTargetKind sets the "target_kind" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableTargetKind(v *string) *AuditEventUpdate {
	if v != nil {
		_u.SetTargetKind(*v)
	}
	return _u
}

// ClearTargetKind clears the value of the "target_kind" field.
func (_u *AuditEventUpdate) ClearTargetKind() *AuditEventUpdate {
	_u.mutation.ClearTargetKind()
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *AuditEventUpdate) SetTargetID(v string) *AuditEventUpdate {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableTargetID(v *string) *AuditEventUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *AuditEventUpdate) ClearTargetID() *AuditEventUpdate {
	_u.mutation.ClearTargetID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AuditEventUpdate) SetMetadata(v map[string]string) *AuditEventUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AuditEventUpdate) ClearMetadata() *AuditEventUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the AuditEventMutation object of the builder.
func (_u *AuditEventUpdate) Mutation() *AuditEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditEventUpdate) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := auditevent.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMode(); ok {
		if err := auditevent.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.auth_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := auditevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetKind(); ok {
		if err := auditevent.TargetKindValidator(v); err != nil {
			return &ValidationError{Name: "target_kind", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.target_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetID(); ok {
		if err := auditevent.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.target_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditevent.Table, auditevent.Columns, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(auditevent.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(auditevent.FieldActorID, field.TypeUUID, value)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(auditevent.FieldActorID, field.TypeUUID)
	}
	if value, ok := _u.mutation.AuthMode(); ok {
		_spec.SetField(auditevent.FieldAuthMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditevent.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetKind(); ok {
		_spec.SetField(auditevent.FieldTargetKind, field.TypeString, value)
	}
	if _u.mutation.TargetKindCleared() {
		_spec.ClearField(auditevent.FieldTargetKind, field.TypeString)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(auditevent.FieldTargetID, field.TypeString, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(auditevent.FieldTargetID, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(auditevent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(auditevent.FieldMetadata, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditEventUpdateOne is the builder for updating a single AuditEvent entity.
type AuditEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditEventMutation
}

// SetTenantKey sets the "tenant_key" field.
func (_u *AuditEventUpdateOne) SetTenantKey(v string) *AuditEventUpdateOne {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableTenantKey(v *string) *AuditEventUpdateOne {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *AuditEventUpdateOne) SetActorID(v uuid.UUID) *AuditEventUpdateOne {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableActorID(v *uuid.UUID) *AuditEventUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// ClearActorID clears the value of the "actor_id" field.
func (_u *AuditEventUpdateOne) ClearActorID() *AuditEventUpdateOne {
	_u.mutation.ClearActorID()
	return _u
}

// SetAuthMode sets the "auth_mode" field.
func (_u *AuditEventUpdateOne) SetAuthMode(v string) *AuditEventUpdateOne {
	_u.mutation.SetAuthMode(v)
	return _u
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableAuthMode(v *string) *AuditEventUpdateOne {
	if v != nil {
		_u.SetAuthMode(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditEventUpdateOne) SetAction(v string) *AuditEventUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableAction(v *string) *AuditEventUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetKind sets the "target_kind" field.
func (_u *AuditEventUpdateOne) SetTargetKind(v string) *AuditEventUpdateOne {
	_u.mutation.SetTargetKind(v)
	return _u
}

// SetNillableTargetKind sets the "target_kind" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableTargetKind(v *string) *AuditEventUpdateOne {
	if v != nil {
		_u.SetTargetKind(*v)
	}
	return _u
}

// ClearTargetKind clears the value of the "target_kind" field.
func (_u *AuditEventUpdateOne) ClearTargetKind() *AuditEventUpdateOne {
	_u.mutation.ClearTargetKind()
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *AuditEventUpdateOne) SetTargetID(v string) *AuditEventUpdateOne {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableTargetID(v *string) *AuditEventUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *AuditEventUpdateOne) ClearTargetID() *AuditEventUpdateOne {
	_u.mutation.ClearTargetID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AuditEventUpdateOne) SetMetadata(v map[string]string) *AuditEventUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AuditEventUpdateOne) ClearMetadata() *AuditEventUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the AuditEventMutation object of the builder.
func (_u *AuditEventUpdateOne) Mutation() *AuditEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditEventUpdate builder.
func (_u *AuditEventUpdateOne) Where(ps ...predicate.AuditEvent) *AuditEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditEventUpdateOne) Select(field string, fields ...string) *AuditEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditEvent entity.
func (_u *AuditEventUpdateOne) Save(ctx context.Context) (*AuditEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditEventUpdateOne) SaveX(ctx context.Context) *AuditEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditEventUpdateOne) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := auditevent.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMode(); ok {
		if err := auditevent.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.auth_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := auditevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetKind(); ok {
		if err := auditevent.TargetKindValidator(v); err != nil {
			return &ValidationError{Name: "target_kind", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.target_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetID(); ok {
		if err := auditevent.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.target_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditEventUpdateOne) sqlSave(ctx context.Context) (_node *AuditEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditevent.Table, auditevent.Columns, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`postgres: missing "AuditEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditevent.FieldID)
		for _, f := range fields {
			if !auditevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("postgres: invalid field %q for query", f)}
			}
			if f != auditevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(auditevent.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(auditevent.FieldActorID, field.TypeUUID, value)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(auditevent.FieldActorID, field.TypeUUID)
	}
	if value, ok := _u.mutation.AuthMode(); ok {
		_spec.SetField(auditevent.FieldAuthMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditevent.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetKind(); ok {
		_spec.SetField(auditevent.FieldTargetKind, field.TypeString, value)
	}
	if _u.mutation.TargetKindCleared() {
		_spec.ClearField(auditevent.FieldTargetKind, field.TypeString)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(auditevent.FieldTargetID, field.TypeString, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(auditevent.FieldTargetID, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(auditevent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(auditevent.FieldMetadata, field.TypeJSON)
	}
	_node = &AuditEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
