// Code generated by ent, DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/auditevent"
)

// AuditEventCreate is the builder for creating a AuditEvent entity.
type AuditEventCreate struct {
	config
	mutation *AuditEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantKey sets the "tenant_key" field.
func (_c *AuditEventCreate) SetTenantKey(v string) *AuditEventCreate {
	_c.mutation.SetTenantKey(v)
	return _c
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableTenantKey(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetTenantKey(*v)
	}
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *AuditEventCreate) SetActorID(v uuid.UUID) *AuditEventCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableActorID(v *uuid.UUID) *AuditEventCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetAuthMode sets the "auth_mode" field.
func (_c *AuditEventCreate) SetAuthMode(v string) *AuditEventCreate {
	_c.mutation.SetAuthMode(v)
	return _c
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableAuthMode(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetAuthMode(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *AuditEventCreate) SetAction(v string) *AuditEventCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetTargetKind sets the "target_kind" field.
func (_c *AuditEventCreate) SetTargetKind(v string) *AuditEventCreate {
	_c.mutation.SetTargetKind(v)
	return _c
}

// SetNillableTargetKind sets the "target_kind" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableTargetKind(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetTargetKind(*v)
	}
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *AuditEventCreate) SetTargetID(v string) *AuditEventCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableTargetID(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetTargetID(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AuditEventCreate) SetMetadata(v map[string]string) *AuditEventCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditEventCreate) SetCreatedAt(v time.Time) *AuditEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableCreatedAt(v *time.Time) *AuditEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuditEventCreate) SetID(v uuid.UUID) *AuditEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableID(v *uuid.UUID) *AuditEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AuditEventMutation object of the builder.
func (_c *AuditEventCreate) Mutation() *AuditEventMutation {
	return _c.mutation
}

// Save creates the AuditEvent in the database.
func (_c *AuditEventCreate) Save(ctx context.Context) (*AuditEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditEventCreate) SaveX(ctx context.Context) *AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditEventCreate) defaults() {
	if _, ok := _c.mutation.TenantKey(); !ok {
		v := auditevent.DefaultTenantKey
		_c.mutation.SetTenantKey(v)
	}
	if _, ok := _c.mutation.AuthMode(); !ok {
		v := auditevent.DefaultAuthMode
		_c.mutation.SetAuthMode(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := auditevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := auditevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditEventCreate) check() error {
	if _, ok := _c.mutation.TenantKey(); !ok {
		return &ValidationError{Name: "tenant_key", err: errors.New(`postgres: missing required field "AuditEvent.tenant_key"`)}
	}
	if v, ok := _c.mutation.TenantKey(); ok {
		if err := auditevent.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.tenant_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthMode(); !ok {
		return &ValidationError{Name: "auth_mode", err: errors.New(`postgres: missing required field "AuditEvent.auth_mode"`)}
	}
	if v, ok := _c.mutation.AuthMode(); ok {
		if err := auditevent.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.auth_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`postgres: missing required field "AuditEvent.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := auditevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.action": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TargetKind(); ok {
		if err := auditevent.TargetKindValidator(v); err != nil {
			return &ValidationError{Name: "target_kind", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.target_kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TargetID(); ok {
		if err := auditevent.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`postgres: validator failed for field "AuditEvent.target_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`postgres: missing required field "AuditEvent.created_at"`)}
	}
	return nil
}

func (_c *AuditEventCreate) sqlSave(ctx context.Context) (*AuditEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditEventCreate) createSpec() (*AuditEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditevent.Table, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantKey(); ok {
		_spec.SetField(auditevent.FieldTenantKey, field.TypeString, value)
		_node.TenantKey = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(auditevent.FieldActorID, field.TypeUUID, value)
		_node.ActorID = &value
	}
	if value, ok := _c.mutation.AuthMode(); ok {
		_spec.SetField(auditevent.FieldAuthMode, field.TypeString, value)
		_node.AuthMode = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(auditevent.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.TargetKind(); ok {
		_spec.SetField(auditevent.FieldTargetKind, field.TypeString, value)
		_node.TargetKind = value
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(auditevent.FieldTargetID, field.TypeString, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(auditevent.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(auditevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditEvent.Create().
//		SetTenantKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditEventUpsert) {
//			SetTenantKey(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditEventCreate) OnConflict(opts ...sql.ConflictOption) *AuditEventUpsertOne {
	_c.conflict = opts
	return &AuditEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditEventCreate) OnConflictColumns(columns ...string) *AuditEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditEventUpsertOne{
		create: _c,
	}
}

type (
	// AuditEventUpsertOne is the builder for "upsert"-ing
	//  one AuditEvent node.
	AuditEventUpsertOne struct {
		create *AuditEventCreate
	}

	// AuditEventUpsert is the "OnConflict" setter.
	AuditEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantKey sets the "tenant_key" field.
func (u *AuditEventUpsert) SetTenantKey(v string) *AuditEventUpsert {
	u.Set(auditevent.FieldTenantKey, v)
	return u
}

// UpdateTenantKey sets the "tenant_key" field to the value that was provided on create.
func (u *AuditEventUpsert) UpdateTenantKey() *AuditEventUpsert {
	u.SetExcluded(auditevent.FieldTenantKey)
	return u
}

// SetActorID sets the "actor_id" field.
func (u *AuditEventUpsert) SetActorID(v uuid.UUID) *AuditEventUpsert {
	u.Set(auditevent.FieldActorID, v)
	return u
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *AuditEventUpsert) UpdateActorID() *AuditEventUpsert {
	u.SetExcluded(auditevent.FieldActorID)
	return u
}

// ClearActorID clears the value of the "actor_id" field.
func (u *AuditEventUpsert) ClearActorID() *AuditEventUpsert {
	u.SetNull(auditevent.FieldActorID)
	return u
}

// SetAuthMode sets the "auth_mode" field.
func (u *AuditEventUpsert) SetAuthMode(v string) *AuditEventUpsert {
	u.Set(auditevent.FieldAuthMode, v)
	return u
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *AuditEventUpsert) UpdateAuthMode() *AuditEventUpsert {
	u.SetExcluded(auditevent.FieldAuthMode)
	return u
}

// SetAction sets the "action" field.
func (u *AuditEventUpsert) SetAction(v string) *AuditEventUpsert {
	u.Set(auditevent.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AuditEventUpsert) UpdateAction() *AuditEventUpsert {
	u.SetExcluded(auditevent.FieldAction)
	return u
}

// SetTargetKind sets the "target_kind" field.
func (u *AuditEventUpsert) SetTargetKind(v string) *AuditEventUpsert {
	u.Set(auditevent.FieldTargetKind, v)
	return u
}

// UpdateTargetKind sets the "target_kind" field to the value that was provided on create.
func (u *AuditEventUpsert) UpdateTargetKind() *AuditEventUpsert {
	u.SetExcluded(auditevent.FieldTargetKind)
	return u
}

// ClearTargetKind clears the value of the "target_kind" field.
func (u *AuditEventUpsert) ClearTargetKind() *AuditEventUpsert {
	u.SetNull(auditevent.FieldTargetKind)
	return u
}

// SetTargetID sets the "target_id" field.
func (u *AuditEventUpsert) SetTargetID(v string) *AuditEventUpsert {
	u.Set(auditevent.FieldTargetID, v)
	return u
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *AuditEventUpsert) UpdateTargetID() *AuditEventUpsert {
	u.SetExcluded(auditevent.FieldTargetID)
	return u
}

// ClearTargetID clears the value of the "target_id" field.
func (u *AuditEventUpsert) ClearTargetID() *AuditEventUpsert {
	u.SetNull(auditevent.FieldTargetID)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *AuditEventUpsert) SetMetadata(v map[string]string) *AuditEventUpsert {
	u.Set(auditevent.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *AuditEventUpsert) UpdateMetadata() *AuditEventUpsert {
	u.SetExcluded(auditevent.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *AuditEventUpsert) ClearMetadata() *AuditEventUpsert {
	u.SetNull(auditevent.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(auditevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuditEventUpsertOne) UpdateNewValues() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(auditevent.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(auditevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuditEventUpsertOne) Ignore() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditEventUpsertOne) DoNothing() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditEventCreate.OnConflict
// documentation for more info.
func (u *AuditEventUpsertOne) Update(set func(*AuditEventUpsert)) *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantKey sets the "tenant_key" field.
func (u *AuditEventUpsertOne) SetTenantKey(v string) *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetTenantKey(v)
	})
}

// UpdateTenantKey sets the "tenant_key" field to the value that was provided on create.
func (u *AuditEventUpsertOne) UpdateTenantKey() *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateTenantKey()
	})
}

// SetActorID sets the "actor_id" field.
func (u *AuditEventUpsertOne) SetActorID(v uuid.UUID) *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *AuditEventUpsertOne) UpdateActorID() *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateActorID()
	})
}

// ClearActorID clears the value of the "actor_id" field.
func (u *AuditEventUpsertOne) ClearActorID() *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.ClearActorID()
	})
}

// SetAuthMode sets the "auth_mode" field.
func (u *AuditEventUpsertOne) SetAuthMode(v string) *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetAuthMode(v)
	})
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *AuditEventUpsertOne) UpdateAuthMode() *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateAuthMode()
	})
}

// SetAction sets the "action" field.
func (u *AuditEventUpsertOne) SetAction(v string) *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AuditEventUpsertOne) UpdateAction() *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateAction()
	})
}

// SetTargetKind sets the "target_kind" field.
func (u *AuditEventUpsertOne) SetTargetKind(v string) *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetTargetKind(v)
	})
}

// UpdateTargetKind sets the "target_kind" field to the value that was provided on create.
func (u *AuditEventUpsertOne) UpdateTargetKind() *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateTargetKind()
	})
}

// ClearTargetKind clears the value of the "target_kind" field.
func (u *AuditEventUpsertOne) ClearTargetKind() *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.ClearTargetKind()
	})
}

// SetTargetID sets the "target_id" field.
func (u *AuditEventUpsertOne) SetTargetID(v string) *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetTargetID(v)
	})
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *AuditEventUpsertOne) UpdateTargetID() *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateTargetID()
	})
}

// ClearTargetID clears the value of the "target_id" field.
func (u *AuditEventUpsertOne) ClearTargetID() *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.ClearTargetID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *AuditEventUpsertOne) SetMetadata(v map[string]string) *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *AuditEventUpsertOne) UpdateMetadata() *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *AuditEventUpsertOne) ClearMetadata() *AuditEventUpsertOne {
	return u.Update(func(s *AuditEventUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *AuditEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("postgres: missing options for AuditEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuditEventUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("postgres: AuditEventUpsertOne.ID is not supported by MySQL driver. Use AuditEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuditEventUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuditEventCreateBulk is the builder for creating many AuditEvent entities in bulk.
type AuditEventCreateBulk struct {
	config
	err      error
	builders []*AuditEventCreate
	conflict []sql.ConflictOption
}

// Save creates the AuditEvent entities in the database.
func (_c *AuditEventCreateBulk) Save(ctx context.Context) ([]*AuditEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditEventCreateBulk) SaveX(ctx context.Context) []*AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditEventUpsert) {
//			SetTenantKey(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuditEventUpsertBulk {
	_c.conflict = opts
	return &AuditEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditEventCreateBulk) OnConflictColumns(columns ...string) *AuditEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditEventUpsertBulk{
		create: _c,
	}
}

// AuditEventUpsertBulk is the builder for "upsert"-ing
// a bulk of AuditEvent nodes.
type AuditEventUpsertBulk struct {
	create *AuditEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(auditevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuditEventUpsertBulk) UpdateNewValues() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(auditevent.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(auditevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuditEventUpsertBulk) Ignore() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditEventUpsertBulk) DoNothing() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditEventCreateBulk.OnConflict
// documentation for more info.
func (u *AuditEventUpsertBulk) Update(set func(*AuditEventUpsert)) *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantKey sets the "tenant_key" field.
func (u *AuditEventUpsertBulk) SetTenantKey(v string) *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetTenantKey(v)
	})
}

// UpdateTenantKey sets the "tenant_key" field to the value that was provided on create.
func (u *AuditEventUpsertBulk) UpdateTenantKey() *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateTenantKey()
	})
}

// SetActorID sets the "actor_id" field.
func (u *AuditEventUpsertBulk) SetActorID(v uuid.UUID) *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *AuditEventUpsertBulk) UpdateActorID() *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateActorID()
	})
}

// ClearActorID clears the value of the "actor_id" field.
func (u *AuditEventUpsertBulk) ClearActorID() *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.ClearActorID()
	})
}

// SetAuthMode sets the "auth_mode" field.
func (u *AuditEventUpsertBulk) SetAuthMode(v string) *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetAuthMode(v)
	})
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *AuditEventUpsertBulk) UpdateAuthMode() *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateAuthMode()
	})
}

// SetAction sets the "action" field.
func (u *AuditEventUpsertBulk) SetAction(v string) *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AuditEventUpsertBulk) UpdateAction() *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateAction()
	})
}

// SetTargetKind sets the "target_kind" field.
func (u *AuditEventUpsertBulk) SetTargetKind(v string) *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetTargetKind(v)
	})
}

// UpdateTargetKind sets the "target_kind" field to the value that was provided on create.
func (u *AuditEventUpsertBulk) UpdateTargetKind() *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateTargetKind()
	})
}

// ClearTargetKind clears the value of the "target_kind" field.
func (u *AuditEventUpsertBulk) ClearTargetKind() *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.ClearTargetKind()
	})
}

// SetTargetID sets the "target_id" field.
func (u *AuditEventUpsertBulk) SetTargetID(v string) *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetTargetID(v)
	})
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *AuditEventUpsertBulk) UpdateTargetID() *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateTargetID()
	})
}

// ClearTargetID clears the value of the "target_id" field.
func (u *AuditEventUpsertBulk) ClearTargetID() *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.ClearTargetID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *AuditEventUpsertBulk) SetMetadata(v map[string]string) *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *AuditEventUpsertBulk) UpdateMetadata() *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *AuditEventUpsertBulk) ClearMetadata() *AuditEventUpsertBulk {
	return u.Update(func(s *AuditEventUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *AuditEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("postgres: OnConflict was set for builder %d. Set it on the AuditEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("postgres: missing options for AuditEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
