// Code generated by ent, DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/graphedge"
)

// GraphEdgeCreate is the builder for creating a GraphEdge entity.
type GraphEdgeCreate struct {
	config
	mutation *GraphEdgeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantKey sets the "tenant_key" field.
func (_c *GraphEdgeCreate) SetTenantKey(v string) *GraphEdgeCreate {
	_c.mutation.SetTenantKey(v)
	return _c
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_c *GraphEdgeCreate) SetNillableTenantKey(v *string) *GraphEdgeCreate {
	if v != nil {
		_c.SetTenantKey(*v)
	}
	return _c
}

// SetFromID sets the "from_id" field.
func (_c *GraphEdgeCreate) SetFromID(v uuid.UUID) *GraphEdgeCreate {
	_c.mutation.SetFromID(v)
	return _c
}

// SetToID sets the "to_id" field.
func (_c *GraphEdgeCreate) SetToID(v uuid.UUID) *GraphEdgeCreate {
	_c.mutation.SetToID(v)
	return _c
}

// SetRelationship sets the "relationship" field.
func (_c *GraphEdgeCreate) SetRelationship(v string) *GraphEdgeCreate {
	_c.mutation.SetRelationship(v)
	return _c
}

// SetRationale sets the "rationale" field.
func (_c *GraphEdgeCreate) SetRationale(v string) *GraphEdgeCreate {
	_c.mutation.SetRationale(v)
	return _c
}

// SetNillableRationale sets the "rationale" field if the given value is not nil.
func (_c *GraphEdgeCreate) SetNillableRationale(v *string) *GraphEdgeCreate {
	if v != nil {
		_c.SetRationale(*v)
	}
	return _c
}

// SetReviewState sets the "review_state" field.
func (_c *GraphEdgeCreate) SetReviewState(v string) *GraphEdgeCreate {
	_c.mutation.SetReviewState(v)
	return _c
}

// SetNillableReviewState sets the "review_state" field if the given value is not nil.
func (_c *GraphEdgeCreate) SetNillableReviewState(v *string) *GraphEdgeCreate {
	if v != nil {
		_c.SetReviewState(*v)
	}
	return _c
}

// SetTombstonedAt sets the "tombstoned_at" field.
func (_c *GraphEdgeCreate) SetTombstonedAt(v time.Time) *GraphEdgeCreate {
	_c.mutation.SetTombstonedAt(v)
	return _c
}

// SetNillableTombstonedAt sets the "tombstoned_at" field if the given value is not nil.
func (_c *GraphEdgeCreate) SetNillableTombstonedAt(v *time.Time) *GraphEdgeCreate {
	if v != nil {
		_c.SetTombstonedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GraphEdgeCreate) SetCreatedAt(v time.Time) *GraphEdgeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GraphEdgeCreate) SetNillableCreatedAt(v *time.Time) *GraphEdgeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GraphEdgeCreate) SetUpdatedAt(v time.Time) *GraphEdgeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GraphEdgeCreate) SetNillableUpdatedAt(v *time.Time) *GraphEdgeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GraphEdgeCreate) SetID(v uuid.UUID) *GraphEdgeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GraphEdgeCreate) SetNillableID(v *uuid.UUID) *GraphEdgeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the GraphEdgeMutation object of the builder.
func (_c *GraphEdgeCreate) Mutation() *GraphEdgeMutation {
	return _c.mutation
}

// Save creates the GraphEdge in the database.
func (_c *GraphEdgeCreate) Save(ctx context.Context) (*GraphEdge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GraphEdgeCreate) SaveX(ctx context.Context) *GraphEdge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GraphEdgeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GraphEdgeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GraphEdgeCreate) defaults() {
	if _, ok := _c.mutation.TenantKey(); !ok {
		v := graphedge.DefaultTenantKey
		_c.mutation.SetTenantKey(v)
	}
	if _, ok := _c.mutation.ReviewState(); !ok {
		v := graphedge.DefaultReviewState
		_c.mutation.SetReviewState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := graphedge.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := graphedge.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := graphedge.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GraphEdgeCreate) check() error {
	if _, ok := _c.mutation.TenantKey(); !ok {
		return &ValidationError{Name: "tenant_key", err: errors.New(`postgres: missing required field "GraphEdge.tenant_key"`)}
	}
	if v, ok := _c.mutation.TenantKey(); ok {
		if err := graphedge.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "GraphEdge.tenant_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromID(); !ok {
		return &ValidationError{Name: "from_id", err: errors.New(`postgres: missing required field "GraphEdge.from_id"`)}
	}
	if _, ok := _c.mutation.ToID(); !ok {
		return &ValidationError{Name: "to_id", err: errors.New(`postgres: missing required field "GraphEdge.to_id"`)}
	}
	if _, ok := _c.mutation.Relationship(); !ok {
		return &ValidationError{Name: "relationship", err: errors.New(`postgres: missing required field "GraphEdge.relationship"`)}
	}
	if v, ok := _c.mutation.Relationship(); ok {
		if err := graphedge.RelationshipValidator(v); err != nil {
			return &ValidationError{Name: "relationship", err: fmt.Errorf(`postgres: validator failed for field "GraphEdge.relationship": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReviewState(); !ok {
		return &ValidationError{Name: "review_state", err: errors.New(`postgres: missing required field "GraphEdge.review_state"`)}
	}
	if v, ok := _c.mutation.ReviewState(); ok {
		if err := graphedge.ReviewStateValidator(v); err != nil {
			return &ValidationError{Name: "review_state", err: fmt.Errorf(`postgres: validator failed for field "GraphEdge.review_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`postgres: missing required field "GraphEdge.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`postgres: missing required field "GraphEdge.updated_at"`)}
	}
	return nil
}

func (_c *GraphEdgeCreate) sqlSave(ctx context.Context) (*GraphEdge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GraphEdgeCreate) createSpec() (*GraphEdge, *sqlgraph.CreateSpec) {
	var (
		_node = &GraphEdge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(graphedge.Table, sqlgraph.NewFieldSpec(graphedge.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantKey(); ok {
		_spec.SetField(graphedge.FieldTenantKey, field.TypeString, value)
		_node.TenantKey = value
	}
	if value, ok := _c.mutation.FromID(); ok {
		_spec.SetField(graphedge.FieldFromID, field.TypeUUID, value)
		_node.FromID = value
	}
	if value, ok := _c.mutation.ToID(); ok {
		_spec.SetField(graphedge.FieldToID, field.TypeUUID, value)
		_node.ToID = value
	}
	if value, ok := _c.mutation.Relationship(); ok {
		_spec.SetField(graphedge.FieldRelationship, field.TypeString, value)
		_node.Relationship = value
	}
	if value, ok := _c.mutation.Rationale(); ok {
		_spec.SetField(graphedge.FieldRationale, field.TypeString, value)
		_node.Rationale = value
	}
	if value, ok := _c.mutation.ReviewState(); ok {
		_spec.SetField(graphedge.FieldReviewState, field.TypeString, value)
		_node.ReviewState = value
	}
	if value, ok := _c.mutation.TombstonedAt(); ok {
		_spec.SetField(graphedge.FieldTombstonedAt, field.TypeTime, value)
		_node.TombstonedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(graphedge.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(graphedge.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GraphEdge.Create().
//		SetTenantKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GraphEdgeUpsert) {
//			SetTenantKey(v+v).
//		}).
//		Exec(ctx)
func (_c *GraphEdgeCreate) OnConflict(opts ...sql.ConflictOption) *GraphEdgeUpsertOne {
	_c.conflict = opts
	return &GraphEdgeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GraphEdge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GraphEdgeCreate) OnConflictColumns(columns ...string) *GraphEdgeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GraphEdgeUpsertOne{
		create: _c,
	}
}

type (
	// GraphEdgeUpsertOne is the builder for "upsert"-ing
	//  one GraphEdge node.
	GraphEdgeUpsertOne struct {
		create *GraphEdgeCreate
	}

	// GraphEdgeUpsert is the "OnConflict" setter.
	GraphEdgeUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantKey sets the "tenant_key" field.
func (u *GraphEdgeUpsert) SetTenantKey(v string) *GraphEdgeUpsert {
	u.Set(graphedge.FieldTenantKey, v)
	return u
}

// UpdateTenantKey sets the "tenant_key" field to the value that was provided on create.
func (u *GraphEdgeUpsert) UpdateTenantKey() *GraphEdgeUpsert {
	u.SetExcluded(graphedge.FieldTenantKey)
	return u
}

// SetFromID sets the "from_id" field.
func (u *GraphEdgeUpsert) SetFromID(v uuid.UUID) *GraphEdgeUpsert {
	u.Set(graphedge.FieldFromID, v)
	return u
}

// UpdateFromID sets the "from_id" field to the value that was provided on create.
func (u *GraphEdgeUpsert) UpdateFromID() *GraphEdgeUpsert {
	u.SetExcluded(graphedge.FieldFromID)
	return u
}

// SetToID sets the "to_id" field.
func (u *GraphEdgeUpsert) SetToID(v uuid.UUID) *GraphEdgeUpsert {
	u.Set(graphedge.FieldToID, v)
	return u
}

// UpdateToID sets the "to_id" field to the value that was provided on create.
func (u *GraphEdgeUpsert) UpdateToID() *GraphEdgeUpsert {
	u.SetExcluded(graphedge.FieldToID)
	return u
}

// SetRelationship sets the "relationship" field.
func (u *GraphEdgeUpsert) SetRelationship(v string) *GraphEdgeUpsert {
	u.Set(graphedge.FieldRelationship, v)
	return u
}

// UpdateRelationship sets the "relationship" field to the value that was provided on create.
func (u *GraphEdgeUpsert) UpdateRelationship() *GraphEdgeUpsert {
	u.SetExcluded(graphedge.FieldRelationship)
	return u
}

// SetRationale sets the "rationale" field.
func (u *GraphEdgeUpsert) SetRationale(v string) *GraphEdgeUpsert {
	u.Set(graphedge.FieldRationale, v)
	return u
}

// UpdateRationale sets the "rationale" field to the value that was provided on create.
func (u *GraphEdgeUpsert) UpdateRationale() *GraphEdgeUpsert {
	u.SetExcluded(graphedge.FieldRationale)
	return u
}

// ClearRationale clears the value of the "rationale" field.
func (u *GraphEdgeUpsert) ClearRationale() *GraphEdgeUpsert {
	u.SetNull(graphedge.FieldRationale)
	return u
}

// SetReviewState sets the "review_state" field.
func (u *GraphEdgeUpsert) SetReviewState(v string) *GraphEdgeUpsert {
	u.Set(graphedge.FieldReviewState, v)
	return u
}

// UpdateReviewState sets the "review_state" field to the value that was provided on create.
func (u *GraphEdgeUpsert) UpdateReviewState() *GraphEdgeUpsert {
	u.SetExcluded(graphedge.FieldReviewState)
	return u
}

// SetTombstonedAt sets the "tombstoned_at" field.
func (u *GraphEdgeUpsert) SetTombstonedAt(v time.Time) *GraphEdgeUpsert {
	u.Set(graphedge.FieldTombstonedAt, v)
	return u
}

// UpdateTombstonedAt sets the "tombstoned_at" field to the value that was provided on create.
func (u *GraphEdgeUpsert) UpdateTombstonedAt() *GraphEdgeUpsert {
	u.SetExcluded(graphedge.FieldTombstonedAt)
	return u
}

// ClearTombstonedAt clears the value of the "tombstoned_at" field.
func (u *GraphEdgeUpsert) ClearTombstonedAt() *GraphEdgeUpsert {
	u.SetNull(graphedge.FieldTombstonedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GraphEdgeUpsert) SetUpdatedAt(v time.Time) *GraphEdgeUpsert {
	u.Set(graphedge.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GraphEdgeUpsert) UpdateUpdatedAt() *GraphEdgeUpsert {
	u.SetExcluded(graphedge.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GraphEdge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(graphedge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GraphEdgeUpsertOne) UpdateNewValues() *GraphEdgeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(graphedge.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(graphedge.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GraphEdge.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GraphEdgeUpsertOne) Ignore() *GraphEdgeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GraphEdgeUpsertOne) DoNothing() *GraphEdgeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GraphEdgeCreate.OnConflict
// documentation for more info.
func (u *GraphEdgeUpsertOne) Update(set func(*GraphEdgeUpsert)) *GraphEdgeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GraphEdgeUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantKey sets the "tenant_key" field.
func (u *GraphEdgeUpsertOne) SetTenantKey(v string) *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetTenantKey(v)
	})
}

// UpdateTenantKey sets the "tenant_key" field to the value that was provided on create.
func (u *GraphEdgeUpsertOne) UpdateTenantKey() *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateTenantKey()
	})
}

// SetFromID sets the "from_id" field.
func (u *GraphEdgeUpsertOne) SetFromID(v uuid.UUID) *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetFromID(v)
	})
}

// UpdateFromID sets the "from_id" field to the value that was provided on create.
func (u *GraphEdgeUpsertOne) UpdateFromID() *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateFromID()
	})
}

// SetToID sets the "to_id" field.
func (u *GraphEdgeUpsertOne) SetToID(v uuid.UUID) *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetToID(v)
	})
}

// UpdateToID sets the "to_id" field to the value that was provided on create.
func (u *GraphEdgeUpsertOne) UpdateToID() *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateToID()
	})
}

// SetRelationship sets the "relationship" field.
func (u *GraphEdgeUpsertOne) SetRelationship(v string) *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetRelationship(v)
	})
}

// UpdateRelationship sets the "relationship" field to the value that was provided on create.
func (u *GraphEdgeUpsertOne) UpdateRelationship() *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateRelationship()
	})
}

// SetRationale sets the "rationale" field.
func (u *GraphEdgeUpsertOne) SetRationale(v string) *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetRationale(v)
	})
}

// UpdateRationale sets the "rationale" field to the value that was provided on create.
func (u *GraphEdgeUpsertOne) UpdateRationale() *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateRationale()
	})
}

// ClearRationale clears the value of the "rationale" field.
func (u *GraphEdgeUpsertOne) ClearRationale() *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.ClearRationale()
	})
}

// SetReviewState sets the "review_state" field.
func (u *GraphEdgeUpsertOne) SetReviewState(v string) *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetReviewState(v)
	})
}

// UpdateReviewState sets the "review_state" field to the value that was provided on create.
func (u *GraphEdgeUpsertOne) UpdateReviewState() *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateReviewState()
	})
}

// SetTombstonedAt sets the "tombstoned_at" field.
func (u *GraphEdgeUpsertOne) SetTombstonedAt(v time.Time) *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetTombstonedAt(v)
	})
}

// UpdateTombstonedAt sets the "tombstoned_at" field to the value that was provided on create.
func (u *GraphEdgeUpsertOne) UpdateTombstonedAt() *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateTombstonedAt()
	})
}

// ClearTombstonedAt clears the value of the "tombstoned_at" field.
func (u *GraphEdgeUpsertOne) ClearTombstonedAt() *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.ClearTombstonedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GraphEdgeUpsertOne) SetUpdatedAt(v time.Time) *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GraphEdgeUpsertOne) UpdateUpdatedAt() *GraphEdgeUpsertOne {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GraphEdgeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("postgres: missing options for GraphEdgeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GraphEdgeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GraphEdgeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("postgres: GraphEdgeUpsertOne.ID is not supported by MySQL driver. Use GraphEdgeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GraphEdgeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GraphEdgeCreateBulk is the builder for creating many GraphEdge entities in bulk.
type GraphEdgeCreateBulk struct {
	config
	err      error
	builders []*GraphEdgeCreate
	conflict []sql.ConflictOption
}

// Save creates the GraphEdge entities in the database.
func (_c *GraphEdgeCreateBulk) Save(ctx context.Context) ([]*GraphEdge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GraphEdge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GraphEdgeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GraphEdgeCreateBulk) SaveX(ctx context.Context) []*GraphEdge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GraphEdgeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GraphEdgeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GraphEdge.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GraphEdgeUpsert) {
//			SetTenantKey(v+v).
//		}).
//		Exec(ctx)
func (_c *GraphEdgeCreateBulk) OnConflict(opts ...sql.ConflictOption) *GraphEdgeUpsertBulk {
	_c.conflict = opts
	return &GraphEdgeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GraphEdge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GraphEdgeCreateBulk) OnConflictColumns(columns ...string) *GraphEdgeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GraphEdgeUpsertBulk{
		create: _c,
	}
}

// GraphEdgeUpsertBulk is the builder for "upsert"-ing
// a bulk of GraphEdge nodes.
type GraphEdgeUpsertBulk struct {
	create *GraphEdgeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GraphEdge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(graphedge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GraphEdgeUpsertBulk) UpdateNewValues() *GraphEdgeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(graphedge.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(graphedge.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GraphEdge.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GraphEdgeUpsertBulk) Ignore() *GraphEdgeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GraphEdgeUpsertBulk) DoNothing() *GraphEdgeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GraphEdgeCreateBulk.OnConflict
// documentation for more info.
func (u *GraphEdgeUpsertBulk) Update(set func(*GraphEdgeUpsert)) *GraphEdgeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GraphEdgeUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantKey sets the "tenant_key" field.
func (u *GraphEdgeUpsertBulk) SetTenantKey(v string) *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetTenantKey(v)
	})
}

// UpdateTenantKey sets the "tenant_key" field to the value that was provided on create.
func (u *GraphEdgeUpsertBulk) UpdateTenantKey() *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateTenantKey()
	})
}

// SetFromID sets the "from_id" field.
func (u *GraphEdgeUpsertBulk) SetFromID(v uuid.UUID) *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetFromID(v)
	})
}

// UpdateFromID sets the "from_id" field to the value that was provided on create.
func (u *GraphEdgeUpsertBulk) UpdateFromID() *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateFromID()
	})
}

// SetToID sets the "to_id" field.
func (u *GraphEdgeUpsertBulk) SetToID(v uuid.UUID) *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetToID(v)
	})
}

// UpdateToID sets the "to_id" field to the value that was provided on create.
func (u *GraphEdgeUpsertBulk) UpdateToID() *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateToID()
	})
}

// SetRelationship sets the "relationship" field.
func (u *GraphEdgeUpsertBulk) SetRelationship(v string) *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetRelationship(v)
	})
}

// UpdateRelationship sets the "relationship" field to the value that was provided on create.
func (u *GraphEdgeUpsertBulk) UpdateRelationship() *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateRelationship()
	})
}

// SetRationale sets the "rationale" field.
func (u *GraphEdgeUpsertBulk) SetRationale(v string) *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetRationale(v)
	})
}

// UpdateRationale sets the "rationale" field to the value that was provided on create.
func (u *GraphEdgeUpsertBulk) UpdateRationale() *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateRationale()
	})
}

// ClearRationale clears the value of the "rationale" field.
func (u *GraphEdgeUpsertBulk) ClearRationale() *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.ClearRationale()
	})
}

// SetReviewState sets the "review_state" field.
func (u *GraphEdgeUpsertBulk) SetReviewState(v string) *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetReviewState(v)
	})
}

// UpdateReviewState sets the "review_state" field to the value that was provided on create.
func (u *GraphEdgeUpsertBulk) UpdateReviewState() *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateReviewState()
	})
}

// SetTombstonedAt sets the "tombstoned_at" field.
func (u *GraphEdgeUpsertBulk) SetTombstonedAt(v time.Time) *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetTombstonedAt(v)
	})
}

// UpdateTombstonedAt sets the "tombstoned_at" field to the value that was provided on create.
func (u *GraphEdgeUpsertBulk) UpdateTombstonedAt() *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateTombstonedAt()
	})
}

// ClearTombstonedAt clears the value of the "tombstoned_at" field.
func (u *GraphEdgeUpsertBulk) ClearTombstonedAt() *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.ClearTombstonedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GraphEdgeUpsertBulk) SetUpdatedAt(v time.Time) *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GraphEdgeUpsertBulk) UpdateUpdatedAt() *GraphEdgeUpsertBulk {
	return u.Update(func(s *GraphEdgeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GraphEdgeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("postgres: OnConflict was set for builder %d. Set it on the GraphEdgeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("postgres: missing options for GraphEdgeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GraphEdgeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
