// Code generated by ent, DO NOT EDIT.

package postgres

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/insight"
)

// Insight is the model entity for the Insight schema.
type Insight struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantKey holds the value of the "tenant_key" field.
	TenantKey string `json:"tenant_key,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Problem holds the value of the "problem" field.
	Problem string `json:"problem,omitempty"`
	// Answer holds the value of the "answer" field.
	Answer string `json:"answer,omitempty"`
	// Example holds the value of the "example" field.
	Example map[string]string `json:"example,omitempty"`
	// Detail holds the value of the "detail" field.
	Detail string `json:"detail,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags []string `json:"tags,omitempty"`
	// Context holds the value of the "context" field.
	Context map[string]string `json:"context,omitempty"`
	// Links holds the value of the "links" field.
	Links []map[string]string `json:"links,omitempty"`
	// CreatedByActorID holds the value of the "created_by_actor_id" field.
	CreatedByActorID *uuid.UUID `json:"created_by_actor_id,omitempty"`
	// SourceRunID holds the value of the "source_run_id" field.
	SourceRunID *string `json:"source_run_id,omitempty"`
	// ReviewState holds the value of the "review_state" field.
	ReviewState string `json:"review_state,omitempty"`
	// LifecycleState holds the value of the "lifecycle_state" field.
	LifecycleState string `json:"lifecycle_state,omitempty"`
	// SupersededByID holds the value of the "superseded_by_id" field.
	SupersededByID *uuid.UUID `json:"superseded_by_id,omitempty"`
	// LastConfirmedAt holds the value of the "last_confirmed_at" field.
	LastConfirmedAt *time.Time `json:"last_confirmed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Insight) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case insight.FieldCreatedByActorID, insight.FieldSupersededByID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case insight.FieldExample, insight.FieldTags, insight.FieldContext, insight.FieldLinks:
			values[i] = new([]byte)
		case insight.FieldTenantKey, insight.FieldTitle, insight.FieldProblem, insight.FieldAnswer, insight.FieldDetail, insight.FieldAction, insight.FieldKind, insight.FieldSourceRunID, insight.FieldReviewState, insight.FieldLifecycleState:
			values[i] = new(sql.NullString)
		case insight.FieldLastConfirmedAt, insight.FieldCreatedAt, insight.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case insight.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Insight fields.
func (_m *Insight) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case insight.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case insight.FieldTenantKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_key", values[i])
			} else if value.Valid {
				_m.TenantKey = value.String
			}
		case insight.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case insight.FieldProblem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field problem", values[i])
			} else if value.Valid {
				_m.Problem = value.String
			}
		case insight.FieldAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field answer", values[i])
			} else if value.Valid {
				_m.Answer = value.String
			}
		case insight.FieldExample:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field example", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Example); err != nil {
					return fmt.Errorf("unmarshal field example: %w", err)
				}
			}
		case insight.FieldDetail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field detail", values[i])
			} else if value.Valid {
				_m.Detail = value.String
			}
		case insight.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case insight.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case insight.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case insight.FieldContext:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field context", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Context); err != nil {
					return fmt.Errorf("unmarshal field context: %w", err)
				}
			}
		case insight.FieldLinks:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field links", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Links); err != nil {
					return fmt.Errorf("unmarshal field links: %w", err)
				}
			}
		case insight.FieldCreatedByActorID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_actor_id", values[i])
			} else if value.Valid {
				_m.CreatedByActorID = new(uuid.UUID)
				*_m.CreatedByActorID = *value.S.(*uuid.UUID)
			}
		case insight.FieldSourceRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_run_id", values[i])
			} else if value.Valid {
				_m.SourceRunID = new(string)
				*_m.SourceRunID = value.String
			}
		case insight.FieldReviewState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_state", values[i])
			} else if value.Valid {
				_m.ReviewState = value.String
			}
		case insight.FieldLifecycleState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lifecycle_state", values[i])
			} else if value.Valid {
				_m.LifecycleState = value.String
			}
		case insight.FieldSupersededByID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field superseded_by_id", values[i])
			} else if value.Valid {
				_m.SupersededByID = new(uuid.UUID)
				*_m.SupersededByID = *value.S.(*uuid.UUID)
			}
		case insight.FieldLastConfirmedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_confirmed_at", values[i])
			} else if value.Valid {
				_m.LastConfirmedAt = new(time.Time)
				*_m.LastConfirmedAt = value.Time
			}
		case insight.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case insight.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Insight.
// This includes values selected through modifiers, order, etc.
func (_m *Insight) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Insight.
// Note that you need to call Insight.Unwrap() before calling this method if this Insight
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Insight) Update() *InsightUpdateOne {
	return NewInsightClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Insight entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Insight) Unwrap() *Insight {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("postgres: Insight is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Insight) String() string {
	var builder strings.Builder
	builder.WriteString("Insight(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_key=")
	builder.WriteString(_m.TenantKey)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("problem=")
	builder.WriteString(_m.Problem)
	builder.WriteString(", ")
	builder.WriteString("answer=")
	builder.WriteString(_m.Answer)
	builder.WriteString(", ")
	builder.WriteString("example=")
	builder.WriteString(fmt.Sprintf("%v", _m.Example))
	builder.WriteString(", ")
	builder.WriteString("detail=")
	builder.WriteString(_m.Detail)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("context=")
	builder.WriteString(fmt.Sprintf("%v", _m.Context))
	builder.WriteString(", ")
	builder.WriteString("links=")
	builder.WriteString(fmt.Sprintf("%v", _m.Links))
	builder.WriteString(", ")
	if v := _m.CreatedByActorID; v != nil {
		builder.WriteString("created_by_actor_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SourceRunID; v != nil {
		builder.WriteString("source_run_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("review_state=")
	builder.WriteString(_m.ReviewState)
	builder.WriteString(", ")
	builder.WriteString("lifecycle_state=")
	builder.WriteString(_m.LifecycleState)
	builder.WriteString(", ")
	if v := _m.SupersededByID; v != nil {
		builder.WriteString("superseded_by_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastConfirmedAt; v != nil {
		builder.WriteString("last_confirmed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Insights is a parsable slice of Insight.
type Insights []*Insight
