// Code generated by ent, DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/insight"
	"github.com/loewenthal-corp/consensus/internal/postgres/predicate"
)

// InsightUpdate is the builder for updating Insight entities.
type InsightUpdate struct {
	config
	hooks    []Hook
	mutation *InsightMutation
}

// Where appends a list predicates to the InsightUpdate builder.
func (_u *InsightUpdate) Where(ps ...predicate.Insight) *InsightUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantKey sets the "tenant_key" field.
func (_u *InsightUpdate) SetTenantKey(v string) *InsightUpdate {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableTenantKey(v *string) *InsightUpdate {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InsightUpdate) SetTitle(v string) *InsightUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableTitle(v *string) *InsightUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetProblem sets the "problem" field.
func (_u *InsightUpdate) SetProblem(v string) *InsightUpdate {
	_u.mutation.SetProblem(v)
	return _u
}

// SetNillableProblem sets the "problem" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableProblem(v *string) *InsightUpdate {
	if v != nil {
		_u.SetProblem(*v)
	}
	return _u
}

// ClearProblem clears the value of the "problem" field.
func (_u *InsightUpdate) ClearProblem() *InsightUpdate {
	_u.mutation.ClearProblem()
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *InsightUpdate) SetAnswer(v string) *InsightUpdate {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableAnswer(v *string) *InsightUpdate {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// SetExample sets the "example" field.
func (_u *InsightUpdate) SetExample(v map[string]string) *InsightUpdate {
	_u.mutation.SetExample(v)
	return _u
}

// ClearExample clears the value of the "example" field.
func (_u *InsightUpdate) ClearExample() *InsightUpdate {
	_u.mutation.ClearExample()
	return _u
}

// SetDetail sets the "detail" field.
func (_u *InsightUpdate) SetDetail(v string) *InsightUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableDetail(v *string) *InsightUpdate {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *InsightUpdate) ClearDetail() *InsightUpdate {
	_u.mutation.ClearDetail()
	return _u
}

// SetAction sets the "action" field.
func (_u *InsightUpdate) SetAction(v string) *InsightUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableAction(v *string) *InsightUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// ClearAction clears the value of the "action" field.
func (_u *InsightUpdate) ClearAction() *InsightUpdate {
	_u.mutation.ClearAction()
	return _u
}

// SetTags sets the "tags" field.
func (_u *InsightUpdate) SetTags(v []string) *InsightUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *InsightUpdate) AppendTags(v []string) *InsightUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *InsightUpdate) ClearTags() *InsightUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetLinks sets the "links" field.
func (_u *InsightUpdate) SetLinks(v []map[string]string) *InsightUpdate {
	_u.mutation.SetLinks(v)
	return _u
}

// AppendLinks appends value to the "links" field.
func (_u *InsightUpdate) AppendLinks(v []map[string]string) *InsightUpdate {
	_u.mutation.AppendLinks(v)
	return _u
}

// ClearLinks clears the value of the "links" field.
func (_u *InsightUpdate) ClearLinks() *InsightUpdate {
	_u.mutation.ClearLinks()
	return _u
}

// SetCreatedByActorID sets the "created_by_actor_id" field.
func (_u *InsightUpdate) SetCreatedByActorID(v uuid.UUID) *InsightUpdate {
	_u.mutation.SetCreatedByActorID(v)
	return _u
}

// SetNillableCreatedByActorID sets the "created_by_actor_id" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableCreatedByActorID(v *uuid.UUID) *InsightUpdate {
	if v != nil {
		_u.SetCreatedByActorID(*v)
	}
	return _u
}

// ClearCreatedByActorID clears the value of the "created_by_actor_id" field.
func (_u *InsightUpdate) ClearCreatedByActorID() *InsightUpdate {
	_u.mutation.ClearCreatedByActorID()
	return _u
}

// SetSourceRunID sets the "source_run_id" field.
func (_u *InsightUpdate) SetSourceRunID(v string) *InsightUpdate {
	_u.mutation.SetSourceRunID(v)
	return _u
}

// SetNillableSourceRunID sets the "source_run_id" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableSourceRunID(v *string) *InsightUpdate {
	if v != nil {
		_u.SetSourceRunID(*v)
	}
	return _u
}

// ClearSourceRunID clears the value of the "source_run_id" field.
func (_u *InsightUpdate) ClearSourceRunID() *InsightUpdate {
	_u.mutation.ClearSourceRunID()
	return _u
}

// SetReviewState sets the "review_state" field.
func (_u *InsightUpdate) SetReviewState(v string) *InsightUpdate {
	_u.mutation.SetReviewState(v)
	return _u
}

// SetNillableReviewState sets the "review_state" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableReviewState(v *string) *InsightUpdate {
	if v != nil {
		_u.SetReviewState(*v)
	}
	return _u
}

// SetLifecycleState sets the "lifecycle_state" field.
func (_u *InsightUpdate) SetLifecycleState(v string) *InsightUpdate {
	_u.mutation.SetLifecycleState(v)
	return _u
}

// SetNillableLifecycleState sets the "lifecycle_state" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableLifecycleState(v *string) *InsightUpdate {
	if v != nil {
		_u.SetLifecycleState(*v)
	}
	return _u
}

// SetSupersededByID sets the "superseded_by_id" field.
func (_u *InsightUpdate) SetSupersededByID(v uuid.UUID) *InsightUpdate {
	_u.mutation.SetSupersededByID(v)
	return _u
}

// SetNillableSupersededByID sets the "superseded_by_id" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableSupersededByID(v *uuid.UUID) *InsightUpdate {
	if v != nil {
		_u.SetSupersededByID(*v)
	}
	return _u
}

// ClearSupersededByID clears the value of the "superseded_by_id" field.
func (_u *InsightUpdate) ClearSupersededByID() *InsightUpdate {
	_u.mutation.ClearSupersededByID()
	return _u
}

// SetLastConfirmedAt sets the "last_confirmed_at" field.
func (_u *InsightUpdate) SetLastConfirmedAt(v time.Time) *InsightUpdate {
	_u.mutation.SetLastConfirmedAt(v)
	return _u
}

// SetNillableLastConfirmedAt sets the "last_confirmed_at" field if the given value is not nil.
func (_u *InsightUpdate) SetNillableLastConfirmedAt(v *time.Time) *InsightUpdate {
	if v != nil {
		_u.SetLastConfirmedAt(*v)
	}
	return _u
}

// ClearLastConfirmedAt clears the value of the "last_confirmed_at" field.
func (_u *InsightUpdate) ClearLastConfirmedAt() *InsightUpdate {
	_u.mutation.ClearLastConfirmedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InsightUpdate) SetUpdatedAt(v time.Time) *InsightUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InsightMutation object of the builder.
func (_u *InsightUpdate) Mutation() *InsightMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InsightUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InsightUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InsightUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InsightUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InsightUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := insight.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InsightUpdate) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := insight.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "Insight.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := insight.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`postgres: validator failed for field "Insight.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Answer(); ok {
		if err := insight.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`postgres: validator failed for field "Insight.answer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceRunID(); ok {
		if err := insight.SourceRunIDValidator(v); err != nil {
			return &ValidationError{Name: "source_run_id", err: fmt.Errorf(`postgres: validator failed for field "Insight.source_run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReviewState(); ok {
		if err := insight.ReviewStateValidator(v); err != nil {
			return &ValidationError{Name: "review_state", err: fmt.Errorf(`postgres: validator failed for field "Insight.review_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifecycleState(); ok {
		if err := insight.LifecycleStateValidator(v); err != nil {
			return &ValidationError{Name: "lifecycle_state", err: fmt.Errorf(`postgres: validator failed for field "Insight.lifecycle_state": %w`, err)}
		}
	}
	return nil
}

func (_u *InsightUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(insight.Table, insight.Columns, sqlgraph.NewFieldSpec(insight.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(insight.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(insight.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Problem(); ok {
		_spec.SetField(insight.FieldProblem, field.TypeString, value)
	}
	if _u.mutation.ProblemCleared() {
		_spec.ClearField(insight.FieldProblem, field.TypeString)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(insight.FieldAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Example(); ok {
		_spec.SetField(insight.FieldExample, field.TypeJSON, value)
	}
	if _u.mutation.ExampleCleared() {
		_spec.ClearField(insight.FieldExample, field.TypeJSON)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(insight.FieldDetail, field.TypeString, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(insight.FieldDetail, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(insight.FieldAction, field.TypeString, value)
	}
	if _u.mutation.ActionCleared() {
		_spec.ClearField(insight.FieldAction, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(insight.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, insight.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(insight.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Links(); ok {
		_spec.SetField(insight.FieldLinks, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLinks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, insight.FieldLinks, value)
		})
	}
	if _u.mutation.LinksCleared() {
		_spec.ClearField(insight.FieldLinks, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedByActorID(); ok {
		_spec.SetField(insight.FieldCreatedByActorID, field.TypeUUID, value)
	}
	if _u.mutation.CreatedByActorIDCleared() {
		_spec.ClearField(insight.FieldCreatedByActorID, field.TypeUUID)
	}
	if value, ok := _u.mutation.SourceRunID(); ok {
		_spec.SetField(insight.FieldSourceRunID, field.TypeString, value)
	}
	if _u.mutation.SourceRunIDCleared() {
		_spec.ClearField(insight.FieldSourceRunID, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewState(); ok {
		_spec.SetField(insight.FieldReviewState, field.TypeString, value)
	}
	if value, ok := _u.mutation.LifecycleState(); ok {
		_spec.SetField(insight.FieldLifecycleState, field.TypeString, value)
	}
	if value, ok := _u.mutation.SupersededByID(); ok {
		_spec.SetField(insight.FieldSupersededByID, field.TypeUUID, value)
	}
	if _u.mutation.SupersededByIDCleared() {
		_spec.ClearField(insight.FieldSupersededByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.LastConfirmedAt(); ok {
		_spec.SetField(insight.FieldLastConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.LastConfirmedAtCleared() {
		_spec.ClearField(insight.FieldLastConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(insight.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{insight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InsightUpdateOne is the builder for updating a single Insight entity.
type InsightUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InsightMutation
}

// SetTenantKey sets the "tenant_key" field.
func (_u *InsightUpdateOne) SetTenantKey(v string) *InsightUpdateOne {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableTenantKey(v *string) *InsightUpdateOne {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InsightUpdateOne) SetTitle(v string) *InsightUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableTitle(v *string) *InsightUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetProblem sets the "problem" field.
func (_u *InsightUpdateOne) SetProblem(v string) *InsightUpdateOne {
	_u.mutation.SetProblem(v)
	return _u
}

// SetNillableProblem sets the "problem" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableProblem(v *string) *InsightUpdateOne {
	if v != nil {
		_u.SetProblem(*v)
	}
	return _u
}

// ClearProblem clears the value of the "problem" field.
func (_u *InsightUpdateOne) ClearProblem() *InsightUpdateOne {
	_u.mutation.ClearProblem()
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *InsightUpdateOne) SetAnswer(v string) *InsightUpdateOne {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableAnswer(v *string) *InsightUpdateOne {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// SetExample sets the "example" field.
func (_u *InsightUpdateOne) SetExample(v map[string]string) *InsightUpdateOne {
	_u.mutation.SetExample(v)
	return _u
}

// ClearExample clears the value of the "example" field.
func (_u *InsightUpdateOne) ClearExample() *InsightUpdateOne {
	_u.mutation.ClearExample()
	return _u
}

// SetDetail sets the "detail" field.
func (_u *InsightUpdateOne) SetDetail(v string) *InsightUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableDetail(v *string) *InsightUpdateOne {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *InsightUpdateOne) ClearDetail() *InsightUpdateOne {
	_u.mutation.ClearDetail()
	return _u
}

// SetAction sets the "action" field.
func (_u *InsightUpdateOne) SetAction(v string) *InsightUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableAction(v *string) *InsightUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// ClearAction clears the value of the "action" field.
func (_u *InsightUpdateOne) ClearAction() *InsightUpdateOne {
	_u.mutation.ClearAction()
	return _u
}

// SetTags sets the "tags" field.
func (_u *InsightUpdateOne) SetTags(v []string) *InsightUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *InsightUpdateOne) AppendTags(v []string) *InsightUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *InsightUpdateOne) ClearTags() *InsightUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetLinks sets the "links" field.
func (_u *InsightUpdateOne) SetLinks(v []map[string]string) *InsightUpdateOne {
	_u.mutation.SetLinks(v)
	return _u
}

// AppendLinks appends value to the "links" field.
func (_u *InsightUpdateOne) AppendLinks(v []map[string]string) *InsightUpdateOne {
	_u.mutation.AppendLinks(v)
	return _u
}

// ClearLinks clears the value of the "links" field.
func (_u *InsightUpdateOne) ClearLinks() *InsightUpdateOne {
	_u.mutation.ClearLinks()
	return _u
}

// SetCreatedByActorID sets the "created_by_actor_id" field.
func (_u *InsightUpdateOne) SetCreatedByActorID(v uuid.UUID) *InsightUpdateOne {
	_u.mutation.SetCreatedByActorID(v)
	return _u
}

// SetNillableCreatedByActorID sets the "created_by_actor_id" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableCreatedByActorID(v *uuid.UUID) *InsightUpdateOne {
	if v != nil {
		_u.SetCreatedByActorID(*v)
	}
	return _u
}

// ClearCreatedByActorID clears the value of the "created_by_actor_id" field.
func (_u *InsightUpdateOne) ClearCreatedByActorID() *InsightUpdateOne {
	_u.mutation.ClearCreatedByActorID()
	return _u
}

// SetSourceRunID sets the "source_run_id" field.
func (_u *InsightUpdateOne) SetSourceRunID(v string) *InsightUpdateOne {
	_u.mutation.SetSourceRunID(v)
	return _u
}

// SetNillableSourceRunID sets the "source_run_id" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableSourceRunID(v *string) *InsightUpdateOne {
	if v != nil {
		_u.SetSourceRunID(*v)
	}
	return _u
}

// ClearSourceRunID clears the value of the "source_run_id" field.
func (_u *InsightUpdateOne) ClearSourceRunID() *InsightUpdateOne {
	_u.mutation.ClearSourceRunID()
	return _u
}

// SetReviewState sets the "review_state" field.
func (_u *InsightUpdateOne) SetReviewState(v string) *InsightUpdateOne {
	_u.mutation.SetReviewState(v)
	return _u
}

// SetNillableReviewState sets the "review_state" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableReviewState(v *string) *InsightUpdateOne {
	if v != nil {
		_u.SetReviewState(*v)
	}
	return _u
}

// SetLifecycleState sets the "lifecycle_state" field.
func (_u *InsightUpdateOne) SetLifecycleState(v string) *InsightUpdateOne {
	_u.mutation.SetLifecycleState(v)
	return _u
}

// SetNillableLifecycleState sets the "lifecycle_state" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableLifecycleState(v *string) *InsightUpdateOne {
	if v != nil {
		_u.SetLifecycleState(*v)
	}
	return _u
}

// SetSupersededByID sets the "superseded_by_id" field.
func (_u *InsightUpdateOne) SetSupersededByID(v uuid.UUID) *InsightUpdateOne {
	_u.mutation.SetSupersededByID(v)
	return _u
}

// SetNillableSupersededByID sets the "superseded_by_id" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableSupersededByID(v *uuid.UUID) *InsightUpdateOne {
	if v != nil {
		_u.SetSupersededByID(*v)
	}
	return _u
}

// ClearSupersededByID clears the value of the "superseded_by_id" field.
func (_u *InsightUpdateOne) ClearSupersededByID() *InsightUpdateOne {
	_u.mutation.ClearSupersededByID()
	return _u
}

// SetLastConfirmedAt sets the "last_confirmed_at" field.
func (_u *InsightUpdateOne) SetLastConfirmedAt(v time.Time) *InsightUpdateOne {
	_u.mutation.SetLastConfirmedAt(v)
	return _u
}

// SetNillableLastConfirmedAt sets the "last_confirmed_at" field if the given value is not nil.
func (_u *InsightUpdateOne) SetNillableLastConfirmedAt(v *time.Time) *InsightUpdateOne {
	if v != nil {
		_u.SetLastConfirmedAt(*v)
	}
	return _u
}

// ClearLastConfirmedAt clears the value of the "last_confirmed_at" field.
func (_u *InsightUpdateOne) ClearLastConfirmedAt() *InsightUpdateOne {
	_u.mutation.ClearLastConfirmedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InsightUpdateOne) SetUpdatedAt(v time.Time) *InsightUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InsightMutation object of the builder.
func (_u *InsightUpdateOne) Mutation() *InsightMutation {
	return _u.mutation
}

// Where appends a list predicates to the InsightUpdate builder.
func (_u *InsightUpdateOne) Where(ps ...predicate.Insight) *InsightUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InsightUpdateOne) Select(field string, fields ...string) *InsightUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Insight entity.
func (_u *InsightUpdateOne) Save(ctx context.Context) (*Insight, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InsightUpdateOne) SaveX(ctx context.Context) *Insight {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InsightUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InsightUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InsightUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := insight.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InsightUpdateOne) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := insight.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "Insight.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := insight.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`postgres: validator failed for field "Insight.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Answer(); ok {
		if err := insight.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`postgres: validator failed for field "Insight.answer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceRunID(); ok {
		if err := insight.SourceRunIDValidator(v); err != nil {
			return &ValidationError{Name: "source_run_id", err: fmt.Errorf(`postgres: validator failed for field "Insight.source_run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReviewState(); ok {
		if err := insight.ReviewStateValidator(v); err != nil {
			return &ValidationError{Name: "review_state", err: fmt.Errorf(`postgres: validator failed for field "Insight.review_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifecycleState(); ok {
		if err := insight.LifecycleStateValidator(v); err != nil {
			return &ValidationError{Name: "lifecycle_state", err: fmt.Errorf(`postgres: validator failed for field "Insight.lifecycle_state": %w`, err)}
		}
	}
	return nil
}

func (_u *InsightUpdateOne) sqlSave(ctx context.Context) (_node *Insight, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(insight.Table, insight.Columns, sqlgraph.NewFieldSpec(insight.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`postgres: missing "Insight.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, insight.FieldID)
		for _, f := range fields {
			if !insight.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("postgres: invalid field %q for query", f)}
			}
			if f != insight.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(insight.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(insight.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Problem(); ok {
		_spec.SetField(insight.FieldProblem, field.TypeString, value)
	}
	if _u.mutation.ProblemCleared() {
		_spec.ClearField(insight.FieldProblem, field.TypeString)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(insight.FieldAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Example(); ok {
		_spec.SetField(insight.FieldExample, field.TypeJSON, value)
	}
	if _u.mutation.ExampleCleared() {
		_spec.ClearField(insight.FieldExample, field.TypeJSON)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(insight.FieldDetail, field.TypeString, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(insight.FieldDetail, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(insight.FieldAction, field.TypeString, value)
	}
	if _u.mutation.ActionCleared() {
		_spec.ClearField(insight.FieldAction, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(insight.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, insight.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(insight.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Links(); ok {
		_spec.SetField(insight.FieldLinks, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLinks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, insight.FieldLinks, value)
		})
	}
	if _u.mutation.LinksCleared() {
		_spec.ClearField(insight.FieldLinks, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedByActorID(); ok {
		_spec.SetField(insight.FieldCreatedByActorID, field.TypeUUID, value)
	}
	if _u.mutation.CreatedByActorIDCleared() {
		_spec.ClearField(insight.FieldCreatedByActorID, field.TypeUUID)
	}
	if value, ok := _u.mutation.SourceRunID(); ok {
		_spec.SetField(insight.FieldSourceRunID, field.TypeString, value)
	}
	if _u.mutation.SourceRunIDCleared() {
		_spec.ClearField(insight.FieldSourceRunID, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewState(); ok {
		_spec.SetField(insight.FieldReviewState, field.TypeString, value)
	}
	if value, ok := _u.mutation.LifecycleState(); ok {
		_spec.SetField(insight.FieldLifecycleState, field.TypeString, value)
	}
	if value, ok := _u.mutation.SupersededByID(); ok {
		_spec.SetField(insight.FieldSupersededByID, field.TypeUUID, value)
	}
	if _u.mutation.SupersededByIDCleared() {
		_spec.ClearField(insight.FieldSupersededByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.LastConfirmedAt(); ok {
		_spec.SetField(insight.FieldLastConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.LastConfirmedAtCleared() {
		_spec.ClearField(insight.FieldLastConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(insight.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Insight{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{insight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
