// Code generated by ent, DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loewenthal-corp/consensus/internal/postgres/job"
	"github.com/loewenthal-corp/consensus/internal/postgres/predicate"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantKey sets the "tenant_key" field.
func (_u *JobUpdate) SetTenantKey(v string) *JobUpdate {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *JobUpdate) SetNillableTenantKey(v *string) *JobUpdate {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *JobUpdate) SetKind(v string) *JobUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *JobUpdate) SetNillableKind(v *string) *JobUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdate) SetStatus(v string) *JobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdate) SetNillableStatus(v *string) *JobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *JobUpdate) SetPayload(v map[string]string) *JobUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *JobUpdate) ClearPayload() *JobUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *JobUpdate) SetLastError(v string) *JobUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *JobUpdate) SetNillableLastError(v *string) *JobUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *JobUpdate) ClearLastError() *JobUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *JobUpdate) SetAttempts(v int) *JobUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *JobUpdate) SetNillableAttempts(v *int) *JobUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *JobUpdate) AddAttempts(v int) *JobUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetRunAt sets the "run_at" field.
func (_u *JobUpdate) SetRunAt(v time.Time) *JobUpdate {
	_u.mutation.SetRunAt(v)
	return _u
}

// SetNillableRunAt sets the "run_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableRunAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetRunAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JobUpdate) SetUpdatedAt(v time.Time) *JobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdate) Mutation() *JobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := job.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdate) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := job.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "Job.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := job.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`postgres: validator failed for field "Job.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`postgres: validator failed for field "Job.status": %w`, err)}
		}
	}
	return nil
}

func (_u *JobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(job.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(job.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(job.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(job.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(job.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RunAt(); ok {
		_spec.SetField(job.FieldRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetTenantKey sets the "tenant_key" field.
func (_u *JobUpdateOne) SetTenantKey(v string) *JobUpdateOne {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableTenantKey(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *JobUpdateOne) SetKind(v string) *JobUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableKind(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdateOne) SetStatus(v string) *JobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableStatus(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *JobUpdateOne) SetPayload(v map[string]string) *JobUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *JobUpdateOne) ClearPayload() *JobUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *JobUpdateOne) SetLastError(v string) *JobUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableLastError(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *JobUpdateOne) ClearLastError() *JobUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *JobUpdateOne) SetAttempts(v int) *JobUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableAttempts(v *int) *JobUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *JobUpdateOne) AddAttempts(v int) *JobUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetRunAt sets the "run_at" field.
func (_u *JobUpdateOne) SetRunAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetRunAt(v)
	return _u
}

// SetNillableRunAt sets the "run_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableRunAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetRunAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JobUpdateOne) SetUpdatedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdateOne) Mutation() *JobMutation {
	return _u.mutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Job entity.
func (_u *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := job.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdateOne) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := job.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "Job.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := job.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`postgres: validator failed for field "Job.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`postgres: validator failed for field "Job.status": %w`, err)}
		}
	}
	return nil
}

func (_u *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`postgres: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("postgres: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(job.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(job.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(job.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(job.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(job.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RunAt(); ok {
		_spec.SetField(job.FieldRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Job{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
