// Code generated by ent, DO NOT EDIT.

package postgres

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/problemfingerprint"
)

// ProblemFingerprint is the model entity for the ProblemFingerprint schema.
type ProblemFingerprint struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantKey holds the value of the "tenant_key" field.
	TenantKey string `json:"tenant_key,omitempty"`
	// KnowledgeUnitID holds the value of the "knowledge_unit_id" field.
	KnowledgeUnitID uuid.UUID `json:"knowledge_unit_id,omitempty"`
	// ErrorHash holds the value of the "error_hash" field.
	ErrorHash string `json:"error_hash,omitempty"`
	// Command holds the value of the "command" field.
	Command string `json:"command,omitempty"`
	// Toolchain holds the value of the "toolchain" field.
	Toolchain string `json:"toolchain,omitempty"`
	// Service holds the value of the "service" field.
	Service string `json:"service,omitempty"`
	// RepoPathPattern holds the value of the "repo_path_pattern" field.
	RepoPathPattern string `json:"repo_path_pattern,omitempty"`
	// Environment holds the value of the "environment" field.
	Environment string `json:"environment,omitempty"`
	// DependencyVersions holds the value of the "dependency_versions" field.
	DependencyVersions map[string]string `json:"dependency_versions,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProblemFingerprint) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case problemfingerprint.FieldDependencyVersions:
			values[i] = new([]byte)
		case problemfingerprint.FieldTenantKey, problemfingerprint.FieldErrorHash, problemfingerprint.FieldCommand, problemfingerprint.FieldToolchain, problemfingerprint.FieldService, problemfingerprint.FieldRepoPathPattern, problemfingerprint.FieldEnvironment:
			values[i] = new(sql.NullString)
		case problemfingerprint.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case problemfingerprint.FieldID, problemfingerprint.FieldKnowledgeUnitID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProblemFingerprint fields.
func (_m *ProblemFingerprint) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case problemfingerprint.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case problemfingerprint.FieldTenantKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_key", values[i])
			} else if value.Valid {
				_m.TenantKey = value.String
			}
		case problemfingerprint.FieldKnowledgeUnitID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field knowledge_unit_id", values[i])
			} else if value != nil {
				_m.KnowledgeUnitID = *value
			}
		case problemfingerprint.FieldErrorHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_hash", values[i])
			} else if value.Valid {
				_m.ErrorHash = value.String
			}
		case problemfingerprint.FieldCommand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field command", values[i])
			} else if value.Valid {
				_m.Command = value.String
			}
		case problemfingerprint.FieldToolchain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field toolchain", values[i])
			} else if value.Valid {
				_m.Toolchain = value.String
			}
		case problemfingerprint.FieldService:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service", values[i])
			} else if value.Valid {
				_m.Service = value.String
			}
		case problemfingerprint.FieldRepoPathPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_path_pattern", values[i])
			} else if value.Valid {
				_m.RepoPathPattern = value.String
			}
		case problemfingerprint.FieldEnvironment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment", values[i])
			} else if value.Valid {
				_m.Environment = value.String
			}
		case problemfingerprint.FieldDependencyVersions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field dependency_versions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DependencyVersions); err != nil {
					return fmt.Errorf("unmarshal field dependency_versions: %w", err)
				}
			}
		case problemfingerprint.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProblemFingerprint.
// This includes values selected through modifiers, order, etc.
func (_m *ProblemFingerprint) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProblemFingerprint.
// Note that you need to call ProblemFingerprint.Unwrap() before calling this method if this ProblemFingerprint
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProblemFingerprint) Update() *ProblemFingerprintUpdateOne {
	return NewProblemFingerprintClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProblemFingerprint entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProblemFingerprint) Unwrap() *ProblemFingerprint {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("postgres: ProblemFingerprint is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProblemFingerprint) String() string {
	var builder strings.Builder
	builder.WriteString("ProblemFingerprint(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_key=")
	builder.WriteString(_m.TenantKey)
	builder.WriteString(", ")
	builder.WriteString("knowledge_unit_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.KnowledgeUnitID))
	builder.WriteString(", ")
	builder.WriteString("error_hash=")
	builder.WriteString(_m.ErrorHash)
	builder.WriteString(", ")
	builder.WriteString("command=")
	builder.WriteString(_m.Command)
	builder.WriteString(", ")
	builder.WriteString("toolchain=")
	builder.WriteString(_m.Toolchain)
	builder.WriteString(", ")
	builder.WriteString("service=")
	builder.WriteString(_m.Service)
	builder.WriteString(", ")
	builder.WriteString("repo_path_pattern=")
	builder.WriteString(_m.RepoPathPattern)
	builder.WriteString(", ")
	builder.WriteString("environment=")
	builder.WriteString(_m.Environment)
	builder.WriteString(", ")
	builder.WriteString("dependency_versions=")
	builder.WriteString(fmt.Sprintf("%v", _m.DependencyVersions))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProblemFingerprints is a parsable slice of ProblemFingerprint.
type ProblemFingerprints []*ProblemFingerprint
