// Code generated by ent, DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/predicate"
	"github.com/loewenthal-corp/consensus/internal/postgres/problemfingerprint"
)

// ProblemFingerprintUpdate is the builder for updating ProblemFingerprint entities.
type ProblemFingerprintUpdate struct {
	config
	hooks    []Hook
	mutation *ProblemFingerprintMutation
}

// Where appends a list predicates to the ProblemFingerprintUpdate builder.
func (_u *ProblemFingerprintUpdate) Where(ps ...predicate.ProblemFingerprint) *ProblemFingerprintUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantKey sets the "tenant_key" field.
func (_u *ProblemFingerprintUpdate) SetTenantKey(v string) *ProblemFingerprintUpdate {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *ProblemFingerprintUpdate) SetNillableTenantKey(v *string) *ProblemFingerprintUpdate {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetInsightID sets the "insight_id" field.
func (_u *ProblemFingerprintUpdate) SetInsightID(v uuid.UUID) *ProblemFingerprintUpdate {
	_u.mutation.SetInsightID(v)
	return _u
}

// SetNillableInsightID sets the "insight_id" field if the given value is not nil.
func (_u *ProblemFingerprintUpdate) SetNillableInsightID(v *uuid.UUID) *ProblemFingerprintUpdate {
	if v != nil {
		_u.SetInsightID(*v)
	}
	return _u
}

// SetErrorHash sets the "error_hash" field.
func (_u *ProblemFingerprintUpdate) SetErrorHash(v string) *ProblemFingerprintUpdate {
	_u.mutation.SetErrorHash(v)
	return _u
}

// SetNillableErrorHash sets the "error_hash" field if the given value is not nil.
func (_u *ProblemFingerprintUpdate) SetNillableErrorHash(v *string) *ProblemFingerprintUpdate {
	if v != nil {
		_u.SetErrorHash(*v)
	}
	return _u
}

// ClearErrorHash clears the value of the "error_hash" field.
func (_u *ProblemFingerprintUpdate) ClearErrorHash() *ProblemFingerprintUpdate {
	_u.mutation.ClearErrorHash()
	return _u
}

// SetCommand sets the "command" field.
func (_u *ProblemFingerprintUpdate) SetCommand(v string) *ProblemFingerprintUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *ProblemFingerprintUpdate) SetNillableCommand(v *string) *ProblemFingerprintUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *ProblemFingerprintUpdate) ClearCommand() *ProblemFingerprintUpdate {
	_u.mutation.ClearCommand()
	return _u
}

// SetToolchain sets the "toolchain" field.
func (_u *ProblemFingerprintUpdate) SetToolchain(v string) *ProblemFingerprintUpdate {
	_u.mutation.SetToolchain(v)
	return _u
}

// SetNillableToolchain sets the "toolchain" field if the given value is not nil.
func (_u *ProblemFingerprintUpdate) SetNillableToolchain(v *string) *ProblemFingerprintUpdate {
	if v != nil {
		_u.SetToolchain(*v)
	}
	return _u
}

// ClearToolchain clears the value of the "toolchain" field.
func (_u *ProblemFingerprintUpdate) ClearToolchain() *ProblemFingerprintUpdate {
	_u.mutation.ClearToolchain()
	return _u
}

// SetService sets the "service" field.
func (_u *ProblemFingerprintUpdate) SetService(v string) *ProblemFingerprintUpdate {
	_u.mutation.SetService(v)
	return _u
}

// SetNillableService sets the "service" field if the given value is not nil.
func (_u *ProblemFingerprintUpdate) SetNillableService(v *string) *ProblemFingerprintUpdate {
	if v != nil {
		_u.SetService(*v)
	}
	return _u
}

// ClearService clears the value of the "service" field.
func (_u *ProblemFingerprintUpdate) ClearService() *ProblemFingerprintUpdate {
	_u.mutation.ClearService()
	return _u
}

// SetRepoPathPattern sets the "repo_path_pattern" field.
func (_u *ProblemFingerprintUpdate) SetRepoPathPattern(v string) *ProblemFingerprintUpdate {
	_u.mutation.SetRepoPathPattern(v)
	return _u
}

// SetNillableRepoPathPattern sets the "repo_path_pattern" field if the given value is not nil.
func (_u *ProblemFingerprintUpdate) SetNillableRepoPathPattern(v *string) *ProblemFingerprintUpdate {
	if v != nil {
		_u.SetRepoPathPattern(*v)
	}
	return _u
}

// ClearRepoPathPattern clears the value of the "repo_path_pattern" field.
func (_u *ProblemFingerprintUpdate) ClearRepoPathPattern() *ProblemFingerprintUpdate {
	_u.mutation.ClearRepoPathPattern()
	return _u
}

// SetEnvironment sets the "environment" field.
func (_u *ProblemFingerprintUpdate) SetEnvironment(v string) *ProblemFingerprintUpdate {
	_u.mutation.SetEnvironment(v)
	return _u
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (_u *ProblemFingerprintUpdate) SetNillableEnvironment(v *string) *ProblemFingerprintUpdate {
	if v != nil {
		_u.SetEnvironment(*v)
	}
	return _u
}

// ClearEnvironment clears the value of the "environment" field.
func (_u *ProblemFingerprintUpdate) ClearEnvironment() *ProblemFingerprintUpdate {
	_u.mutation.ClearEnvironment()
	return _u
}

// SetDependencyVersions sets the "dependency_versions" field.
func (_u *ProblemFingerprintUpdate) SetDependencyVersions(v map[string]string) *ProblemFingerprintUpdate {
	_u.mutation.SetDependencyVersions(v)
	return _u
}

// ClearDependencyVersions clears the value of the "dependency_versions" field.
func (_u *ProblemFingerprintUpdate) ClearDependencyVersions() *ProblemFingerprintUpdate {
	_u.mutation.ClearDependencyVersions()
	return _u
}

// Mutation returns the ProblemFingerprintMutation object of the builder.
func (_u *ProblemFingerprintUpdate) Mutation() *ProblemFingerprintMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProblemFingerprintUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProblemFingerprintUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProblemFingerprintUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProblemFingerprintUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProblemFingerprintUpdate) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := problemfingerprint.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorHash(); ok {
		if err := problemfingerprint.ErrorHashValidator(v); err != nil {
			return &ValidationError{Name: "error_hash", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.error_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Command(); ok {
		if err := problemfingerprint.CommandValidator(v); err != nil {
			return &ValidationError{Name: "command", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.command": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Toolchain(); ok {
		if err := problemfingerprint.ToolchainValidator(v); err != nil {
			return &ValidationError{Name: "toolchain", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.toolchain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Service(); ok {
		if err := problemfingerprint.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.service": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoPathPattern(); ok {
		if err := problemfingerprint.RepoPathPatternValidator(v); err != nil {
			return &ValidationError{Name: "repo_path_pattern", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.repo_path_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Environment(); ok {
		if err := problemfingerprint.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.environment": %w`, err)}
		}
	}
	return nil
}

func (_u *ProblemFingerprintUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(problemfingerprint.Table, problemfingerprint.Columns, sqlgraph.NewFieldSpec(problemfingerprint.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(problemfingerprint.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.InsightID(); ok {
		_spec.SetField(problemfingerprint.FieldInsightID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ErrorHash(); ok {
		_spec.SetField(problemfingerprint.FieldErrorHash, field.TypeString, value)
	}
	if _u.mutation.ErrorHashCleared() {
		_spec.ClearField(problemfingerprint.FieldErrorHash, field.TypeString)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(problemfingerprint.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(problemfingerprint.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.Toolchain(); ok {
		_spec.SetField(problemfingerprint.FieldToolchain, field.TypeString, value)
	}
	if _u.mutation.ToolchainCleared() {
		_spec.ClearField(problemfingerprint.FieldToolchain, field.TypeString)
	}
	if value, ok := _u.mutation.Service(); ok {
		_spec.SetField(problemfingerprint.FieldService, field.TypeString, value)
	}
	if _u.mutation.ServiceCleared() {
		_spec.ClearField(problemfingerprint.FieldService, field.TypeString)
	}
	if value, ok := _u.mutation.RepoPathPattern(); ok {
		_spec.SetField(problemfingerprint.FieldRepoPathPattern, field.TypeString, value)
	}
	if _u.mutation.RepoPathPatternCleared() {
		_spec.ClearField(problemfingerprint.FieldRepoPathPattern, field.TypeString)
	}
	if value, ok := _u.mutation.Environment(); ok {
		_spec.SetField(problemfingerprint.FieldEnvironment, field.TypeString, value)
	}
	if _u.mutation.EnvironmentCleared() {
		_spec.ClearField(problemfingerprint.FieldEnvironment, field.TypeString)
	}
	if value, ok := _u.mutation.DependencyVersions(); ok {
		_spec.SetField(problemfingerprint.FieldDependencyVersions, field.TypeJSON, value)
	}
	if _u.mutation.DependencyVersionsCleared() {
		_spec.ClearField(problemfingerprint.FieldDependencyVersions, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problemfingerprint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProblemFingerprintUpdateOne is the builder for updating a single ProblemFingerprint entity.
type ProblemFingerprintUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProblemFingerprintMutation
}

// SetTenantKey sets the "tenant_key" field.
func (_u *ProblemFingerprintUpdateOne) SetTenantKey(v string) *ProblemFingerprintUpdateOne {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *ProblemFingerprintUpdateOne) SetNillableTenantKey(v *string) *ProblemFingerprintUpdateOne {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetInsightID sets the "insight_id" field.
func (_u *ProblemFingerprintUpdateOne) SetInsightID(v uuid.UUID) *ProblemFingerprintUpdateOne {
	_u.mutation.SetInsightID(v)
	return _u
}

// SetNillableInsightID sets the "insight_id" field if the given value is not nil.
func (_u *ProblemFingerprintUpdateOne) SetNillableInsightID(v *uuid.UUID) *ProblemFingerprintUpdateOne {
	if v != nil {
		_u.SetInsightID(*v)
	}
	return _u
}

// SetErrorHash sets the "error_hash" field.
func (_u *ProblemFingerprintUpdateOne) SetErrorHash(v string) *ProblemFingerprintUpdateOne {
	_u.mutation.SetErrorHash(v)
	return _u
}

// SetNillableErrorHash sets the "error_hash" field if the given value is not nil.
func (_u *ProblemFingerprintUpdateOne) SetNillableErrorHash(v *string) *ProblemFingerprintUpdateOne {
	if v != nil {
		_u.SetErrorHash(*v)
	}
	return _u
}

// ClearErrorHash clears the value of the "error_hash" field.
func (_u *ProblemFingerprintUpdateOne) ClearErrorHash() *ProblemFingerprintUpdateOne {
	_u.mutation.ClearErrorHash()
	return _u
}

// SetCommand sets the "command" field.
func (_u *ProblemFingerprintUpdateOne) SetCommand(v string) *ProblemFingerprintUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *ProblemFingerprintUpdateOne) SetNillableCommand(v *string) *ProblemFingerprintUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *ProblemFingerprintUpdateOne) ClearCommand() *ProblemFingerprintUpdateOne {
	_u.mutation.ClearCommand()
	return _u
}

// SetToolchain sets the "toolchain" field.
func (_u *ProblemFingerprintUpdateOne) SetToolchain(v string) *ProblemFingerprintUpdateOne {
	_u.mutation.SetToolchain(v)
	return _u
}

// SetNillableToolchain sets the "toolchain" field if the given value is not nil.
func (_u *ProblemFingerprintUpdateOne) SetNillableToolchain(v *string) *ProblemFingerprintUpdateOne {
	if v != nil {
		_u.SetToolchain(*v)
	}
	return _u
}

// ClearToolchain clears the value of the "toolchain" field.
func (_u *ProblemFingerprintUpdateOne) ClearToolchain() *ProblemFingerprintUpdateOne {
	_u.mutation.ClearToolchain()
	return _u
}

// SetService sets the "service" field.
func (_u *ProblemFingerprintUpdateOne) SetService(v string) *ProblemFingerprintUpdateOne {
	_u.mutation.SetService(v)
	return _u
}

// SetNillableService sets the "service" field if the given value is not nil.
func (_u *ProblemFingerprintUpdateOne) SetNillableService(v *string) *ProblemFingerprintUpdateOne {
	if v != nil {
		_u.SetService(*v)
	}
	return _u
}

// ClearService clears the value of the "service" field.
func (_u *ProblemFingerprintUpdateOne) ClearService() *ProblemFingerprintUpdateOne {
	_u.mutation.ClearService()
	return _u
}

// SetRepoPathPattern sets the "repo_path_pattern" field.
func (_u *ProblemFingerprintUpdateOne) SetRepoPathPattern(v string) *ProblemFingerprintUpdateOne {
	_u.mutation.SetRepoPathPattern(v)
	return _u
}

// SetNillableRepoPathPattern sets the "repo_path_pattern" field if the given value is not nil.
func (_u *ProblemFingerprintUpdateOne) SetNillableRepoPathPattern(v *string) *ProblemFingerprintUpdateOne {
	if v != nil {
		_u.SetRepoPathPattern(*v)
	}
	return _u
}

// ClearRepoPathPattern clears the value of the "repo_path_pattern" field.
func (_u *ProblemFingerprintUpdateOne) ClearRepoPathPattern() *ProblemFingerprintUpdateOne {
	_u.mutation.ClearRepoPathPattern()
	return _u
}

// SetEnvironment sets the "environment" field.
func (_u *ProblemFingerprintUpdateOne) SetEnvironment(v string) *ProblemFingerprintUpdateOne {
	_u.mutation.SetEnvironment(v)
	return _u
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (_u *ProblemFingerprintUpdateOne) SetNillableEnvironment(v *string) *ProblemFingerprintUpdateOne {
	if v != nil {
		_u.SetEnvironment(*v)
	}
	return _u
}

// ClearEnvironment clears the value of the "environment" field.
func (_u *ProblemFingerprintUpdateOne) ClearEnvironment() *ProblemFingerprintUpdateOne {
	_u.mutation.ClearEnvironment()
	return _u
}

// SetDependencyVersions sets the "dependency_versions" field.
func (_u *ProblemFingerprintUpdateOne) SetDependencyVersions(v map[string]string) *ProblemFingerprintUpdateOne {
	_u.mutation.SetDependencyVersions(v)
	return _u
}

// ClearDependencyVersions clears the value of the "dependency_versions" field.
func (_u *ProblemFingerprintUpdateOne) ClearDependencyVersions() *ProblemFingerprintUpdateOne {
	_u.mutation.ClearDependencyVersions()
	return _u
}

// Mutation returns the ProblemFingerprintMutation object of the builder.
func (_u *ProblemFingerprintUpdateOne) Mutation() *ProblemFingerprintMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProblemFingerprintUpdate builder.
func (_u *ProblemFingerprintUpdateOne) Where(ps ...predicate.ProblemFingerprint) *ProblemFingerprintUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProblemFingerprintUpdateOne) Select(field string, fields ...string) *ProblemFingerprintUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProblemFingerprint entity.
func (_u *ProblemFingerprintUpdateOne) Save(ctx context.Context) (*ProblemFingerprint, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProblemFingerprintUpdateOne) SaveX(ctx context.Context) *ProblemFingerprint {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProblemFingerprintUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProblemFingerprintUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProblemFingerprintUpdateOne) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := problemfingerprint.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorHash(); ok {
		if err := problemfingerprint.ErrorHashValidator(v); err != nil {
			return &ValidationError{Name: "error_hash", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.error_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Command(); ok {
		if err := problemfingerprint.CommandValidator(v); err != nil {
			return &ValidationError{Name: "command", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.command": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Toolchain(); ok {
		if err := problemfingerprint.ToolchainValidator(v); err != nil {
			return &ValidationError{Name: "toolchain", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.toolchain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Service(); ok {
		if err := problemfingerprint.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.service": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoPathPattern(); ok {
		if err := problemfingerprint.RepoPathPatternValidator(v); err != nil {
			return &ValidationError{Name: "repo_path_pattern", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.repo_path_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Environment(); ok {
		if err := problemfingerprint.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.environment": %w`, err)}
		}
	}
	return nil
}

func (_u *ProblemFingerprintUpdateOne) sqlSave(ctx context.Context) (_node *ProblemFingerprint, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(problemfingerprint.Table, problemfingerprint.Columns, sqlgraph.NewFieldSpec(problemfingerprint.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`postgres: missing "ProblemFingerprint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, problemfingerprint.FieldID)
		for _, f := range fields {
			if !problemfingerprint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("postgres: invalid field %q for query", f)}
			}
			if f != problemfingerprint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(problemfingerprint.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.InsightID(); ok {
		_spec.SetField(problemfingerprint.FieldInsightID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ErrorHash(); ok {
		_spec.SetField(problemfingerprint.FieldErrorHash, field.TypeString, value)
	}
	if _u.mutation.ErrorHashCleared() {
		_spec.ClearField(problemfingerprint.FieldErrorHash, field.TypeString)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(problemfingerprint.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(problemfingerprint.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.Toolchain(); ok {
		_spec.SetField(problemfingerprint.FieldToolchain, field.TypeString, value)
	}
	if _u.mutation.ToolchainCleared() {
		_spec.ClearField(problemfingerprint.FieldToolchain, field.TypeString)
	}
	if value, ok := _u.mutation.Service(); ok {
		_spec.SetField(problemfingerprint.FieldService, field.TypeString, value)
	}
	if _u.mutation.ServiceCleared() {
		_spec.ClearField(problemfingerprint.FieldService, field.TypeString)
	}
	if value, ok := _u.mutation.RepoPathPattern(); ok {
		_spec.SetField(problemfingerprint.FieldRepoPathPattern, field.TypeString, value)
	}
	if _u.mutation.RepoPathPatternCleared() {
		_spec.ClearField(problemfingerprint.FieldRepoPathPattern, field.TypeString)
	}
	if value, ok := _u.mutation.Environment(); ok {
		_spec.SetField(problemfingerprint.FieldEnvironment, field.TypeString, value)
	}
	if _u.mutation.EnvironmentCleared() {
		_spec.ClearField(problemfingerprint.FieldEnvironment, field.TypeString)
	}
	if value, ok := _u.mutation.DependencyVersions(); ok {
		_spec.SetField(problemfingerprint.FieldDependencyVersions, field.TypeJSON, value)
	}
	if _u.mutation.DependencyVersionsCleared() {
		_spec.ClearField(problemfingerprint.FieldDependencyVersions, field.TypeJSON)
	}
	_node = &ProblemFingerprint{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problemfingerprint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
