// Code generated by ent, DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/problemfingerprint"
)

// ProblemFingerprintCreate is the builder for creating a ProblemFingerprint entity.
type ProblemFingerprintCreate struct {
	config
	mutation *ProblemFingerprintMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantKey sets the "tenant_key" field.
func (_c *ProblemFingerprintCreate) SetTenantKey(v string) *ProblemFingerprintCreate {
	_c.mutation.SetTenantKey(v)
	return _c
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_c *ProblemFingerprintCreate) SetNillableTenantKey(v *string) *ProblemFingerprintCreate {
	if v != nil {
		_c.SetTenantKey(*v)
	}
	return _c
}

// SetInsightID sets the "insight_id" field.
func (_c *ProblemFingerprintCreate) SetInsightID(v uuid.UUID) *ProblemFingerprintCreate {
	_c.mutation.SetInsightID(v)
	return _c
}

// SetErrorHash sets the "error_hash" field.
func (_c *ProblemFingerprintCreate) SetErrorHash(v string) *ProblemFingerprintCreate {
	_c.mutation.SetErrorHash(v)
	return _c
}

// SetNillableErrorHash sets the "error_hash" field if the given value is not nil.
func (_c *ProblemFingerprintCreate) SetNillableErrorHash(v *string) *ProblemFingerprintCreate {
	if v != nil {
		_c.SetErrorHash(*v)
	}
	return _c
}

// SetCommand sets the "command" field.
func (_c *ProblemFingerprintCreate) SetCommand(v string) *ProblemFingerprintCreate {
	_c.mutation.SetCommand(v)
	return _c
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_c *ProblemFingerprintCreate) SetNillableCommand(v *string) *ProblemFingerprintCreate {
	if v != nil {
		_c.SetCommand(*v)
	}
	return _c
}

// SetToolchain sets the "toolchain" field.
func (_c *ProblemFingerprintCreate) SetToolchain(v string) *ProblemFingerprintCreate {
	_c.mutation.SetToolchain(v)
	return _c
}

// SetNillableToolchain sets the "toolchain" field if the given value is not nil.
func (_c *ProblemFingerprintCreate) SetNillableToolchain(v *string) *ProblemFingerprintCreate {
	if v != nil {
		_c.SetToolchain(*v)
	}
	return _c
}

// SetService sets the "service" field.
func (_c *ProblemFingerprintCreate) SetService(v string) *ProblemFingerprintCreate {
	_c.mutation.SetService(v)
	return _c
}

// SetNillableService sets the "service" field if the given value is not nil.
func (_c *ProblemFingerprintCreate) SetNillableService(v *string) *ProblemFingerprintCreate {
	if v != nil {
		_c.SetService(*v)
	}
	return _c
}

// SetRepoPathPattern sets the "repo_path_pattern" field.
func (_c *ProblemFingerprintCreate) SetRepoPathPattern(v string) *ProblemFingerprintCreate {
	_c.mutation.SetRepoPathPattern(v)
	return _c
}

// SetNillableRepoPathPattern sets the "repo_path_pattern" field if the given value is not nil.
func (_c *ProblemFingerprintCreate) SetNillableRepoPathPattern(v *string) *ProblemFingerprintCreate {
	if v != nil {
		_c.SetRepoPathPattern(*v)
	}
	return _c
}

// SetEnvironment sets the "environment" field.
func (_c *ProblemFingerprintCreate) SetEnvironment(v string) *ProblemFingerprintCreate {
	_c.mutation.SetEnvironment(v)
	return _c
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (_c *ProblemFingerprintCreate) SetNillableEnvironment(v *string) *ProblemFingerprintCreate {
	if v != nil {
		_c.SetEnvironment(*v)
	}
	return _c
}

// SetDependencyVersions sets the "dependency_versions" field.
func (_c *ProblemFingerprintCreate) SetDependencyVersions(v map[string]string) *ProblemFingerprintCreate {
	_c.mutation.SetDependencyVersions(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProblemFingerprintCreate) SetCreatedAt(v time.Time) *ProblemFingerprintCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProblemFingerprintCreate) SetNillableCreatedAt(v *time.Time) *ProblemFingerprintCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProblemFingerprintCreate) SetID(v uuid.UUID) *ProblemFingerprintCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProblemFingerprintCreate) SetNillableID(v *uuid.UUID) *ProblemFingerprintCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ProblemFingerprintMutation object of the builder.
func (_c *ProblemFingerprintCreate) Mutation() *ProblemFingerprintMutation {
	return _c.mutation
}

// Save creates the ProblemFingerprint in the database.
func (_c *ProblemFingerprintCreate) Save(ctx context.Context) (*ProblemFingerprint, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProblemFingerprintCreate) SaveX(ctx context.Context) *ProblemFingerprint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProblemFingerprintCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProblemFingerprintCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProblemFingerprintCreate) defaults() {
	if _, ok := _c.mutation.TenantKey(); !ok {
		v := problemfingerprint.DefaultTenantKey
		_c.mutation.SetTenantKey(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := problemfingerprint.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := problemfingerprint.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProblemFingerprintCreate) check() error {
	if _, ok := _c.mutation.TenantKey(); !ok {
		return &ValidationError{Name: "tenant_key", err: errors.New(`postgres: missing required field "ProblemFingerprint.tenant_key"`)}
	}
	if v, ok := _c.mutation.TenantKey(); ok {
		if err := problemfingerprint.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.tenant_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InsightID(); !ok {
		return &ValidationError{Name: "insight_id", err: errors.New(`postgres: missing required field "ProblemFingerprint.insight_id"`)}
	}
	if v, ok := _c.mutation.ErrorHash(); ok {
		if err := problemfingerprint.ErrorHashValidator(v); err != nil {
			return &ValidationError{Name: "error_hash", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.error_hash": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Command(); ok {
		if err := problemfingerprint.CommandValidator(v); err != nil {
			return &ValidationError{Name: "command", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.command": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Toolchain(); ok {
		if err := problemfingerprint.ToolchainValidator(v); err != nil {
			return &ValidationError{Name: "toolchain", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.toolchain": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Service(); ok {
		if err := problemfingerprint.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.service": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RepoPathPattern(); ok {
		if err := problemfingerprint.RepoPathPatternValidator(v); err != nil {
			return &ValidationError{Name: "repo_path_pattern", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.repo_path_pattern": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Environment(); ok {
		if err := problemfingerprint.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`postgres: validator failed for field "ProblemFingerprint.environment": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`postgres: missing required field "ProblemFingerprint.created_at"`)}
	}
	return nil
}

func (_c *ProblemFingerprintCreate) sqlSave(ctx context.Context) (*ProblemFingerprint, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProblemFingerprintCreate) createSpec() (*ProblemFingerprint, *sqlgraph.CreateSpec) {
	var (
		_node = &ProblemFingerprint{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(problemfingerprint.Table, sqlgraph.NewFieldSpec(problemfingerprint.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantKey(); ok {
		_spec.SetField(problemfingerprint.FieldTenantKey, field.TypeString, value)
		_node.TenantKey = value
	}
	if value, ok := _c.mutation.InsightID(); ok {
		_spec.SetField(problemfingerprint.FieldInsightID, field.TypeUUID, value)
		_node.InsightID = value
	}
	if value, ok := _c.mutation.ErrorHash(); ok {
		_spec.SetField(problemfingerprint.FieldErrorHash, field.TypeString, value)
		_node.ErrorHash = value
	}
	if value, ok := _c.mutation.Command(); ok {
		_spec.SetField(problemfingerprint.FieldCommand, field.TypeString, value)
		_node.Command = value
	}
	if value, ok := _c.mutation.Toolchain(); ok {
		_spec.SetField(problemfingerprint.FieldToolchain, field.TypeString, value)
		_node.Toolchain = value
	}
	if value, ok := _c.mutation.Service(); ok {
		_spec.SetField(problemfingerprint.FieldService, field.TypeString, value)
		_node.Service = value
	}
	if value, ok := _c.mutation.RepoPathPattern(); ok {
		_spec.SetField(problemfingerprint.FieldRepoPathPattern, field.TypeString, value)
		_node.RepoPathPattern = value
	}
	if value, ok := _c.mutation.Environment(); ok {
		_spec.SetField(problemfingerprint.FieldEnvironment, field.TypeString, value)
		_node.Environment = value
	}
	if value, ok := _c.mutation.DependencyVersions(); ok {
		_spec.SetField(problemfingerprint.FieldDependencyVersions, field.TypeJSON, value)
		_node.DependencyVersions = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(problemfingerprint.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProblemFingerprint.Create().
//		SetTenantKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProblemFingerprintUpsert) {
//			SetTenantKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ProblemFingerprintCreate) OnConflict(opts ...sql.ConflictOption) *ProblemFingerprintUpsertOne {
	_c.conflict = opts
	return &ProblemFingerprintUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProblemFingerprint.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProblemFingerprintCreate) OnConflictColumns(columns ...string) *ProblemFingerprintUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProblemFingerprintUpsertOne{
		create: _c,
	}
}

type (
	// ProblemFingerprintUpsertOne is the builder for "upsert"-ing
	//  one ProblemFingerprint node.
	ProblemFingerprintUpsertOne struct {
		create *ProblemFingerprintCreate
	}

	// ProblemFingerprintUpsert is the "OnConflict" setter.
	ProblemFingerprintUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantKey sets the "tenant_key" field.
func (u *ProblemFingerprintUpsert) SetTenantKey(v string) *ProblemFingerprintUpsert {
	u.Set(problemfingerprint.FieldTenantKey, v)
	return u
}

// UpdateTenantKey sets the "tenant_key" field to the value that was provided on create.
func (u *ProblemFingerprintUpsert) UpdateTenantKey() *ProblemFingerprintUpsert {
	u.SetExcluded(problemfingerprint.FieldTenantKey)
	return u
}

// SetInsightID sets the "insight_id" field.
func (u *ProblemFingerprintUpsert) SetInsightID(v uuid.UUID) *ProblemFingerprintUpsert {
	u.Set(problemfingerprint.FieldInsightID, v)
	return u
}

// UpdateInsightID sets the "insight_id" field to the value that was provided on create.
func (u *ProblemFingerprintUpsert) UpdateInsightID() *ProblemFingerprintUpsert {
	u.SetExcluded(problemfingerprint.FieldInsightID)
	return u
}

// SetErrorHash sets the "error_hash" field.
func (u *ProblemFingerprintUpsert) SetErrorHash(v string) *ProblemFingerprintUpsert {
	u.Set(problemfingerprint.FieldErrorHash, v)
	return u
}

// UpdateErrorHash sets the "error_hash" field to the value that was provided on create.
func (u *ProblemFingerprintUpsert) UpdateErrorHash() *ProblemFingerprintUpsert {
	u.SetExcluded(problemfingerprint.FieldErrorHash)
	return u
}

// ClearErrorHash clears the value of the "error_hash" field.
func (u *ProblemFingerprintUpsert) ClearErrorHash() *ProblemFingerprintUpsert {
	u.SetNull(problemfingerprint.FieldErrorHash)
	return u
}

// SetCommand sets the "command" field.
func (u *ProblemFingerprintUpsert) SetCommand(v string) *ProblemFingerprintUpsert {
	u.Set(problemfingerprint.FieldCommand, v)
	return u
}

// UpdateCommand sets the "command" field to the value that was provided on create.
func (u *ProblemFingerprintUpsert) UpdateCommand() *ProblemFingerprintUpsert {
	u.SetExcluded(problemfingerprint.FieldCommand)
	return u
}

// ClearCommand clears the value of the "command" field.
func (u *ProblemFingerprintUpsert) ClearCommand() *ProblemFingerprintUpsert {
	u.SetNull(problemfingerprint.FieldCommand)
	return u
}

// SetToolchain sets the "toolchain" field.
func (u *ProblemFingerprintUpsert) SetToolchain(v string) *ProblemFingerprintUpsert {
	u.Set(problemfingerprint.FieldToolchain, v)
	return u
}

// UpdateToolchain sets the "toolchain" field to the value that was provided on create.
func (u *ProblemFingerprintUpsert) UpdateToolchain() *ProblemFingerprintUpsert {
	u.SetExcluded(problemfingerprint.FieldToolchain)
	return u
}

// ClearToolchain clears the value of the "toolchain" field.
func (u *ProblemFingerprintUpsert) ClearToolchain() *ProblemFingerprintUpsert {
	u.SetNull(problemfingerprint.FieldToolchain)
	return u
}

// SetService sets the "service" field.
func (u *ProblemFingerprintUpsert) SetService(v string) *ProblemFingerprintUpsert {
	u.Set(problemfingerprint.FieldService, v)
	return u
}

// UpdateService sets the "service" field to the value that was provided on create.
func (u *ProblemFingerprintUpsert) UpdateService() *ProblemFingerprintUpsert {
	u.SetExcluded(problemfingerprint.FieldService)
	return u
}

// ClearService clears the value of the "service" field.
func (u *ProblemFingerprintUpsert) ClearService() *ProblemFingerprintUpsert {
	u.SetNull(problemfingerprint.FieldService)
	return u
}

// SetRepoPathPattern sets the "repo_path_pattern" field.
func (u *ProblemFingerprintUpsert) SetRepoPathPattern(v string) *ProblemFingerprintUpsert {
	u.Set(problemfingerprint.FieldRepoPathPattern, v)
	return u
}

// UpdateRepoPathPattern sets the "repo_path_pattern" field to the value that was provided on create.
func (u *ProblemFingerprintUpsert) UpdateRepoPathPattern() *ProblemFingerprintUpsert {
	u.SetExcluded(problemfingerprint.FieldRepoPathPattern)
	return u
}

// ClearRepoPathPattern clears the value of the "repo_path_pattern" field.
func (u *ProblemFingerprintUpsert) ClearRepoPathPattern() *ProblemFingerprintUpsert {
	u.SetNull(problemfingerprint.FieldRepoPathPattern)
	return u
}

// SetEnvironment sets the "environment" field.
func (u *ProblemFingerprintUpsert) SetEnvironment(v string) *ProblemFingerprintUpsert {
	u.Set(problemfingerprint.FieldEnvironment, v)
	return u
}

// UpdateEnvironment sets the "environment" field to the value that was provided on create.
func (u *ProblemFingerprintUpsert) UpdateEnvironment() *ProblemFingerprintUpsert {
	u.SetExcluded(problemfingerprint.FieldEnvironment)
	return u
}

// ClearEnvironment clears the value of the "environment" field.
func (u *ProblemFingerprintUpsert) ClearEnvironment() *ProblemFingerprintUpsert {
	u.SetNull(problemfingerprint.FieldEnvironment)
	return u
}

// SetDependencyVersions sets the "dependency_versions" field.
func (u *ProblemFingerprintUpsert) SetDependencyVersions(v map[string]string) *ProblemFingerprintUpsert {
	u.Set(problemfingerprint.FieldDependencyVersions, v)
	return u
}

// UpdateDependencyVersions sets the "dependency_versions" field to the value that was provided on create.
func (u *ProblemFingerprintUpsert) UpdateDependencyVersions() *ProblemFingerprintUpsert {
	u.SetExcluded(problemfingerprint.FieldDependencyVersions)
	return u
}

// ClearDependencyVersions clears the value of the "dependency_versions" field.
func (u *ProblemFingerprintUpsert) ClearDependencyVersions() *ProblemFingerprintUpsert {
	u.SetNull(problemfingerprint.FieldDependencyVersions)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ProblemFingerprint.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(problemfingerprint.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProblemFingerprintUpsertOne) UpdateNewValues() *ProblemFingerprintUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(problemfingerprint.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(problemfingerprint.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProblemFingerprint.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProblemFingerprintUpsertOne) Ignore() *ProblemFingerprintUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProblemFingerprintUpsertOne) DoNothing() *ProblemFingerprintUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProblemFingerprintCreate.OnConflict
// documentation for more info.
func (u *ProblemFingerprintUpsertOne) Update(set func(*ProblemFingerprintUpsert)) *ProblemFingerprintUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProblemFingerprintUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantKey sets the "tenant_key" field.
func (u *ProblemFingerprintUpsertOne) SetTenantKey(v string) *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetTenantKey(v)
	})
}

// UpdateTenantKey sets the "tenant_key" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertOne) UpdateTenantKey() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateTenantKey()
	})
}

// SetInsightID sets the "insight_id" field.
func (u *ProblemFingerprintUpsertOne) SetInsightID(v uuid.UUID) *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetInsightID(v)
	})
}

// UpdateInsightID sets the "insight_id" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertOne) UpdateInsightID() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateInsightID()
	})
}

// SetErrorHash sets the "error_hash" field.
func (u *ProblemFingerprintUpsertOne) SetErrorHash(v string) *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetErrorHash(v)
	})
}

// UpdateErrorHash sets the "error_hash" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertOne) UpdateErrorHash() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateErrorHash()
	})
}

// ClearErrorHash clears the value of the "error_hash" field.
func (u *ProblemFingerprintUpsertOne) ClearErrorHash() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearErrorHash()
	})
}

// SetCommand sets the "command" field.
func (u *ProblemFingerprintUpsertOne) SetCommand(v string) *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetCommand(v)
	})
}

// UpdateCommand sets the "command" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertOne) UpdateCommand() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateCommand()
	})
}

// ClearCommand clears the value of the "command" field.
func (u *ProblemFingerprintUpsertOne) ClearCommand() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearCommand()
	})
}

// SetToolchain sets the "toolchain" field.
func (u *ProblemFingerprintUpsertOne) SetToolchain(v string) *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetToolchain(v)
	})
}

// UpdateToolchain sets the "toolchain" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertOne) UpdateToolchain() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateToolchain()
	})
}

// ClearToolchain clears the value of the "toolchain" field.
func (u *ProblemFingerprintUpsertOne) ClearToolchain() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearToolchain()
	})
}

// SetService sets the "service" field.
func (u *ProblemFingerprintUpsertOne) SetService(v string) *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetService(v)
	})
}

// UpdateService sets the "service" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertOne) UpdateService() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateService()
	})
}

// ClearService clears the value of the "service" field.
func (u *ProblemFingerprintUpsertOne) ClearService() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearService()
	})
}

// SetRepoPathPattern sets the "repo_path_pattern" field.
func (u *ProblemFingerprintUpsertOne) SetRepoPathPattern(v string) *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetRepoPathPattern(v)
	})
}

// UpdateRepoPathPattern sets the "repo_path_pattern" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertOne) UpdateRepoPathPattern() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateRepoPathPattern()
	})
}

// ClearRepoPathPattern clears the value of the "repo_path_pattern" field.
func (u *ProblemFingerprintUpsertOne) ClearRepoPathPattern() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearRepoPathPattern()
	})
}

// SetEnvironment sets the "environment" field.
func (u *ProblemFingerprintUpsertOne) SetEnvironment(v string) *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetEnvironment(v)
	})
}

// UpdateEnvironment sets the "environment" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertOne) UpdateEnvironment() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateEnvironment()
	})
}

// ClearEnvironment clears the value of the "environment" field.
func (u *ProblemFingerprintUpsertOne) ClearEnvironment() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearEnvironment()
	})
}

// SetDependencyVersions sets the "dependency_versions" field.
func (u *ProblemFingerprintUpsertOne) SetDependencyVersions(v map[string]string) *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetDependencyVersions(v)
	})
}

// UpdateDependencyVersions sets the "dependency_versions" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertOne) UpdateDependencyVersions() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateDependencyVersions()
	})
}

// ClearDependencyVersions clears the value of the "dependency_versions" field.
func (u *ProblemFingerprintUpsertOne) ClearDependencyVersions() *ProblemFingerprintUpsertOne {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearDependencyVersions()
	})
}

// Exec executes the query.
func (u *ProblemFingerprintUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("postgres: missing options for ProblemFingerprintCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProblemFingerprintUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProblemFingerprintUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("postgres: ProblemFingerprintUpsertOne.ID is not supported by MySQL driver. Use ProblemFingerprintUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProblemFingerprintUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProblemFingerprintCreateBulk is the builder for creating many ProblemFingerprint entities in bulk.
type ProblemFingerprintCreateBulk struct {
	config
	err      error
	builders []*ProblemFingerprintCreate
	conflict []sql.ConflictOption
}

// Save creates the ProblemFingerprint entities in the database.
func (_c *ProblemFingerprintCreateBulk) Save(ctx context.Context) ([]*ProblemFingerprint, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProblemFingerprint, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProblemFingerprintMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProblemFingerprintCreateBulk) SaveX(ctx context.Context) []*ProblemFingerprint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProblemFingerprintCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProblemFingerprintCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProblemFingerprint.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProblemFingerprintUpsert) {
//			SetTenantKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ProblemFingerprintCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProblemFingerprintUpsertBulk {
	_c.conflict = opts
	return &ProblemFingerprintUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProblemFingerprint.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProblemFingerprintCreateBulk) OnConflictColumns(columns ...string) *ProblemFingerprintUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProblemFingerprintUpsertBulk{
		create: _c,
	}
}

// ProblemFingerprintUpsertBulk is the builder for "upsert"-ing
// a bulk of ProblemFingerprint nodes.
type ProblemFingerprintUpsertBulk struct {
	create *ProblemFingerprintCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProblemFingerprint.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(problemfingerprint.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProblemFingerprintUpsertBulk) UpdateNewValues() *ProblemFingerprintUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(problemfingerprint.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(problemfingerprint.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProblemFingerprint.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProblemFingerprintUpsertBulk) Ignore() *ProblemFingerprintUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProblemFingerprintUpsertBulk) DoNothing() *ProblemFingerprintUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProblemFingerprintCreateBulk.OnConflict
// documentation for more info.
func (u *ProblemFingerprintUpsertBulk) Update(set func(*ProblemFingerprintUpsert)) *ProblemFingerprintUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProblemFingerprintUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantKey sets the "tenant_key" field.
func (u *ProblemFingerprintUpsertBulk) SetTenantKey(v string) *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetTenantKey(v)
	})
}

// UpdateTenantKey sets the "tenant_key" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertBulk) UpdateTenantKey() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateTenantKey()
	})
}

// SetInsightID sets the "insight_id" field.
func (u *ProblemFingerprintUpsertBulk) SetInsightID(v uuid.UUID) *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetInsightID(v)
	})
}

// UpdateInsightID sets the "insight_id" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertBulk) UpdateInsightID() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateInsightID()
	})
}

// SetErrorHash sets the "error_hash" field.
func (u *ProblemFingerprintUpsertBulk) SetErrorHash(v string) *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetErrorHash(v)
	})
}

// UpdateErrorHash sets the "error_hash" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertBulk) UpdateErrorHash() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateErrorHash()
	})
}

// ClearErrorHash clears the value of the "error_hash" field.
func (u *ProblemFingerprintUpsertBulk) ClearErrorHash() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearErrorHash()
	})
}

// SetCommand sets the "command" field.
func (u *ProblemFingerprintUpsertBulk) SetCommand(v string) *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetCommand(v)
	})
}

// UpdateCommand sets the "command" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertBulk) UpdateCommand() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateCommand()
	})
}

// ClearCommand clears the value of the "command" field.
func (u *ProblemFingerprintUpsertBulk) ClearCommand() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearCommand()
	})
}

// SetToolchain sets the "toolchain" field.
func (u *ProblemFingerprintUpsertBulk) SetToolchain(v string) *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetToolchain(v)
	})
}

// UpdateToolchain sets the "toolchain" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertBulk) UpdateToolchain() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateToolchain()
	})
}

// ClearToolchain clears the value of the "toolchain" field.
func (u *ProblemFingerprintUpsertBulk) ClearToolchain() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearToolchain()
	})
}

// SetService sets the "service" field.
func (u *ProblemFingerprintUpsertBulk) SetService(v string) *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetService(v)
	})
}

// UpdateService sets the "service" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertBulk) UpdateService() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateService()
	})
}

// ClearService clears the value of the "service" field.
func (u *ProblemFingerprintUpsertBulk) ClearService() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearService()
	})
}

// SetRepoPathPattern sets the "repo_path_pattern" field.
func (u *ProblemFingerprintUpsertBulk) SetRepoPathPattern(v string) *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetRepoPathPattern(v)
	})
}

// UpdateRepoPathPattern sets the "repo_path_pattern" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertBulk) UpdateRepoPathPattern() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateRepoPathPattern()
	})
}

// ClearRepoPathPattern clears the value of the "repo_path_pattern" field.
func (u *ProblemFingerprintUpsertBulk) ClearRepoPathPattern() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearRepoPathPattern()
	})
}

// SetEnvironment sets the "environment" field.
func (u *ProblemFingerprintUpsertBulk) SetEnvironment(v string) *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetEnvironment(v)
	})
}

// UpdateEnvironment sets the "environment" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertBulk) UpdateEnvironment() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateEnvironment()
	})
}

// ClearEnvironment clears the value of the "environment" field.
func (u *ProblemFingerprintUpsertBulk) ClearEnvironment() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearEnvironment()
	})
}

// SetDependencyVersions sets the "dependency_versions" field.
func (u *ProblemFingerprintUpsertBulk) SetDependencyVersions(v map[string]string) *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.SetDependencyVersions(v)
	})
}

// UpdateDependencyVersions sets the "dependency_versions" field to the value that was provided on create.
func (u *ProblemFingerprintUpsertBulk) UpdateDependencyVersions() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.UpdateDependencyVersions()
	})
}

// ClearDependencyVersions clears the value of the "dependency_versions" field.
func (u *ProblemFingerprintUpsertBulk) ClearDependencyVersions() *ProblemFingerprintUpsertBulk {
	return u.Update(func(s *ProblemFingerprintUpsert) {
		s.ClearDependencyVersions()
	})
}

// Exec executes the query.
func (u *ProblemFingerprintUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("postgres: OnConflict was set for builder %d. Set it on the ProblemFingerprintCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("postgres: missing options for ProblemFingerprintCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProblemFingerprintUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
