// Code generated by ent, DO NOT EDIT.

package postgres

import (
	"time"

	"github.com/google/uuid"
	"github.com/loewenthal-corp/consensus/internal/postgres/actor"
	"github.com/loewenthal-corp/consensus/internal/postgres/auditevent"
	"github.com/loewenthal-corp/consensus/internal/postgres/graphedge"
	"github.com/loewenthal-corp/consensus/internal/postgres/insight"
	"github.com/loewenthal-corp/consensus/internal/postgres/job"
	"github.com/loewenthal-corp/consensus/internal/postgres/problemfingerprint"
	"github.com/loewenthal-corp/consensus/internal/postgres/schema"
	"github.com/loewenthal-corp/consensus/internal/postgres/setting"
	"github.com/loewenthal-corp/consensus/internal/postgres/tenant"
	"github.com/loewenthal-corp/consensus/internal/postgres/vote"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	actorFields := schema.Actor{}.Fields()
	_ = actorFields
	// actorDescTenantKey is the schema descriptor for tenant_key field.
	actorDescTenantKey := actorFields[1].Descriptor()
	// actor.DefaultTenantKey holds the default value on creation for the tenant_key field.
	actor.DefaultTenantKey = actorDescTenantKey.Default.(string)
	// actor.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	actor.TenantKeyValidator = func() func(string) error {
		validators := actorDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// actorDescKind is the schema descriptor for kind field.
	actorDescKind := actorFields[2].Descriptor()
	// actor.DefaultKind holds the default value on creation for the kind field.
	actor.DefaultKind = actorDescKind.Default.(string)
	// actor.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	actor.KindValidator = func() func(string) error {
		validators := actorDescKind.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(kind string) error {
			for _, fn := range fns {
				if err := fn(kind); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// actorDescName is the schema descriptor for name field.
	actorDescName := actorFields[3].Descriptor()
	// actor.DefaultName holds the default value on creation for the name field.
	actor.DefaultName = actorDescName.Default.(string)
	// actor.NameValidator is a validator for the "name" field. It is called by the builders before save.
	actor.NameValidator = func() func(string) error {
		validators := actorDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// actorDescExternalID is the schema descriptor for external_id field.
	actorDescExternalID := actorFields[4].Descriptor()
	// actor.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	actor.ExternalIDValidator = actorDescExternalID.Validators[0].(func(string) error)
	// actorDescCreatedAt is the schema descriptor for created_at field.
	actorDescCreatedAt := actorFields[5].Descriptor()
	// actor.DefaultCreatedAt holds the default value on creation for the created_at field.
	actor.DefaultCreatedAt = actorDescCreatedAt.Default.(func() time.Time)
	// actorDescUpdatedAt is the schema descriptor for updated_at field.
	actorDescUpdatedAt := actorFields[6].Descriptor()
	// actor.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	actor.DefaultUpdatedAt = actorDescUpdatedAt.Default.(func() time.Time)
	// actor.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	actor.UpdateDefaultUpdatedAt = actorDescUpdatedAt.UpdateDefault.(func() time.Time)
	// actorDescID is the schema descriptor for id field.
	actorDescID := actorFields[0].Descriptor()
	// actor.DefaultID holds the default value on creation for the id field.
	actor.DefaultID = actorDescID.Default.(func() uuid.UUID)
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescTenantKey is the schema descriptor for tenant_key field.
	auditeventDescTenantKey := auditeventFields[1].Descriptor()
	// auditevent.DefaultTenantKey holds the default value on creation for the tenant_key field.
	auditevent.DefaultTenantKey = auditeventDescTenantKey.Default.(string)
	// auditevent.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	auditevent.TenantKeyValidator = func() func(string) error {
		validators := auditeventDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditeventDescAuthMode is the schema descriptor for auth_mode field.
	auditeventDescAuthMode := auditeventFields[3].Descriptor()
	// auditevent.DefaultAuthMode holds the default value on creation for the auth_mode field.
	auditevent.DefaultAuthMode = auditeventDescAuthMode.Default.(string)
	// auditevent.AuthModeValidator is a validator for the "auth_mode" field. It is called by the builders before save.
	auditevent.AuthModeValidator = func() func(string) error {
		validators := auditeventDescAuthMode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(auth_mode string) error {
			for _, fn := range fns {
				if err := fn(auth_mode); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditeventDescAction is the schema descriptor for action field.
	auditeventDescAction := auditeventFields[4].Descriptor()
	// auditevent.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditevent.ActionValidator = func() func(string) error {
		validators := auditeventDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditeventDescTargetKind is the schema descriptor for target_kind field.
	auditeventDescTargetKind := auditeventFields[5].Descriptor()
	// auditevent.TargetKindValidator is a validator for the "target_kind" field. It is called by the builders before save.
	auditevent.TargetKindValidator = auditeventDescTargetKind.Validators[0].(func(string) error)
	// auditeventDescTargetID is the schema descriptor for target_id field.
	auditeventDescTargetID := auditeventFields[6].Descriptor()
	// auditevent.TargetIDValidator is a validator for the "target_id" field. It is called by the builders before save.
	auditevent.TargetIDValidator = auditeventDescTargetID.Validators[0].(func(string) error)
	// auditeventDescCreatedAt is the schema descriptor for created_at field.
	auditeventDescCreatedAt := auditeventFields[8].Descriptor()
	// auditevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditevent.DefaultCreatedAt = auditeventDescCreatedAt.Default.(func() time.Time)
	// auditeventDescID is the schema descriptor for id field.
	auditeventDescID := auditeventFields[0].Descriptor()
	// auditevent.DefaultID holds the default value on creation for the id field.
	auditevent.DefaultID = auditeventDescID.Default.(func() uuid.UUID)
	graphedgeFields := schema.GraphEdge{}.Fields()
	_ = graphedgeFields
	// graphedgeDescTenantKey is the schema descriptor for tenant_key field.
	graphedgeDescTenantKey := graphedgeFields[1].Descriptor()
	// graphedge.DefaultTenantKey holds the default value on creation for the tenant_key field.
	graphedge.DefaultTenantKey = graphedgeDescTenantKey.Default.(string)
	// graphedge.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	graphedge.TenantKeyValidator = func() func(string) error {
		validators := graphedgeDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// graphedgeDescRelationship is the schema descriptor for relationship field.
	graphedgeDescRelationship := graphedgeFields[4].Descriptor()
	// graphedge.RelationshipValidator is a validator for the "relationship" field. It is called by the builders before save.
	graphedge.RelationshipValidator = func() func(string) error {
		validators := graphedgeDescRelationship.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(relationship string) error {
			for _, fn := range fns {
				if err := fn(relationship); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// graphedgeDescReviewState is the schema descriptor for review_state field.
	graphedgeDescReviewState := graphedgeFields[6].Descriptor()
	// graphedge.DefaultReviewState holds the default value on creation for the review_state field.
	graphedge.DefaultReviewState = graphedgeDescReviewState.Default.(string)
	// graphedge.ReviewStateValidator is a validator for the "review_state" field. It is called by the builders before save.
	graphedge.ReviewStateValidator = func() func(string) error {
		validators := graphedgeDescReviewState.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(review_state string) error {
			for _, fn := range fns {
				if err := fn(review_state); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// graphedgeDescCreatedAt is the schema descriptor for created_at field.
	graphedgeDescCreatedAt := graphedgeFields[8].Descriptor()
	// graphedge.DefaultCreatedAt holds the default value on creation for the created_at field.
	graphedge.DefaultCreatedAt = graphedgeDescCreatedAt.Default.(func() time.Time)
	// graphedgeDescUpdatedAt is the schema descriptor for updated_at field.
	graphedgeDescUpdatedAt := graphedgeFields[9].Descriptor()
	// graphedge.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	graphedge.DefaultUpdatedAt = graphedgeDescUpdatedAt.Default.(func() time.Time)
	// graphedge.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	graphedge.UpdateDefaultUpdatedAt = graphedgeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// graphedgeDescID is the schema descriptor for id field.
	graphedgeDescID := graphedgeFields[0].Descriptor()
	// graphedge.DefaultID holds the default value on creation for the id field.
	graphedge.DefaultID = graphedgeDescID.Default.(func() uuid.UUID)
	insightFields := schema.Insight{}.Fields()
	_ = insightFields
	// insightDescTenantKey is the schema descriptor for tenant_key field.
	insightDescTenantKey := insightFields[1].Descriptor()
	// insight.DefaultTenantKey holds the default value on creation for the tenant_key field.
	insight.DefaultTenantKey = insightDescTenantKey.Default.(string)
	// insight.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	insight.TenantKeyValidator = func() func(string) error {
		validators := insightDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// insightDescTitle is the schema descriptor for title field.
	insightDescTitle := insightFields[2].Descriptor()
	// insight.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	insight.TitleValidator = func() func(string) error {
		validators := insightDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// insightDescAnswer is the schema descriptor for answer field.
	insightDescAnswer := insightFields[4].Descriptor()
	// insight.AnswerValidator is a validator for the "answer" field. It is called by the builders before save.
	insight.AnswerValidator = func() func(string) error {
		validators := insightDescAnswer.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(answer string) error {
			for _, fn := range fns {
				if err := fn(answer); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// insightDescSourceRunID is the schema descriptor for source_run_id field.
	insightDescSourceRunID := insightFields[11].Descriptor()
	// insight.SourceRunIDValidator is a validator for the "source_run_id" field. It is called by the builders before save.
	insight.SourceRunIDValidator = insightDescSourceRunID.Validators[0].(func(string) error)
	// insightDescReviewState is the schema descriptor for review_state field.
	insightDescReviewState := insightFields[12].Descriptor()
	// insight.DefaultReviewState holds the default value on creation for the review_state field.
	insight.DefaultReviewState = insightDescReviewState.Default.(string)
	// insight.ReviewStateValidator is a validator for the "review_state" field. It is called by the builders before save.
	insight.ReviewStateValidator = func() func(string) error {
		validators := insightDescReviewState.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(review_state string) error {
			for _, fn := range fns {
				if err := fn(review_state); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// insightDescLifecycleState is the schema descriptor for lifecycle_state field.
	insightDescLifecycleState := insightFields[13].Descriptor()
	// insight.DefaultLifecycleState holds the default value on creation for the lifecycle_state field.
	insight.DefaultLifecycleState = insightDescLifecycleState.Default.(string)
	// insight.LifecycleStateValidator is a validator for the "lifecycle_state" field. It is called by the builders before save.
	insight.LifecycleStateValidator = func() func(string) error {
		validators := insightDescLifecycleState.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(lifecycle_state string) error {
			for _, fn := range fns {
				if err := fn(lifecycle_state); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// insightDescCreatedAt is the schema descriptor for created_at field.
	insightDescCreatedAt := insightFields[16].Descriptor()
	// insight.DefaultCreatedAt holds the default value on creation for the created_at field.
	insight.DefaultCreatedAt = insightDescCreatedAt.Default.(func() time.Time)
	// insightDescUpdatedAt is the schema descriptor for updated_at field.
	insightDescUpdatedAt := insightFields[17].Descriptor()
	// insight.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	insight.DefaultUpdatedAt = insightDescUpdatedAt.Default.(func() time.Time)
	// insight.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	insight.UpdateDefaultUpdatedAt = insightDescUpdatedAt.UpdateDefault.(func() time.Time)
	// insightDescID is the schema descriptor for id field.
	insightDescID := insightFields[0].Descriptor()
	// insight.DefaultID holds the default value on creation for the id field.
	insight.DefaultID = insightDescID.Default.(func() uuid.UUID)
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescTenantKey is the schema descriptor for tenant_key field.
	jobDescTenantKey := jobFields[1].Descriptor()
	// job.DefaultTenantKey holds the default value on creation for the tenant_key field.
	job.DefaultTenantKey = jobDescTenantKey.Default.(string)
	// job.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	job.TenantKeyValidator = func() func(string) error {
		validators := jobDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// jobDescKind is the schema descriptor for kind field.
	jobDescKind := jobFields[2].Descriptor()
	// job.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	job.KindValidator = func() func(string) error {
		validators := jobDescKind.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(kind string) error {
			for _, fn := range fns {
				if err := fn(kind); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// jobDescStatus is the schema descriptor for status field.
	jobDescStatus := jobFields[3].Descriptor()
	// job.DefaultStatus holds the default value on creation for the status field.
	job.DefaultStatus = jobDescStatus.Default.(string)
	// job.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	job.StatusValidator = func() func(string) error {
		validators := jobDescStatus.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(status string) error {
			for _, fn := range fns {
				if err := fn(status); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// jobDescAttempts is the schema descriptor for attempts field.
	jobDescAttempts := jobFields[6].Descriptor()
	// job.DefaultAttempts holds the default value on creation for the attempts field.
	job.DefaultAttempts = jobDescAttempts.Default.(int)
	// jobDescRunAt is the schema descriptor for run_at field.
	jobDescRunAt := jobFields[7].Descriptor()
	// job.DefaultRunAt holds the default value on creation for the run_at field.
	job.DefaultRunAt = jobDescRunAt.Default.(func() time.Time)
	// jobDescCreatedAt is the schema descriptor for created_at field.
	jobDescCreatedAt := jobFields[8].Descriptor()
	// job.DefaultCreatedAt holds the default value on creation for the created_at field.
	job.DefaultCreatedAt = jobDescCreatedAt.Default.(func() time.Time)
	// jobDescUpdatedAt is the schema descriptor for updated_at field.
	jobDescUpdatedAt := jobFields[9].Descriptor()
	// job.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	job.DefaultUpdatedAt = jobDescUpdatedAt.Default.(func() time.Time)
	// job.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	job.UpdateDefaultUpdatedAt = jobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// jobDescID is the schema descriptor for id field.
	jobDescID := jobFields[0].Descriptor()
	// job.DefaultID holds the default value on creation for the id field.
	job.DefaultID = jobDescID.Default.(func() uuid.UUID)
	problemfingerprintFields := schema.ProblemFingerprint{}.Fields()
	_ = problemfingerprintFields
	// problemfingerprintDescTenantKey is the schema descriptor for tenant_key field.
	problemfingerprintDescTenantKey := problemfingerprintFields[1].Descriptor()
	// problemfingerprint.DefaultTenantKey holds the default value on creation for the tenant_key field.
	problemfingerprint.DefaultTenantKey = problemfingerprintDescTenantKey.Default.(string)
	// problemfingerprint.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	problemfingerprint.TenantKeyValidator = func() func(string) error {
		validators := problemfingerprintDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// problemfingerprintDescErrorHash is the schema descriptor for error_hash field.
	problemfingerprintDescErrorHash := problemfingerprintFields[3].Descriptor()
	// problemfingerprint.ErrorHashValidator is a validator for the "error_hash" field. It is called by the builders before save.
	problemfingerprint.ErrorHashValidator = problemfingerprintDescErrorHash.Validators[0].(func(string) error)
	// problemfingerprintDescCommand is the schema descriptor for command field.
	problemfingerprintDescCommand := problemfingerprintFields[4].Descriptor()
	// problemfingerprint.CommandValidator is a validator for the "command" field. It is called by the builders before save.
	problemfingerprint.CommandValidator = problemfingerprintDescCommand.Validators[0].(func(string) error)
	// problemfingerprintDescToolchain is the schema descriptor for toolchain field.
	problemfingerprintDescToolchain := problemfingerprintFields[5].Descriptor()
	// problemfingerprint.ToolchainValidator is a validator for the "toolchain" field. It is called by the builders before save.
	problemfingerprint.ToolchainValidator = problemfingerprintDescToolchain.Validators[0].(func(string) error)
	// problemfingerprintDescService is the schema descriptor for service field.
	problemfingerprintDescService := problemfingerprintFields[6].Descriptor()
	// problemfingerprint.ServiceValidator is a validator for the "service" field. It is called by the builders before save.
	problemfingerprint.ServiceValidator = problemfingerprintDescService.Validators[0].(func(string) error)
	// problemfingerprintDescRepoPathPattern is the schema descriptor for repo_path_pattern field.
	problemfingerprintDescRepoPathPattern := problemfingerprintFields[7].Descriptor()
	// problemfingerprint.RepoPathPatternValidator is a validator for the "repo_path_pattern" field. It is called by the builders before save.
	problemfingerprint.RepoPathPatternValidator = problemfingerprintDescRepoPathPattern.Validators[0].(func(string) error)
	// problemfingerprintDescEnvironment is the schema descriptor for environment field.
	problemfingerprintDescEnvironment := problemfingerprintFields[8].Descriptor()
	// problemfingerprint.EnvironmentValidator is a validator for the "environment" field. It is called by the builders before save.
	problemfingerprint.EnvironmentValidator = problemfingerprintDescEnvironment.Validators[0].(func(string) error)
	// problemfingerprintDescCreatedAt is the schema descriptor for created_at field.
	problemfingerprintDescCreatedAt := problemfingerprintFields[10].Descriptor()
	// problemfingerprint.DefaultCreatedAt holds the default value on creation for the created_at field.
	problemfingerprint.DefaultCreatedAt = problemfingerprintDescCreatedAt.Default.(func() time.Time)
	// problemfingerprintDescID is the schema descriptor for id field.
	problemfingerprintDescID := problemfingerprintFields[0].Descriptor()
	// problemfingerprint.DefaultID holds the default value on creation for the id field.
	problemfingerprint.DefaultID = problemfingerprintDescID.Default.(func() uuid.UUID)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescTenantKey is the schema descriptor for tenant_key field.
	settingDescTenantKey := settingFields[1].Descriptor()
	// setting.DefaultTenantKey holds the default value on creation for the tenant_key field.
	setting.DefaultTenantKey = settingDescTenantKey.Default.(string)
	// setting.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	setting.TenantKeyValidator = func() func(string) error {
		validators := settingDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[2].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = func() func(string) error {
		validators := settingDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingFields[4].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingFields[5].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// settingDescID is the schema descriptor for id field.
	settingDescID := settingFields[0].Descriptor()
	// setting.DefaultID holds the default value on creation for the id field.
	setting.DefaultID = settingDescID.Default.(func() uuid.UUID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescKey is the schema descriptor for key field.
	tenantDescKey := tenantFields[1].Descriptor()
	// tenant.DefaultKey holds the default value on creation for the key field.
	tenant.DefaultKey = tenantDescKey.Default.(string)
	// tenant.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	tenant.KeyValidator = func() func(string) error {
		validators := tenantDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[2].Descriptor()
	// tenant.DefaultName holds the default value on creation for the name field.
	tenant.DefaultName = tenantDescName.Default.(string)
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = func() func(string) error {
		validators := tenantDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[3].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[4].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
	voteFields := schema.Vote{}.Fields()
	_ = voteFields
	// voteDescTenantKey is the schema descriptor for tenant_key field.
	voteDescTenantKey := voteFields[1].Descriptor()
	// vote.DefaultTenantKey holds the default value on creation for the tenant_key field.
	vote.DefaultTenantKey = voteDescTenantKey.Default.(string)
	// vote.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	vote.TenantKeyValidator = func() func(string) error {
		validators := voteDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// voteDescOutcome is the schema descriptor for outcome field.
	voteDescOutcome := voteFields[5].Descriptor()
	// vote.OutcomeValidator is a validator for the "outcome" field. It is called by the builders before save.
	vote.OutcomeValidator = func() func(string) error {
		validators := voteDescOutcome.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(outcome string) error {
			for _, fn := range fns {
				if err := fn(outcome); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// voteDescConfidence is the schema descriptor for confidence field.
	voteDescConfidence := voteFields[6].Descriptor()
	// vote.DefaultConfidence holds the default value on creation for the confidence field.
	vote.DefaultConfidence = voteDescConfidence.Default.(float64)
	// voteDescIdempotencyKey is the schema descriptor for idempotency_key field.
	voteDescIdempotencyKey := voteFields[8].Descriptor()
	// vote.IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	vote.IdempotencyKeyValidator = voteDescIdempotencyKey.Validators[0].(func(string) error)
	// voteDescCreatedAt is the schema descriptor for created_at field.
	voteDescCreatedAt := voteFields[9].Descriptor()
	// vote.DefaultCreatedAt holds the default value on creation for the created_at field.
	vote.DefaultCreatedAt = voteDescCreatedAt.Default.(func() time.Time)
	// voteDescID is the schema descriptor for id field.
	voteDescID := voteFields[0].Descriptor()
	// vote.DefaultID holds the default value on creation for the id field.
	vote.DefaultID = voteDescID.Default.(func() uuid.UUID)
}
